{
 "title": "Cilium Metrics",
 "description": "Dashboard for Cilium (https://cilium.io/) metrics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": "label_values(kube_pod_created{pod=~\"^cilium-[a-z|A-Z|0-9]+$\"},pod)"
   }
  ]
 },
 "panels": [
  { "title": "Cilium process status", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 } },
  { "title": "Cilium  overview status", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 } },
  {
   "title": "Virtual Memmory Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(cilium_process_virtual_memory_bytes{kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "MAX_virtual_memory_bytes"
    },
    {
     "expr": "avg(cilium_process_virtual_memory_bytes{kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "AVG_virtual_memory_bytes"
    },
    {
     "expr": "min(cilium_process_virtual_memory_bytes{kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "MIN_virtual_memory_bytes"
    }
   ]
  },
  {
   "title": "Resident memory status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(cilium_process_resident_memory_bytes{kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "AVG_resident_memory_bytes"
    },
    {
     "expr": "max(cilium_process_resident_memory_bytes{kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "MAX_resident_memory_bytes_max"
    },
    {
     "expr": "min(cilium_process_resident_memory_bytes{kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "MIN_resident_memory_bytes_min"
    }
   ]
  },
  {
   "title": "CPU Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(cilium_process_cpu_seconds_total{kubernetes_pod_name=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Endpoints policy enforcement status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cilium_policy_endpoint_enforcement_status{kubernetes_pod_name=~\"$pod\"}) by (enforcement)",
     "legendFormat": "{{enforcement}}"
    }
   ]
  },
  {
   "title": "L7 parser errors",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cilium_policy_l7_parse_errors_total{kubernetes_pod_name=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Policy Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(cilium_policy_count{kubernetes_pod_name=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Max open fds",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(cilium_process_open_fds{kubernetes_pod_name=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Policy Errors",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(cilium_policy_import_errors{kubernetes_pod_name=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Failing controllers",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cilium_controllers_failing{kubernetes_pod_name=~\"$pod\"})"
    }
   ]
  },
  { "title": "Cilium network information", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 9 } },
  {
   "title": "Cilium drops Ingress",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_drop_count_total{direction=\"INGRESS\", kubernetes_pod_name=~\"$pod\"}[5m])) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Cilium drops Egress",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_drop_count_total{direction=\"EGRESS\", kubernetes_pod_name=~\"$pod\"}[5m])) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Endpoint regenerations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_endpoint_regenerations{kubernetes_pod_name=~\"$pod\"}[5m])) by(outcome)",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "Cilium endpoint state",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cilium_endpoint_state{kubernetes_pod_name=~\"$pod\"}) by (endpoint_state)",
     "legendFormat": "{{endpoint_state}}"
    }
   ]
  },
  {
   "title": "L7 forwarded request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_policy_l7_denied_total{kubernetes_pod_name=~\"$pod\"}[5m]))",
     "legendFormat": "L7 denied request"
    },
    {
     "expr": "sum(rate(cilium_policy_l7_forwarded_total{kubernetes_pod_name=~\"$pod\"}[5m]))",
     "legendFormat": "L7 forwarded request"
    }
   ]
  },
  {
   "title": "Conntrack_GC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cilium_datapath_conntrack_gc_entries{kubernetes_pod_name=~\"$pod\", status=\"alive\"}) by (family,status)",
     "legendFormat": "Alive CT entries {{family}}"
    },
    {
     "expr": "sum(cilium_datapath_conntrack_gc_entries{kubernetes_pod_name=~\"$pod\", status=\"deleted\"}) by (family,status)",
     "legendFormat": "Deleted CT entries {{family}}"
    }
   ]
  },
  {
   "title": "Endpoint regeneration time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(cilium_endpoint_regeneration_time_stats_seconds_sum{kubernetes_pod_name=~\"$pod\"} / cilium_endpoint_regeneration_time_stats_seconds_count{kubernetes_pod_name=~\"$pod\"} ) by (scope)",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  { "title": "Kubernetes integration", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 25 } },
  {
   "title": "Kubernetes Watcher",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(cilium_kubernetes_events_total{kubernetes_pod_name=~\"$pod\"}[5m])) by (status,action, scope)"
    }
   ]
  }
 ]
}