apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "fqdn"
specs:
  - endpointSelector:
      matchLabels:
        org: empire
        class: mediabot
    egress:
    - toFQDNs:
        - matchPattern: "*.twitter.com"  
      toPorts:
      - ports:
        - port: "443"
          protocol: TCP 
      - ports:
        - port: "80"
          protocol: TCP
        rules:
          http:
          - method: "GET"  
  - endpointSelector:
      matchLabels:
        org: empire
        class: mediabot
    egress:
      - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kube-system
            "k8s:k8s-app": kube-dns
        toPorts:
        - ports:
          - port: "53"
            protocol: ANY
          rules:
            dns:
            - matchPattern: "*"
