{{- if and .Values.prometheus.enabled .Values.prometheus.tls.enabled .Values.prometheus.tls.auto.enabled (eq .Values.prometheus.tls.auto.method "certmanager") }}
{{- $cn := list (.Values.cluster.name | replace "." "-") "agent-metrics.cilium.io" | join "." }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.prometheus.tls.server.existingSecret | default "agent-metrics-server-certs" }}
  namespace: {{ include "cilium.namespace" . }}
  {{- with .Values.commonLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  issuerRef:
    {{- toYaml .Values.prometheus.tls.auto.certManagerIssuerRef | nindent 4 }}
  secretName: {{ .Values.prometheus.tls.server.existingSecret | default "agent-metrics-server-certs" }}
  commonName: {{ $cn | quote }}
  dnsNames:
  - {{ $cn | quote }}
  {{- range $dns := .Values.prometheus.tls.server.extraDnsNames }}
  - {{ $dns | quote }}
  {{- end }}
  {{- if .Values.prometheus.tls.server.extraIpAddresses }}
  ipAddresses:
  {{- range $ip := .Values.prometheus.tls.server.extraIpAddresses }}
  - {{ $ip | quote }}
  {{- end }}
  {{- end }}
  duration: {{ printf "%dh0m0s" (mul .Values.prometheus.tls.auto.certValidityDuration 24) }}
  privateKey:
    rotationPolicy: Always
  isCA: false
  usages:
    - signing
    - key encipherment
    - server auth
{{- end }}
