//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by deepcopy-gen. DO NOT EDIT.

package sockmap

import (
	types "github.com/cilium/cilium/pkg/bpf/types"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SockmapKey) DeepCopyInto(out *SockmapKey) {
	*out = *in
	in.DIP.DeepCopyInto(&out.DIP)
	in.SIP.DeepCopyInto(&out.SIP)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SockmapKey.
func (in *SockmapKey) DeepCopy() *SockmapKey {
	if in == nil {
		return nil
	}
	out := new(SockmapKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyMapKey is an autogenerated deepcopy function, copying the receiver, creating a new types.MapKey.
func (in *SockmapKey) DeepCopyMapKey() types.MapKey {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SockmapValue) DeepCopyInto(out *SockmapValue) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SockmapValue.
func (in *SockmapValue) DeepCopy() *SockmapValue {
	if in == nil {
		return nil
	}
	out := new(SockmapValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyMapValue is an autogenerated deepcopy function, copying the receiver, creating a new types.MapValue.
func (in *SockmapValue) DeepCopyMapValue() types.MapValue {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
