// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	ciliumiov2alpha1 "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/typed/cilium.io/v2alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeCiliumResourceIPPools implements CiliumResourceIPPoolInterface
type fakeCiliumResourceIPPools struct {
	*gentype.FakeClientWithList[*v2alpha1.CiliumResourceIPPool, *v2alpha1.CiliumResourceIPPoolList]
	Fake *FakeCiliumV2alpha1
}

func newFakeCiliumResourceIPPools(fake *FakeCiliumV2alpha1) ciliumiov2alpha1.CiliumResourceIPPoolInterface {
	return &fakeCiliumResourceIPPools{
		gentype.NewFakeClientWithList[*v2alpha1.CiliumResourceIPPool, *v2alpha1.CiliumResourceIPPoolList](
			fake.Fake,
			"",
			v2alpha1.SchemeGroupVersion.WithResource("ciliumresourceippools"),
			v2alpha1.SchemeGroupVersion.WithKind("CiliumResourceIPPool"),
			func() *v2alpha1.CiliumResourceIPPool { return &v2alpha1.CiliumResourceIPPool{} },
			func() *v2alpha1.CiliumResourceIPPoolList { return &v2alpha1.CiliumResourceIPPoolList{} },
			func(dst, src *v2alpha1.CiliumResourceIPPoolList) { dst.ListMeta = src.ListMeta },
			func(list *v2alpha1.CiliumResourceIPPoolList) []*v2alpha1.CiliumResourceIPPool {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v2alpha1.CiliumResourceIPPoolList, items []*v2alpha1.CiliumResourceIPPool) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
