// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	ciliumiov2alpha1 "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/typed/cilium.io/v2alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeCiliumResourceNetworkConfigs implements CiliumResourceNetworkConfigInterface
type fakeCiliumResourceNetworkConfigs struct {
	*gentype.FakeClientWithList[*v2alpha1.CiliumResourceNetworkConfig, *v2alpha1.CiliumResourceNetworkConfigList]
	Fake *FakeCiliumV2alpha1
}

func newFakeCiliumResourceNetworkConfigs(fake *FakeCiliumV2alpha1) ciliumiov2alpha1.CiliumResourceNetworkConfigInterface {
	return &fakeCiliumResourceNetworkConfigs{
		gentype.NewFakeClientWithList[*v2alpha1.CiliumResourceNetworkConfig, *v2alpha1.CiliumResourceNetworkConfigList](
			fake.Fake,
			"",
			v2alpha1.SchemeGroupVersion.WithResource("ciliumresourcenetworkconfigs"),
			v2alpha1.SchemeGroupVersion.WithKind("CiliumResourceNetworkConfig"),
			func() *v2alpha1.CiliumResourceNetworkConfig { return &v2alpha1.CiliumResourceNetworkConfig{} },
			func() *v2alpha1.CiliumResourceNetworkConfigList { return &v2alpha1.CiliumResourceNetworkConfigList{} },
			func(dst, src *v2alpha1.CiliumResourceNetworkConfigList) { dst.ListMeta = src.ListMeta },
			func(list *v2alpha1.CiliumResourceNetworkConfigList) []*v2alpha1.CiliumResourceNetworkConfig {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v2alpha1.CiliumResourceNetworkConfigList, items []*v2alpha1.CiliumResourceNetworkConfig) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
