FROM cilium/dependencies:0.13.90
LABEL maintainer="andre@cilium.io"
# New packages can be added by appending ../cp-dirs
ADD . /tmp/cilium-net-build/src/github.com/cilium/cilium
RUN cd /tmp/cilium-net-build/src/github.com/cilium/cilium && \
export GOROOT=/usr/local/go && \
export GOPATH=/tmp/cilium-net-build && \
export PATH="$GOROOT/bin:/usr/local/clang+llvm/bin:$GOPATH/bin:$PATH" && \
make clean-container build && \
make PKG_BUILD=1 install && \

# bash-completion-begin
mkdir -p /root && \
echo ". /etc/profile.d/bash_completion.sh" >> /root/.bashrc && \
cilium completion bash >> /root/.bashrc && \
# bash-completion-end

groupadd -f cilium

ADD plugins/cilium-cni/cni-install.sh /cni-install.sh
ADD plugins/cilium-cni/cni-uninstall.sh /cni-uninstall.sh

ENV PATH="/usr/local/clang+llvm/bin:$PATH"
ENV INITSYSTEM="SYSTEMD"

CMD ["/usr/bin/cilium"]
