# Copyright Authors of Cilium
# SPDX-License-Identifier: Apache-2.0

##@ Development (Remote)

define VALUES_FILES
--helm-values=$(ROOT_DIR)/contrib/testing/remote-values.yaml
endef

.PHONY: cluster-install-cilium
cluster-install-cilium: check_deps
	@echo "  INSTALL cilium"
	# cilium-cli doesn't support idempotent installs, so we uninstall and
	# reinstall here. https://github.com/cilium/cilium-cli/issues/205
	-@$(CILIUM_CLI) uninstall >/dev/null 2>&1 || true

	# cilium-cli's --wait flag doesn't work, so we just force it to run
	# in the background instead and wait for the resources to be available.
	# https://github.com/cilium/cilium-cli/issues/1070
	$(CILIUM_CLI) install \
		--chart-directory=$(ROOT_DIR)/install/kubernetes/cilium \
		$(VALUES_FILES) \
		--version= \
		>/dev/null 2>&1 &
