// Code generated by protoc-gen-go. DO NOT EDIT.
// source: envoy/api/v2/cds.proto

/*
Package v2 is a generated protocol buffer package.

It is generated from these files:
	envoy/api/v2/cds.proto
	envoy/api/v2/discovery.proto
	envoy/api/v2/eds.proto
	envoy/api/v2/lds.proto
	envoy/api/v2/rds.proto

It has these top-level messages:
	Cluster
	UpstreamBindConfig
	DiscoveryRequest
	DiscoveryResponse
	ClusterLoadAssignment
	Listener
	RouteConfiguration
*/
package v2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import envoy_api_v2_core "github.com/cilium/cilium/pkg/envoy/envoy/api/v2/core"
import envoy_api_v2_auth "github.com/cilium/cilium/pkg/envoy/envoy/api/v2/auth"
import envoy_api_v2_core1 "github.com/cilium/cilium/pkg/envoy/envoy/api/v2/core"
import envoy_api_v2_core3 "github.com/cilium/cilium/pkg/envoy/envoy/api/v2/core"
import envoy_api_v2_core4 "github.com/cilium/cilium/pkg/envoy/envoy/api/v2/core"
import envoy_api_v2_core5 "github.com/cilium/cilium/pkg/envoy/envoy/api/v2/core"
import envoy_api_v2_cluster "github.com/cilium/cilium/pkg/envoy/envoy/api/v2/cluster"
import envoy_api_v2_cluster1 "github.com/cilium/cilium/pkg/envoy/envoy/api/v2/cluster"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf2 "github.com/golang/protobuf/ptypes/duration"
import google_protobuf4 "github.com/golang/protobuf/ptypes/struct"
import google_protobuf "github.com/golang/protobuf/ptypes/wrappers"
import _ "github.com/lyft/protoc-gen-validate/validate"
import _ "github.com/gogo/protobuf/gogoproto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Refer to :ref:`service discovery type <arch_overview_service_discovery_types>`
// for an explanation on each type.
type Cluster_DiscoveryType int32

const (
	// Refer to the :ref:`static discovery type<arch_overview_service_discovery_types_static>`
	// for an explanation.
	Cluster_STATIC Cluster_DiscoveryType = 0
	// Refer to the :ref:`strict DNS discovery
	// type<arch_overview_service_discovery_types_strict_dns>`
	// for an explanation.
	Cluster_STRICT_DNS Cluster_DiscoveryType = 1
	// Refer to the :ref:`logical DNS discovery
	// type<arch_overview_service_discovery_types_logical_dns>`
	// for an explanation.
	Cluster_LOGICAL_DNS Cluster_DiscoveryType = 2
	// Refer to the :ref:`service discovery type<arch_overview_service_discovery_types_sds>`
	// for an explanation.
	Cluster_EDS Cluster_DiscoveryType = 3
	// Refer to the :ref:`original destination discovery
	// type<arch_overview_service_discovery_types_original_destination>`
	// for an explanation.
	Cluster_ORIGINAL_DST Cluster_DiscoveryType = 4
)

var Cluster_DiscoveryType_name = map[int32]string{
	0: "STATIC",
	1: "STRICT_DNS",
	2: "LOGICAL_DNS",
	3: "EDS",
	4: "ORIGINAL_DST",
}
var Cluster_DiscoveryType_value = map[string]int32{
	"STATIC":       0,
	"STRICT_DNS":   1,
	"LOGICAL_DNS":  2,
	"EDS":          3,
	"ORIGINAL_DST": 4,
}

func (x Cluster_DiscoveryType) String() string {
	return proto.EnumName(Cluster_DiscoveryType_name, int32(x))
}
func (Cluster_DiscoveryType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

// Refer to :ref:`load balancer type <arch_overview_load_balancing_types>` architecture
// overview section for information on each type.
type Cluster_LbPolicy int32

const (
	// Refer to the :ref:`round robin load balancing
	// policy<arch_overview_load_balancing_types_round_robin>`
	// for an explanation.
	Cluster_ROUND_ROBIN Cluster_LbPolicy = 0
	// Refer to the :ref:`least request load balancing
	// policy<arch_overview_load_balancing_types_least_request>`
	// for an explanation.
	Cluster_LEAST_REQUEST Cluster_LbPolicy = 1
	// Refer to the :ref:`ring hash load balancing
	// policy<arch_overview_load_balancing_types_ring_hash>`
	// for an explanation.
	Cluster_RING_HASH Cluster_LbPolicy = 2
	// Refer to the :ref:`random load balancing
	// policy<arch_overview_load_balancing_types_random>`
	// for an explanation.
	Cluster_RANDOM Cluster_LbPolicy = 3
	// Refer to the :ref:`original destination load balancing
	// policy<arch_overview_load_balancing_types_original_destination>`
	// for an explanation.
	Cluster_ORIGINAL_DST_LB Cluster_LbPolicy = 4
)

var Cluster_LbPolicy_name = map[int32]string{
	0: "ROUND_ROBIN",
	1: "LEAST_REQUEST",
	2: "RING_HASH",
	3: "RANDOM",
	4: "ORIGINAL_DST_LB",
}
var Cluster_LbPolicy_value = map[string]int32{
	"ROUND_ROBIN":     0,
	"LEAST_REQUEST":   1,
	"RING_HASH":       2,
	"RANDOM":          3,
	"ORIGINAL_DST_LB": 4,
}

func (x Cluster_LbPolicy) String() string {
	return proto.EnumName(Cluster_LbPolicy_name, int32(x))
}
func (Cluster_LbPolicy) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

// When V4_ONLY is selected, the DNS resolver will only perform a lookup for
// addresses in the IPv4 family. If V6_ONLY is selected, the DNS resolver will
// only perform a lookup for addresses in the IPv6 family. If AUTO is
// specified, the DNS resolver will first perform a lookup for addresses in
// the IPv6 family and fallback to a lookup for addresses in the IPv4 family.
// For cluster types other than
// :ref:`STRICT_DNS<envoy_api_enum_value_Cluster.DiscoveryType.STRICT_DNS>` and
// :ref:`LOGICAL_DNS<envoy_api_enum_value_Cluster.DiscoveryType.LOGICAL_DNS>`,
// this setting is
// ignored.
type Cluster_DnsLookupFamily int32

const (
	Cluster_AUTO    Cluster_DnsLookupFamily = 0
	Cluster_V4_ONLY Cluster_DnsLookupFamily = 1
	Cluster_V6_ONLY Cluster_DnsLookupFamily = 2
)

var Cluster_DnsLookupFamily_name = map[int32]string{
	0: "AUTO",
	1: "V4_ONLY",
	2: "V6_ONLY",
}
var Cluster_DnsLookupFamily_value = map[string]int32{
	"AUTO":    0,
	"V4_ONLY": 1,
	"V6_ONLY": 2,
}

func (x Cluster_DnsLookupFamily) String() string {
	return proto.EnumName(Cluster_DnsLookupFamily_name, int32(x))
}
func (Cluster_DnsLookupFamily) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 2} }

type Cluster_ClusterProtocolSelection int32

const (
	// Cluster can only operate on one of the possible upstream protocols (HTTP1.1, HTTP2).
	// If :ref:`http2_protocol_options <envoy_api_field_Cluster.http2_protocol_options>` are
	// present, HTTP2 will be used, otherwise HTTP1.1 will be used.
	Cluster_USE_CONFIGURED_PROTOCOL Cluster_ClusterProtocolSelection = 0
	// Use HTTP1.1 or HTTP2, depending on which one is used on the downstream connection.
	Cluster_USE_DOWNSTREAM_PROTOCOL Cluster_ClusterProtocolSelection = 1
)

var Cluster_ClusterProtocolSelection_name = map[int32]string{
	0: "USE_CONFIGURED_PROTOCOL",
	1: "USE_DOWNSTREAM_PROTOCOL",
}
var Cluster_ClusterProtocolSelection_value = map[string]int32{
	"USE_CONFIGURED_PROTOCOL": 0,
	"USE_DOWNSTREAM_PROTOCOL": 1,
}

func (x Cluster_ClusterProtocolSelection) String() string {
	return proto.EnumName(Cluster_ClusterProtocolSelection_name, int32(x))
}
func (Cluster_ClusterProtocolSelection) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 3}
}

// If NO_FALLBACK is selected, a result
// equivalent to no healthy hosts is reported. If ANY_ENDPOINT is selected,
// any cluster endpoint may be returned (subject to policy, health checks,
// etc). If DEFAULT_SUBSET is selected, load balancing is performed over the
// endpoints matching the values from the default_subset field.
type Cluster_LbSubsetConfig_LbSubsetFallbackPolicy int32

const (
	Cluster_LbSubsetConfig_NO_FALLBACK    Cluster_LbSubsetConfig_LbSubsetFallbackPolicy = 0
	Cluster_LbSubsetConfig_ANY_ENDPOINT   Cluster_LbSubsetConfig_LbSubsetFallbackPolicy = 1
	Cluster_LbSubsetConfig_DEFAULT_SUBSET Cluster_LbSubsetConfig_LbSubsetFallbackPolicy = 2
)

var Cluster_LbSubsetConfig_LbSubsetFallbackPolicy_name = map[int32]string{
	0: "NO_FALLBACK",
	1: "ANY_ENDPOINT",
	2: "DEFAULT_SUBSET",
}
var Cluster_LbSubsetConfig_LbSubsetFallbackPolicy_value = map[string]int32{
	"NO_FALLBACK":    0,
	"ANY_ENDPOINT":   1,
	"DEFAULT_SUBSET": 2,
}

func (x Cluster_LbSubsetConfig_LbSubsetFallbackPolicy) String() string {
	return proto.EnumName(Cluster_LbSubsetConfig_LbSubsetFallbackPolicy_name, int32(x))
}
func (Cluster_LbSubsetConfig_LbSubsetFallbackPolicy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 1, 0}
}

// Configuration for a single upstream cluster.
// [#comment:next free field: 28]
type Cluster struct {
	// Supplies the name of the cluster which must be unique across all clusters.
	// The cluster name is used when emitting
	// :ref:`statistics <config_cluster_manager_cluster_stats>`.
	// Any ``:`` in the cluster name will be converted to ``_`` when emitting statistics.
	// By default, the maximum length of a cluster name is limited to 60
	// characters. This limit can be increased by setting the
	// :option:`--max-obj-name-len` command line argument to the desired value.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// The :ref:`service discovery type <arch_overview_service_discovery_types>`
	// to use for resolving the cluster.
	Type Cluster_DiscoveryType `protobuf:"varint,2,opt,name=type,enum=envoy.api.v2.Cluster_DiscoveryType" json:"type,omitempty"`
	// Configuration to use for EDS updates for the Cluster.
	EdsClusterConfig *Cluster_EdsClusterConfig `protobuf:"bytes,3,opt,name=eds_cluster_config,json=edsClusterConfig" json:"eds_cluster_config,omitempty"`
	// The timeout for new network connections to hosts in the cluster.
	ConnectTimeout *google_protobuf2.Duration `protobuf:"bytes,4,opt,name=connect_timeout,json=connectTimeout" json:"connect_timeout,omitempty"`
	// Soft limit on size of the cluster’s connections read and write buffers. If
	// unspecified, an implementation defined default is applied (1MiB).
	PerConnectionBufferLimitBytes *google_protobuf.UInt32Value `protobuf:"bytes,5,opt,name=per_connection_buffer_limit_bytes,json=perConnectionBufferLimitBytes" json:"per_connection_buffer_limit_bytes,omitempty"`
	// The :ref:`load balancer type <arch_overview_load_balancing_types>` to use
	// when picking a host in the cluster.
	LbPolicy Cluster_LbPolicy `protobuf:"varint,6,opt,name=lb_policy,json=lbPolicy,enum=envoy.api.v2.Cluster_LbPolicy" json:"lb_policy,omitempty"`
	// If the service discovery type is
	// :ref:`STATIC<envoy_api_enum_value_Cluster.DiscoveryType.STATIC>`,
	// :ref:`STRICT_DNS<envoy_api_enum_value_Cluster.DiscoveryType.STRICT_DNS>`
	// or :ref:`LOGICAL_DNS<envoy_api_enum_value_Cluster.DiscoveryType.LOGICAL_DNS>`,
	// then hosts is required.
	Hosts []*envoy_api_v2_core.Address `protobuf:"bytes,7,rep,name=hosts" json:"hosts,omitempty"`
	// Optional :ref:`active health checking <arch_overview_health_checking>`
	// configuration for the cluster. If no
	// configuration is specified no health checking will be done and all cluster
	// members will be considered healthy at all times.
	HealthChecks []*envoy_api_v2_core4.HealthCheck `protobuf:"bytes,8,rep,name=health_checks,json=healthChecks" json:"health_checks,omitempty"`
	// Optional maximum requests for a single upstream connection. This parameter
	// is respected by both the HTTP/1.1 and HTTP/2 connection pool
	// implementations. If not specified, there is no limit. Setting this
	// parameter to 1 will effectively disable keep alive.
	MaxRequestsPerConnection *google_protobuf.UInt32Value `protobuf:"bytes,9,opt,name=max_requests_per_connection,json=maxRequestsPerConnection" json:"max_requests_per_connection,omitempty"`
	// Optional :ref:`circuit breaking <arch_overview_circuit_break>` for the cluster.
	CircuitBreakers *envoy_api_v2_cluster.CircuitBreakers `protobuf:"bytes,10,opt,name=circuit_breakers,json=circuitBreakers" json:"circuit_breakers,omitempty"`
	// The TLS configuration for connections to the upstream cluster. If no TLS
	// configuration is specified, TLS will not be used for new connections.
	//
	// .. attention::
	//
	//   Server certificate verification is not enabled by default. Configure
	//   :ref:`trusted_ca<envoy_api_field_auth.CertificateValidationContext.trusted_ca>` to enable
	//   verification.
	TlsContext *envoy_api_v2_auth.UpstreamTlsContext `protobuf:"bytes,11,opt,name=tls_context,json=tlsContext" json:"tls_context,omitempty"`
	// Additional options when handling HTTP1 requests.
	HttpProtocolOptions *envoy_api_v2_core5.Http1ProtocolOptions `protobuf:"bytes,13,opt,name=http_protocol_options,json=httpProtocolOptions" json:"http_protocol_options,omitempty"`
	// Even if default HTTP2 protocol options are desired, this field must be
	// set so that Envoy will assume that the upstream supports HTTP/2 when
	// making new HTTP connection pool connections. Currently, Envoy only
	// supports prior knowledge for upstream connections. Even if TLS is used
	// with ALPN, `http2_protocol_options` must be specified. As an aside this allows HTTP/2
	// connections to happen over plain text.
	Http2ProtocolOptions *envoy_api_v2_core5.Http2ProtocolOptions `protobuf:"bytes,14,opt,name=http2_protocol_options,json=http2ProtocolOptions" json:"http2_protocol_options,omitempty"`
	// If the DNS refresh rate is specified and the cluster type is either
	// :ref:`STRICT_DNS<envoy_api_enum_value_Cluster.DiscoveryType.STRICT_DNS>`,
	// or :ref:`LOGICAL_DNS<envoy_api_enum_value_Cluster.DiscoveryType.LOGICAL_DNS>`,
	// this value is used as the cluster’s DNS refresh
	// rate. If this setting is not specified, the value defaults to 5000. For
	// cluster types other than
	// :ref:`STRICT_DNS<envoy_api_enum_value_Cluster.DiscoveryType.STRICT_DNS>`
	// and :ref:`LOGICAL_DNS<envoy_api_enum_value_Cluster.DiscoveryType.LOGICAL_DNS>`
	// this setting is ignored.
	DnsRefreshRate *google_protobuf2.Duration `protobuf:"bytes,16,opt,name=dns_refresh_rate,json=dnsRefreshRate" json:"dns_refresh_rate,omitempty"`
	// The DNS IP address resolution policy. If this setting is not specified, the
	// value defaults to
	// :ref:`AUTO<envoy_api_enum_value_Cluster.DnsLookupFamily.AUTO>`.
	DnsLookupFamily Cluster_DnsLookupFamily `protobuf:"varint,17,opt,name=dns_lookup_family,json=dnsLookupFamily,enum=envoy.api.v2.Cluster_DnsLookupFamily" json:"dns_lookup_family,omitempty"`
	// If DNS resolvers are specified and the cluster type is either
	// :ref:`STRICT_DNS<envoy_api_enum_value_Cluster.DiscoveryType.STRICT_DNS>`,
	// or :ref:`LOGICAL_DNS<envoy_api_enum_value_Cluster.DiscoveryType.LOGICAL_DNS>`,
	// this value is used to specify the cluster’s dns resolvers.
	// If this setting is not specified, the value defaults to the default
	// resolver, which uses /etc/resolv.conf for configuration. For cluster types
	// other than
	// :ref:`STRICT_DNS<envoy_api_enum_value_Cluster.DiscoveryType.STRICT_DNS>`
	// and :ref:`LOGICAL_DNS<envoy_api_enum_value_Cluster.DiscoveryType.LOGICAL_DNS>`
	// this setting is ignored.
	DnsResolvers []*envoy_api_v2_core.Address `protobuf:"bytes,18,rep,name=dns_resolvers,json=dnsResolvers" json:"dns_resolvers,omitempty"`
	// If specified, outlier detection will be enabled for this upstream cluster.
	// Each of the configuration values can be overridden via
	// :ref:`runtime values <config_cluster_manager_cluster_runtime_outlier_detection>`.
	OutlierDetection *envoy_api_v2_cluster1.OutlierDetection `protobuf:"bytes,19,opt,name=outlier_detection,json=outlierDetection" json:"outlier_detection,omitempty"`
	// The interval for removing stale hosts from a cluster type
	// :ref:`ORIGINAL_DST<envoy_api_enum_value_Cluster.DiscoveryType.ORIGINAL_DST>`.
	// Hosts are considered stale if they have not been used
	// as upstream destinations during this interval. New hosts are added
	// to original destination clusters on demand as new connections are
	// redirected to Envoy, causing the number of hosts in the cluster to
	// grow over time. Hosts that are not stale (they are actively used as
	// destinations) are kept in the cluster, which allows connections to
	// them remain open, saving the latency that would otherwise be spent
	// on opening new connections. If this setting is not specified, the
	// value defaults to 5000ms. For cluster types other than
	// :ref:`ORIGINAL_DST<envoy_api_enum_value_Cluster.DiscoveryType.ORIGINAL_DST>`
	// this setting is ignored.
	CleanupInterval *google_protobuf2.Duration `protobuf:"bytes,20,opt,name=cleanup_interval,json=cleanupInterval" json:"cleanup_interval,omitempty"`
	// Optional configuration used to bind newly established upstream connections.
	// This overrides any bind_config specified in the bootstrap proto.
	// If the addres and port are empty, no bind will be performed.
	UpstreamBindConfig *envoy_api_v2_core.BindConfig `protobuf:"bytes,21,opt,name=upstream_bind_config,json=upstreamBindConfig" json:"upstream_bind_config,omitempty"`
	// Configuration for load balancing subsetting.
	LbSubsetConfig *Cluster_LbSubsetConfig `protobuf:"bytes,22,opt,name=lb_subset_config,json=lbSubsetConfig" json:"lb_subset_config,omitempty"`
	// Optional configuration for the load balancing algorithm selected by
	// LbPolicy. Currently only
	// :ref:`RING_HASH<envoy_api_enum_value_Cluster.LbPolicy.RING_HASH>`
	// has additional configuration options.
	// Specifying ring_hash_lb_config without setting the LbPolicy to
	// :ref:`RING_HASH<envoy_api_enum_value_Cluster.LbPolicy.RING_HASH>`
	// will generate an error at runtime.
	//
	// Types that are valid to be assigned to LbConfig:
	//	*Cluster_RingHashLbConfig_
	LbConfig isCluster_LbConfig `protobuf_oneof:"lb_config"`
	// Common configuration for all load balancer implementations.
	CommonLbConfig *Cluster_CommonLbConfig `protobuf:"bytes,27,opt,name=common_lb_config,json=commonLbConfig" json:"common_lb_config,omitempty"`
	// Optional custom transport socket implementation to use for upstream connections.
	TransportSocket *envoy_api_v2_core1.TransportSocket `protobuf:"bytes,24,opt,name=transport_socket,json=transportSocket" json:"transport_socket,omitempty"`
	// The Metadata field can be used to provide additional information about the
	// cluster. It can be used for stats, logging, and varying filter behavior.
	// Fields should use reverse DNS notation to denote which entity within Envoy
	// will need the information. For instance, if the metadata is intended for
	// the Router filter, the filter name should be specified as *envoy.router*.
	Metadata *envoy_api_v2_core1.Metadata `protobuf:"bytes,25,opt,name=metadata" json:"metadata,omitempty"`
	// Determines how Envoy selects the protocol used to speak to upstream hosts.
	ProtocolSelection Cluster_ClusterProtocolSelection `protobuf:"varint,26,opt,name=protocol_selection,json=protocolSelection,enum=envoy.api.v2.Cluster_ClusterProtocolSelection" json:"protocol_selection,omitempty"`
}

func (m *Cluster) Reset()                    { *m = Cluster{} }
func (m *Cluster) String() string            { return proto.CompactTextString(m) }
func (*Cluster) ProtoMessage()               {}
func (*Cluster) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isCluster_LbConfig interface {
	isCluster_LbConfig()
}

type Cluster_RingHashLbConfig_ struct {
	RingHashLbConfig *Cluster_RingHashLbConfig `protobuf:"bytes,23,opt,name=ring_hash_lb_config,json=ringHashLbConfig,oneof"`
}

func (*Cluster_RingHashLbConfig_) isCluster_LbConfig() {}

func (m *Cluster) GetLbConfig() isCluster_LbConfig {
	if m != nil {
		return m.LbConfig
	}
	return nil
}

func (m *Cluster) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Cluster) GetType() Cluster_DiscoveryType {
	if m != nil {
		return m.Type
	}
	return Cluster_STATIC
}

func (m *Cluster) GetEdsClusterConfig() *Cluster_EdsClusterConfig {
	if m != nil {
		return m.EdsClusterConfig
	}
	return nil
}

func (m *Cluster) GetConnectTimeout() *google_protobuf2.Duration {
	if m != nil {
		return m.ConnectTimeout
	}
	return nil
}

func (m *Cluster) GetPerConnectionBufferLimitBytes() *google_protobuf.UInt32Value {
	if m != nil {
		return m.PerConnectionBufferLimitBytes
	}
	return nil
}

func (m *Cluster) GetLbPolicy() Cluster_LbPolicy {
	if m != nil {
		return m.LbPolicy
	}
	return Cluster_ROUND_ROBIN
}

func (m *Cluster) GetHosts() []*envoy_api_v2_core.Address {
	if m != nil {
		return m.Hosts
	}
	return nil
}

func (m *Cluster) GetHealthChecks() []*envoy_api_v2_core4.HealthCheck {
	if m != nil {
		return m.HealthChecks
	}
	return nil
}

func (m *Cluster) GetMaxRequestsPerConnection() *google_protobuf.UInt32Value {
	if m != nil {
		return m.MaxRequestsPerConnection
	}
	return nil
}

func (m *Cluster) GetCircuitBreakers() *envoy_api_v2_cluster.CircuitBreakers {
	if m != nil {
		return m.CircuitBreakers
	}
	return nil
}

func (m *Cluster) GetTlsContext() *envoy_api_v2_auth.UpstreamTlsContext {
	if m != nil {
		return m.TlsContext
	}
	return nil
}

func (m *Cluster) GetHttpProtocolOptions() *envoy_api_v2_core5.Http1ProtocolOptions {
	if m != nil {
		return m.HttpProtocolOptions
	}
	return nil
}

func (m *Cluster) GetHttp2ProtocolOptions() *envoy_api_v2_core5.Http2ProtocolOptions {
	if m != nil {
		return m.Http2ProtocolOptions
	}
	return nil
}

func (m *Cluster) GetDnsRefreshRate() *google_protobuf2.Duration {
	if m != nil {
		return m.DnsRefreshRate
	}
	return nil
}

func (m *Cluster) GetDnsLookupFamily() Cluster_DnsLookupFamily {
	if m != nil {
		return m.DnsLookupFamily
	}
	return Cluster_AUTO
}

func (m *Cluster) GetDnsResolvers() []*envoy_api_v2_core.Address {
	if m != nil {
		return m.DnsResolvers
	}
	return nil
}

func (m *Cluster) GetOutlierDetection() *envoy_api_v2_cluster1.OutlierDetection {
	if m != nil {
		return m.OutlierDetection
	}
	return nil
}

func (m *Cluster) GetCleanupInterval() *google_protobuf2.Duration {
	if m != nil {
		return m.CleanupInterval
	}
	return nil
}

func (m *Cluster) GetUpstreamBindConfig() *envoy_api_v2_core.BindConfig {
	if m != nil {
		return m.UpstreamBindConfig
	}
	return nil
}

func (m *Cluster) GetLbSubsetConfig() *Cluster_LbSubsetConfig {
	if m != nil {
		return m.LbSubsetConfig
	}
	return nil
}

func (m *Cluster) GetRingHashLbConfig() *Cluster_RingHashLbConfig {
	if x, ok := m.GetLbConfig().(*Cluster_RingHashLbConfig_); ok {
		return x.RingHashLbConfig
	}
	return nil
}

func (m *Cluster) GetCommonLbConfig() *Cluster_CommonLbConfig {
	if m != nil {
		return m.CommonLbConfig
	}
	return nil
}

func (m *Cluster) GetTransportSocket() *envoy_api_v2_core1.TransportSocket {
	if m != nil {
		return m.TransportSocket
	}
	return nil
}

func (m *Cluster) GetMetadata() *envoy_api_v2_core1.Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Cluster) GetProtocolSelection() Cluster_ClusterProtocolSelection {
	if m != nil {
		return m.ProtocolSelection
	}
	return Cluster_USE_CONFIGURED_PROTOCOL
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Cluster) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Cluster_OneofMarshaler, _Cluster_OneofUnmarshaler, _Cluster_OneofSizer, []interface{}{
		(*Cluster_RingHashLbConfig_)(nil),
	}
}

func _Cluster_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Cluster)
	// lb_config
	switch x := m.LbConfig.(type) {
	case *Cluster_RingHashLbConfig_:
		b.EncodeVarint(23<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RingHashLbConfig); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Cluster.LbConfig has unexpected type %T", x)
	}
	return nil
}

func _Cluster_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Cluster)
	switch tag {
	case 23: // lb_config.ring_hash_lb_config
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Cluster_RingHashLbConfig)
		err := b.DecodeMessage(msg)
		m.LbConfig = &Cluster_RingHashLbConfig_{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Cluster_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Cluster)
	// lb_config
	switch x := m.LbConfig.(type) {
	case *Cluster_RingHashLbConfig_:
		s := proto.Size(x.RingHashLbConfig)
		n += proto.SizeVarint(23<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Only valid when discovery type is EDS.
type Cluster_EdsClusterConfig struct {
	// Configuration for the source of EDS updates for this Cluster.
	EdsConfig *envoy_api_v2_core3.ConfigSource `protobuf:"bytes,1,opt,name=eds_config,json=edsConfig" json:"eds_config,omitempty"`
	// Optional alternative to cluster name to present to EDS. This does not
	// have the same restrictions as cluster name, i.e. it may be arbitrary
	// length.
	ServiceName string `protobuf:"bytes,2,opt,name=service_name,json=serviceName" json:"service_name,omitempty"`
}

func (m *Cluster_EdsClusterConfig) Reset()                    { *m = Cluster_EdsClusterConfig{} }
func (m *Cluster_EdsClusterConfig) String() string            { return proto.CompactTextString(m) }
func (*Cluster_EdsClusterConfig) ProtoMessage()               {}
func (*Cluster_EdsClusterConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Cluster_EdsClusterConfig) GetEdsConfig() *envoy_api_v2_core3.ConfigSource {
	if m != nil {
		return m.EdsConfig
	}
	return nil
}

func (m *Cluster_EdsClusterConfig) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

// Optionally divide the endpoints in this cluster into subsets defined by
// endpoint metadata and selected by route and weighted cluster metadata.
type Cluster_LbSubsetConfig struct {
	// The behavior used when no endpoint subset matches the selected route's
	// metadata. The value defaults to
	// :ref:`NO_FALLBACK<envoy_api_enum_value_Cluster.LbSubsetConfig.LbSubsetFallbackPolicy.NO_FALLBACK>`.
	FallbackPolicy Cluster_LbSubsetConfig_LbSubsetFallbackPolicy `protobuf:"varint,1,opt,name=fallback_policy,json=fallbackPolicy,enum=envoy.api.v2.Cluster_LbSubsetConfig_LbSubsetFallbackPolicy" json:"fallback_policy,omitempty"`
	// Specifies the default subset of endpoints used during fallback if
	// fallback_policy is
	// :ref:`DEFAULT_SUBSET<envoy_api_enum_value_Cluster.LbSubsetConfig.LbSubsetFallbackPolicy.DEFAULT_SUBSET>`.
	// Each field in default_subset is
	// compared to the matching LbEndpoint.Metadata under the *envoy.lb*
	// namespace. It is valid for no hosts to match, in which case the behavior
	// is the same as a fallback_policy of
	// :ref:`NO_FALLBACK<envoy_api_enum_value_Cluster.LbSubsetConfig.LbSubsetFallbackPolicy.NO_FALLBACK>`.
	DefaultSubset *google_protobuf4.Struct `protobuf:"bytes,2,opt,name=default_subset,json=defaultSubset" json:"default_subset,omitempty"`
	// For each entry, LbEndpoint.Metadata's
	// *envoy.lb* namespace is traversed and a subset is created for each unique
	// combination of key and value. For example:
	//
	// .. code-block:: json
	//
	//   { "subset_selectors": [
	//       { "keys": [ "version" ] },
	//       { "keys": [ "stage", "hardware_type" ] }
	//   ]}
	//
	// A subset is matched when the metadata from the selected route and
	// weighted cluster contains the same keys and values as the subset's
	// metadata. The same host may appear in multiple subsets.
	SubsetSelectors []*Cluster_LbSubsetConfig_LbSubsetSelector `protobuf:"bytes,3,rep,name=subset_selectors,json=subsetSelectors" json:"subset_selectors,omitempty"`
}

func (m *Cluster_LbSubsetConfig) Reset()                    { *m = Cluster_LbSubsetConfig{} }
func (m *Cluster_LbSubsetConfig) String() string            { return proto.CompactTextString(m) }
func (*Cluster_LbSubsetConfig) ProtoMessage()               {}
func (*Cluster_LbSubsetConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func (m *Cluster_LbSubsetConfig) GetFallbackPolicy() Cluster_LbSubsetConfig_LbSubsetFallbackPolicy {
	if m != nil {
		return m.FallbackPolicy
	}
	return Cluster_LbSubsetConfig_NO_FALLBACK
}

func (m *Cluster_LbSubsetConfig) GetDefaultSubset() *google_protobuf4.Struct {
	if m != nil {
		return m.DefaultSubset
	}
	return nil
}

func (m *Cluster_LbSubsetConfig) GetSubsetSelectors() []*Cluster_LbSubsetConfig_LbSubsetSelector {
	if m != nil {
		return m.SubsetSelectors
	}
	return nil
}

// Specifications for subsets.
type Cluster_LbSubsetConfig_LbSubsetSelector struct {
	// List of keys to match with the weighted cluster metadata.
	Keys []string `protobuf:"bytes,1,rep,name=keys" json:"keys,omitempty"`
}

func (m *Cluster_LbSubsetConfig_LbSubsetSelector) Reset() {
	*m = Cluster_LbSubsetConfig_LbSubsetSelector{}
}
func (m *Cluster_LbSubsetConfig_LbSubsetSelector) String() string { return proto.CompactTextString(m) }
func (*Cluster_LbSubsetConfig_LbSubsetSelector) ProtoMessage()    {}
func (*Cluster_LbSubsetConfig_LbSubsetSelector) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 1, 0}
}

func (m *Cluster_LbSubsetConfig_LbSubsetSelector) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

// Specific configuration for the :ref:`RingHash<arch_overview_load_balancing_types_ring_hash>`
// load balancing policy.
type Cluster_RingHashLbConfig struct {
	// Minimum hash ring size, i.e. total virtual nodes. A larger size
	// will provide better request distribution since each host in the
	// cluster will have more virtual nodes. Defaults to 1024. In the case
	// that total number of hosts is greater than the minimum, each host will
	// be allocated a single virtual node.
	MinimumRingSize *google_protobuf.UInt64Value `protobuf:"bytes,1,opt,name=minimum_ring_size,json=minimumRingSize" json:"minimum_ring_size,omitempty"`
	// Deprecated settings from v1 config.
	DeprecatedV1 *Cluster_RingHashLbConfig_DeprecatedV1 `protobuf:"bytes,2,opt,name=deprecated_v1,json=deprecatedV1" json:"deprecated_v1,omitempty"`
}

func (m *Cluster_RingHashLbConfig) Reset()                    { *m = Cluster_RingHashLbConfig{} }
func (m *Cluster_RingHashLbConfig) String() string            { return proto.CompactTextString(m) }
func (*Cluster_RingHashLbConfig) ProtoMessage()               {}
func (*Cluster_RingHashLbConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 2} }

func (m *Cluster_RingHashLbConfig) GetMinimumRingSize() *google_protobuf.UInt64Value {
	if m != nil {
		return m.MinimumRingSize
	}
	return nil
}

func (m *Cluster_RingHashLbConfig) GetDeprecatedV1() *Cluster_RingHashLbConfig_DeprecatedV1 {
	if m != nil {
		return m.DeprecatedV1
	}
	return nil
}

type Cluster_RingHashLbConfig_DeprecatedV1 struct {
	// Defaults to true, meaning that std::hash is used to hash hosts onto
	// the ketama ring. std::hash can vary by platform. For this reason,
	// Envoy will eventually use `xxHash <https://github.com/Cyan4973/xxHash>`_
	// by default. This field exists for
	// migration purposes and will eventually be deprecated. Set it to false
	// to use `xxHash <https://github.com/Cyan4973/xxHash>`_ now.
	UseStdHash *google_protobuf.BoolValue `protobuf:"bytes,1,opt,name=use_std_hash,json=useStdHash" json:"use_std_hash,omitempty"`
}

func (m *Cluster_RingHashLbConfig_DeprecatedV1) Reset()         { *m = Cluster_RingHashLbConfig_DeprecatedV1{} }
func (m *Cluster_RingHashLbConfig_DeprecatedV1) String() string { return proto.CompactTextString(m) }
func (*Cluster_RingHashLbConfig_DeprecatedV1) ProtoMessage()    {}
func (*Cluster_RingHashLbConfig_DeprecatedV1) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 2, 0}
}

func (m *Cluster_RingHashLbConfig_DeprecatedV1) GetUseStdHash() *google_protobuf.BoolValue {
	if m != nil {
		return m.UseStdHash
	}
	return nil
}

// Common configuration for all load balancer implementations.
type Cluster_CommonLbConfig struct {
	// Configures the :ref:`healthy panic threshold <arch_overview_load_balancing_panic_threshold>`.
	// If not specified, the default is 50%.
	HealthyPanicThreshold *envoy_api_v2_core1.Percent `protobuf:"bytes,1,opt,name=healthy_panic_threshold,json=healthyPanicThreshold" json:"healthy_panic_threshold,omitempty"`
}

func (m *Cluster_CommonLbConfig) Reset()                    { *m = Cluster_CommonLbConfig{} }
func (m *Cluster_CommonLbConfig) String() string            { return proto.CompactTextString(m) }
func (*Cluster_CommonLbConfig) ProtoMessage()               {}
func (*Cluster_CommonLbConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 3} }

func (m *Cluster_CommonLbConfig) GetHealthyPanicThreshold() *envoy_api_v2_core1.Percent {
	if m != nil {
		return m.HealthyPanicThreshold
	}
	return nil
}

// An extensible structure containing the address Envoy should bind to when
// establishing upstream connections.
type UpstreamBindConfig struct {
	// The address Envoy should bind to when establishing upstream connections.
	SourceAddress *envoy_api_v2_core.Address `protobuf:"bytes,1,opt,name=source_address,json=sourceAddress" json:"source_address,omitempty"`
}

func (m *UpstreamBindConfig) Reset()                    { *m = UpstreamBindConfig{} }
func (m *UpstreamBindConfig) String() string            { return proto.CompactTextString(m) }
func (*UpstreamBindConfig) ProtoMessage()               {}
func (*UpstreamBindConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UpstreamBindConfig) GetSourceAddress() *envoy_api_v2_core.Address {
	if m != nil {
		return m.SourceAddress
	}
	return nil
}

func init() {
	proto.RegisterType((*Cluster)(nil), "envoy.api.v2.Cluster")
	proto.RegisterType((*Cluster_EdsClusterConfig)(nil), "envoy.api.v2.Cluster.EdsClusterConfig")
	proto.RegisterType((*Cluster_LbSubsetConfig)(nil), "envoy.api.v2.Cluster.LbSubsetConfig")
	proto.RegisterType((*Cluster_LbSubsetConfig_LbSubsetSelector)(nil), "envoy.api.v2.Cluster.LbSubsetConfig.LbSubsetSelector")
	proto.RegisterType((*Cluster_RingHashLbConfig)(nil), "envoy.api.v2.Cluster.RingHashLbConfig")
	proto.RegisterType((*Cluster_RingHashLbConfig_DeprecatedV1)(nil), "envoy.api.v2.Cluster.RingHashLbConfig.DeprecatedV1")
	proto.RegisterType((*Cluster_CommonLbConfig)(nil), "envoy.api.v2.Cluster.CommonLbConfig")
	proto.RegisterType((*UpstreamBindConfig)(nil), "envoy.api.v2.UpstreamBindConfig")
	proto.RegisterEnum("envoy.api.v2.Cluster_DiscoveryType", Cluster_DiscoveryType_name, Cluster_DiscoveryType_value)
	proto.RegisterEnum("envoy.api.v2.Cluster_LbPolicy", Cluster_LbPolicy_name, Cluster_LbPolicy_value)
	proto.RegisterEnum("envoy.api.v2.Cluster_DnsLookupFamily", Cluster_DnsLookupFamily_name, Cluster_DnsLookupFamily_value)
	proto.RegisterEnum("envoy.api.v2.Cluster_ClusterProtocolSelection", Cluster_ClusterProtocolSelection_name, Cluster_ClusterProtocolSelection_value)
	proto.RegisterEnum("envoy.api.v2.Cluster_LbSubsetConfig_LbSubsetFallbackPolicy", Cluster_LbSubsetConfig_LbSubsetFallbackPolicy_name, Cluster_LbSubsetConfig_LbSubsetFallbackPolicy_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ClusterDiscoveryService service

type ClusterDiscoveryServiceClient interface {
	StreamClusters(ctx context.Context, opts ...grpc.CallOption) (ClusterDiscoveryService_StreamClustersClient, error)
	FetchClusters(ctx context.Context, in *DiscoveryRequest, opts ...grpc.CallOption) (*DiscoveryResponse, error)
}

type clusterDiscoveryServiceClient struct {
	cc *grpc.ClientConn
}

func NewClusterDiscoveryServiceClient(cc *grpc.ClientConn) ClusterDiscoveryServiceClient {
	return &clusterDiscoveryServiceClient{cc}
}

func (c *clusterDiscoveryServiceClient) StreamClusters(ctx context.Context, opts ...grpc.CallOption) (ClusterDiscoveryService_StreamClustersClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ClusterDiscoveryService_serviceDesc.Streams[0], c.cc, "/envoy.api.v2.ClusterDiscoveryService/StreamClusters", opts...)
	if err != nil {
		return nil, err
	}
	x := &clusterDiscoveryServiceStreamClustersClient{stream}
	return x, nil
}

type ClusterDiscoveryService_StreamClustersClient interface {
	Send(*DiscoveryRequest) error
	Recv() (*DiscoveryResponse, error)
	grpc.ClientStream
}

type clusterDiscoveryServiceStreamClustersClient struct {
	grpc.ClientStream
}

func (x *clusterDiscoveryServiceStreamClustersClient) Send(m *DiscoveryRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *clusterDiscoveryServiceStreamClustersClient) Recv() (*DiscoveryResponse, error) {
	m := new(DiscoveryResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *clusterDiscoveryServiceClient) FetchClusters(ctx context.Context, in *DiscoveryRequest, opts ...grpc.CallOption) (*DiscoveryResponse, error) {
	out := new(DiscoveryResponse)
	err := grpc.Invoke(ctx, "/envoy.api.v2.ClusterDiscoveryService/FetchClusters", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ClusterDiscoveryService service

type ClusterDiscoveryServiceServer interface {
	StreamClusters(ClusterDiscoveryService_StreamClustersServer) error
	FetchClusters(context.Context, *DiscoveryRequest) (*DiscoveryResponse, error)
}

func RegisterClusterDiscoveryServiceServer(s *grpc.Server, srv ClusterDiscoveryServiceServer) {
	s.RegisterService(&_ClusterDiscoveryService_serviceDesc, srv)
}

func _ClusterDiscoveryService_StreamClusters_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClusterDiscoveryServiceServer).StreamClusters(&clusterDiscoveryServiceStreamClustersServer{stream})
}

type ClusterDiscoveryService_StreamClustersServer interface {
	Send(*DiscoveryResponse) error
	Recv() (*DiscoveryRequest, error)
	grpc.ServerStream
}

type clusterDiscoveryServiceStreamClustersServer struct {
	grpc.ServerStream
}

func (x *clusterDiscoveryServiceStreamClustersServer) Send(m *DiscoveryResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *clusterDiscoveryServiceStreamClustersServer) Recv() (*DiscoveryRequest, error) {
	m := new(DiscoveryRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ClusterDiscoveryService_FetchClusters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterDiscoveryServiceServer).FetchClusters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/envoy.api.v2.ClusterDiscoveryService/FetchClusters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterDiscoveryServiceServer).FetchClusters(ctx, req.(*DiscoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClusterDiscoveryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "envoy.api.v2.ClusterDiscoveryService",
	HandlerType: (*ClusterDiscoveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchClusters",
			Handler:    _ClusterDiscoveryService_FetchClusters_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamClusters",
			Handler:       _ClusterDiscoveryService_StreamClusters_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "envoy/api/v2/cds.proto",
}

func init() { proto.RegisterFile("envoy/api/v2/cds.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1730 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x4f, 0x6f, 0xdb, 0xc8,
	0x15, 0x37, 0x65, 0x25, 0xb1, 0x9f, 0x2d, 0x89, 0x9e, 0x24, 0x36, 0x23, 0x6f, 0x62, 0x47, 0xdd,
	0x6c, 0x8d, 0xa0, 0x90, 0x37, 0xca, 0xee, 0x16, 0xd8, 0x16, 0x5b, 0xe8, 0x9f, 0x6d, 0x6d, 0x15,
	0xd1, 0x1d, 0x52, 0x31, 0x16, 0xdb, 0x74, 0x4a, 0x91, 0x23, 0x8b, 0x30, 0x45, 0xb2, 0x9c, 0xa1,
	0x1b, 0xef, 0x71, 0x4f, 0xbd, 0xf7, 0xd2, 0x4b, 0xef, 0x45, 0x0f, 0xfd, 0x00, 0x3d, 0xf5, 0xd8,
	0x7b, 0xef, 0x2d, 0x50, 0x14, 0x28, 0xfa, 0x2d, 0x0a, 0x0e, 0x87, 0x8a, 0x25, 0xd1, 0xd9, 0x04,
	0xd8, 0x93, 0x66, 0xde, 0xfb, 0xbd, 0x1f, 0xdf, 0xbc, 0x79, 0xef, 0xcd, 0x13, 0x6c, 0x53, 0xff,
	0x32, 0xb8, 0x3a, 0xb4, 0x42, 0xf7, 0xf0, 0xb2, 0x71, 0x68, 0x3b, 0xac, 0x1e, 0x46, 0x01, 0x0f,
	0xd0, 0xa6, 0x90, 0xd7, 0xad, 0xd0, 0xad, 0x5f, 0x36, 0xaa, 0x7b, 0xf3, 0xa8, 0x20, 0xa2, 0x87,
	0x96, 0xe3, 0x44, 0x94, 0x49, 0x78, 0xf5, 0x83, 0x39, 0x80, 0x15, 0xf3, 0xc9, 0xa1, 0x4d, 0x23,
	0x9e, 0xab, 0x15, 0xe6, 0x23, 0x8b, 0x51, 0xa9, 0x7d, 0xb2, 0xac, 0xb5, 0x03, 0x7f, 0xec, 0x9e,
	0x13, 0x16, 0xc4, 0x91, 0x4d, 0x73, 0x49, 0x1c, 0x97, 0xd9, 0xc1, 0x25, 0x8d, 0xae, 0xa4, 0xf6,
	0xc3, 0x65, 0x92, 0x09, 0xb5, 0x3c, 0x3e, 0x21, 0xf6, 0x84, 0xda, 0x17, 0x12, 0xb5, 0xbf, 0x8c,
	0x12, 0x0a, 0x3b, 0xf0, 0x24, 0xe2, 0xe9, 0x3c, 0xc2, 0x8b, 0x19, 0xa7, 0xd1, 0xa1, 0xed, 0x46,
	0x76, 0xec, 0x72, 0x32, 0x8a, 0xa8, 0x75, 0x41, 0x23, 0x89, 0xfd, 0x51, 0x2e, 0x36, 0x88, 0xb9,
	0xe7, 0xd2, 0x88, 0x38, 0x94, 0x53, 0x9b, 0xbb, 0x81, 0x9f, 0xf9, 0x7f, 0x1e, 0x04, 0xe7, 0x1e,
	0x15, 0x70, 0xcb, 0xf7, 0x03, 0x6e, 0x25, 0xca, 0x2c, 0x80, 0x8f, 0xa4, 0x56, 0xec, 0x46, 0xf1,
	0xf8, 0xd0, 0x89, 0x23, 0x2b, 0xc7, 0x7a, 0xa6, 0x67, 0x3c, 0x8a, 0x6d, 0x7e, 0x93, 0xf5, 0x6f,
	0x23, 0x2b, 0x0c, 0x69, 0x94, 0xb1, 0xef, 0x5c, 0x5a, 0x9e, 0xeb, 0x58, 0x9c, 0x1e, 0x66, 0x0b,
	0xa9, 0xb8, 0x77, 0x1e, 0x9c, 0x07, 0x62, 0x79, 0x98, 0xac, 0x52, 0x69, 0xed, 0x2f, 0x0f, 0xe0,
	0x4e, 0x3b, 0x3d, 0x0e, 0x7a, 0x08, 0x45, 0xdf, 0x9a, 0x52, 0x4d, 0xd9, 0x57, 0x0e, 0xd6, 0x5b,
	0xeb, 0x7f, 0xfd, 0xdf, 0xdf, 0x56, 0x8b, 0x51, 0x61, 0x5f, 0xc1, 0x42, 0x8c, 0xda, 0x50, 0xe4,
	0x57, 0x21, 0xd5, 0x0a, 0xfb, 0xca, 0x41, 0xb9, 0xf1, 0x83, 0xfa, 0xf5, 0xb4, 0xa9, 0x4b, 0x8e,
	0x7a, 0x27, 0xbb, 0x2c, 0xf3, 0x2a, 0xa4, 0x2d, 0x48, 0x38, 0x6e, 0x7d, 0xab, 0x14, 0x54, 0x05,
	0x0b, 0x63, 0x64, 0x02, 0xa2, 0x0e, 0x23, 0x32, 0x82, 0x24, 0xbd, 0x7d, 0x6d, 0x75, 0x5f, 0x39,
	0xd8, 0x68, 0x7c, 0x94, 0x4f, 0xd9, 0x75, 0x98, 0x5c, 0xb6, 0x05, 0x1a, 0xab, 0x74, 0x41, 0x82,
	0x5e, 0x42, 0xc5, 0x0e, 0x7c, 0x9f, 0xda, 0x9c, 0x70, 0x77, 0x4a, 0x83, 0x98, 0x6b, 0x45, 0x41,
	0xf9, 0xa0, 0x9e, 0x86, 0xab, 0x9e, 0x85, 0xab, 0xde, 0x91, 0xc1, 0x6e, 0xa1, 0xbf, 0xff, 0x73,
	0x6f, 0xe5, 0x0f, 0xff, 0xda, 0x53, 0x84, 0x8f, 0x7f, 0x56, 0x0a, 0x4f, 0x57, 0x70, 0x59, 0xb2,
	0x98, 0x29, 0x09, 0x1a, 0xc3, 0xe3, 0x30, 0xf5, 0xd2, 0x4f, 0x2f, 0x98, 0x8c, 0xe2, 0xf1, 0x98,
	0x46, 0xc4, 0x73, 0xa7, 0x49, 0x8e, 0x5c, 0x71, 0xca, 0xb4, 0x5b, 0xe2, 0x4b, 0x1f, 0x2c, 0x7d,
	0x69, 0xd8, 0xf3, 0xf9, 0xf3, 0xc6, 0x4b, 0xcb, 0x8b, 0x29, 0x7e, 0x18, 0x0a, 0x5f, 0x25, 0x4b,
	0x4b, 0x90, 0xf4, 0x13, 0x8e, 0x56, 0x42, 0x81, 0x8e, 0x61, 0xdd, 0x1b, 0x91, 0x30, 0xf0, 0x5c,
	0xfb, 0x4a, 0xbb, 0x2d, 0xe2, 0xfb, 0x28, 0x3f, 0x18, 0xfd, 0xd1, 0xa9, 0x40, 0xcd, 0x85, 0x76,
	0xcd, 0x93, 0x52, 0xf4, 0x31, 0xdc, 0x9a, 0x04, 0x8c, 0x33, 0xed, 0xce, 0xfe, 0xea, 0xc1, 0x46,
	0xa3, 0x3a, 0x4f, 0x92, 0x54, 0x41, 0xbd, 0x99, 0x56, 0x33, 0x4e, 0x81, 0xa8, 0x0d, 0xa5, 0xeb,
	0xd5, 0xc3, 0xb4, 0x35, 0x61, 0xf9, 0x28, 0xc7, 0xf2, 0x44, 0xe0, 0xda, 0x09, 0x0c, 0x6f, 0x4e,
	0xde, 0x6c, 0x18, 0xfa, 0x1a, 0x76, 0xa7, 0xd6, 0x6b, 0x12, 0xd1, 0xdf, 0xc4, 0x94, 0x71, 0x46,
	0xe6, 0x83, 0xa6, 0xad, 0xbf, 0x43, 0x84, 0xb4, 0xa9, 0xf5, 0x1a, 0x4b, 0xfb, 0xd3, 0xeb, 0xc1,
	0x42, 0xa7, 0xa0, 0x2e, 0x14, 0x25, 0xd3, 0x40, 0x30, 0x3e, 0x59, 0x70, 0x52, 0xc6, 0xa8, 0x9d,
	0xa2, 0x5b, 0x12, 0x8c, 0x2b, 0xf6, 0xbc, 0x00, 0x1d, 0xc1, 0x06, 0xf7, 0x58, 0xe2, 0x21, 0xa7,
	0xaf, 0xb9, 0xb6, 0x91, 0x47, 0x96, 0x34, 0xb6, 0xfa, 0x30, 0x64, 0x3c, 0xa2, 0xd6, 0xd4, 0xf4,
	0x58, 0x3b, 0x05, 0x63, 0xe0, 0xb3, 0x35, 0xfa, 0x1a, 0xee, 0x4f, 0x38, 0x0f, 0x49, 0xd6, 0x58,
	0x48, 0x10, 0x8a, 0x42, 0xd7, 0x4a, 0x82, 0xf1, 0x87, 0x79, 0x31, 0xe4, 0x3c, 0x7c, 0x76, 0x2a,
	0xf1, 0x7a, 0x0a, 0xc7, 0x77, 0x13, 0x96, 0x05, 0x21, 0x7a, 0x05, 0xdb, 0x89, 0xb8, 0xb1, 0xcc,
	0x5e, 0x7e, 0x2b, 0x7b, 0x63, 0x91, 0xfd, 0xde, 0x24, 0x47, 0x8a, 0x0c, 0x50, 0x1d, 0x9f, 0x91,
	0x88, 0x8e, 0x23, 0xca, 0x26, 0x24, 0xb2, 0x38, 0xd5, 0xd4, 0xef, 0xaa, 0x99, 0xf2, 0x62, 0xbd,
	0x38, 0x3e, 0xc3, 0x29, 0x03, 0xb6, 0x38, 0x45, 0xaf, 0x60, 0x2b, 0x21, 0xf5, 0x82, 0xe0, 0x22,
	0x0e, 0xc9, 0xd8, 0x9a, 0xba, 0xde, 0x95, 0xb6, 0x25, 0xf2, 0xf9, 0xc9, 0x0d, 0xfd, 0xc2, 0x67,
	0x7d, 0x81, 0x3e, 0x12, 0xe0, 0xb9, 0xb4, 0xae, 0x38, 0xf3, 0x4a, 0xf4, 0x33, 0x28, 0xa5, 0x3e,
	0xb3, 0xc0, 0xbb, 0x4c, 0xd2, 0x00, 0x7d, 0x67, 0x96, 0x6f, 0x0a, 0x0f, 0x25, 0x1e, 0x19, 0xb0,
	0xb5, 0xd4, 0xb3, 0xb5, 0xbb, 0x79, 0xcd, 0x27, 0xcb, 0x25, 0x3d, 0x85, 0x77, 0x32, 0x34, 0x56,
	0x83, 0x05, 0x09, 0x32, 0x41, 0xb5, 0x3d, 0x6a, 0xf9, 0x71, 0x48, 0x5c, 0x9f, 0xd3, 0xe8, 0xd2,
	0xf2, 0xb4, 0x7b, 0xef, 0x1b, 0xc9, 0x8a, 0xa4, 0xe8, 0x49, 0x06, 0xa4, 0xc3, 0xbd, 0x58, 0x66,
	0x1f, 0x19, 0xb9, 0xbe, 0x93, 0xb5, 0xca, 0xfb, 0x82, 0xf9, 0x61, 0xce, 0x91, 0x5b, 0xae, 0xef,
	0xc8, 0x0e, 0x89, 0x32, 0xd3, 0x37, 0x32, 0x34, 0x00, 0xd5, 0x1b, 0x11, 0x16, 0x8f, 0x18, 0xe5,
	0x19, 0xd9, 0xb6, 0x20, 0xfb, 0xf0, 0xa6, 0x56, 0x63, 0x08, 0xb0, 0xe4, 0x2c, 0x7b, 0x73, 0x7b,
	0x74, 0x06, 0x77, 0x23, 0xd7, 0x3f, 0x27, 0x13, 0x8b, 0x4d, 0x88, 0x37, 0xca, 0x28, 0x77, 0xde,
	0xd6, 0xca, 0xb1, 0xeb, 0x9f, 0x9f, 0x58, 0x6c, 0xd2, 0x1f, 0xa5, 0x24, 0x27, 0x2b, 0x58, 0x8d,
	0x16, 0x64, 0x89, 0xa3, 0x76, 0x30, 0x9d, 0x06, 0xfe, 0x35, 0xd6, 0xdd, 0xb7, 0x39, 0xda, 0x16,
	0xe8, 0xcc, 0x3e, 0x69, 0xe2, 0xd7, 0xf7, 0xe8, 0x05, 0xa8, 0x3c, 0xb2, 0x7c, 0x16, 0x06, 0x11,
	0x27, 0x2c, 0xb0, 0x2f, 0x28, 0xd7, 0x34, 0xc1, 0x57, 0xcb, 0x89, 0xa2, 0x99, 0x41, 0x0d, 0x81,
	0xc4, 0x15, 0x3e, 0x2f, 0x40, 0x3f, 0x86, 0xb5, 0x29, 0xe5, 0x96, 0x63, 0x71, 0x4b, 0x7b, 0x20,
	0x68, 0x76, 0x73, 0x68, 0x5e, 0x48, 0x08, 0x9e, 0x81, 0xd1, 0x2b, 0x40, 0xb3, 0x52, 0x66, 0xd4,
	0x93, 0xd9, 0x57, 0x15, 0xd5, 0x51, 0xbf, 0xe1, 0x64, 0xe9, 0x6f, 0x56, 0xbb, 0x46, 0x66, 0x85,
	0xb7, 0xc2, 0x45, 0x51, 0x35, 0x06, 0x75, 0xf1, 0xa5, 0x44, 0x5f, 0x00, 0x88, 0xd7, 0x36, 0x0d,
	0xa2, 0x22, 0xbc, 0xdd, 0xcb, 0xf1, 0x36, 0x85, 0x1b, 0x62, 0x06, 0xc3, 0xeb, 0xc9, 0xf3, 0x9a,
	0xda, 0x3f, 0x86, 0x4d, 0x46, 0xa3, 0x4b, 0xd7, 0xa6, 0x44, 0x4c, 0x06, 0xc9, 0xd3, 0xbf, 0x8e,
	0x37, 0xa4, 0x6c, 0x60, 0x4d, 0x69, 0xf5, 0x8f, 0xab, 0x50, 0x9e, 0xcf, 0x14, 0x14, 0x42, 0x65,
	0x6c, 0x79, 0xde, 0xc8, 0xb2, 0x2f, 0xb2, 0x37, 0x4d, 0x11, 0xa7, 0xfc, 0xc9, 0xbb, 0x24, 0xda,
	0x6c, 0x7b, 0x24, 0x39, 0x72, 0x1e, 0xbc, 0xf2, 0x78, 0x4e, 0x87, 0xbe, 0x80, 0xb2, 0x43, 0xc7,
	0x56, 0xec, 0x71, 0x99, 0xe0, 0xc2, 0xd3, 0x8d, 0xc6, 0xce, 0x52, 0x01, 0x1a, 0x62, 0x96, 0xc2,
	0x25, 0x09, 0x4f, 0xbf, 0x84, 0x7e, 0x0d, 0xaa, 0x2c, 0x8c, 0xf4, 0x62, 0x82, 0x88, 0x69, 0xab,
	0xa2, 0xb7, 0x7c, 0xfa, 0x5e, 0x2e, 0x1b, 0xd2, 0x1a, 0x57, 0xd8, 0xdc, 0x9e, 0x55, 0x3f, 0x02,
	0x75, 0x11, 0x84, 0x10, 0x14, 0x2f, 0xe8, 0x15, 0xd3, 0x94, 0xfd, 0xd5, 0x83, 0x75, 0x2c, 0xd6,
	0x35, 0x1d, 0xb6, 0xf3, 0xcf, 0x8f, 0x2a, 0xb0, 0x31, 0xd0, 0xc9, 0x51, 0xb3, 0xdf, 0x6f, 0x35,
	0xdb, 0x3f, 0x57, 0x57, 0x90, 0x0a, 0x9b, 0xcd, 0xc1, 0x57, 0xa4, 0x3b, 0xe8, 0x9c, 0xea, 0xbd,
	0x81, 0xa9, 0x2a, 0x08, 0x41, 0xb9, 0xd3, 0x3d, 0x6a, 0x0e, 0xfb, 0x26, 0x31, 0x86, 0x2d, 0xa3,
	0x6b, 0xaa, 0x85, 0xea, 0xef, 0x0a, 0xa0, 0x2e, 0x96, 0x1d, 0x3a, 0x81, 0xad, 0xa9, 0xeb, 0xbb,
	0xd3, 0x78, 0x4a, 0x44, 0x0d, 0x33, 0xf7, 0x1b, 0x2a, 0xd3, 0x23, 0xff, 0x95, 0xfe, 0xec, 0x93,
	0xf4, 0x95, 0xae, 0x48, 0xb3, 0x84, 0xd1, 0x70, 0xbf, 0xa1, 0xe8, 0x97, 0x50, 0x72, 0x68, 0x18,
	0x51, 0xdb, 0xe2, 0xd4, 0x21, 0x97, 0xcf, 0x64, 0xe0, 0x9f, 0xbf, 0x5b, 0xfd, 0xd7, 0x3b, 0x33,
	0xdb, 0x97, 0xcf, 0x5a, 0x05, 0x4d, 0xc1, 0x9b, 0xce, 0x35, 0x49, 0xb5, 0x0f, 0x9b, 0xd7, 0x11,
	0xe8, 0xa7, 0xb0, 0x19, 0x33, 0x4a, 0x18, 0x77, 0x44, 0xdb, 0x91, 0x2e, 0x57, 0x97, 0x5c, 0x6e,
	0x05, 0x81, 0x97, 0x3a, 0x0c, 0x31, 0xa3, 0x06, 0x77, 0x92, 0x8f, 0x56, 0x1d, 0x28, 0xcf, 0xb7,
	0x0a, 0x84, 0x61, 0x27, 0x9d, 0x63, 0xae, 0x48, 0x68, 0xf9, 0xae, 0x4d, 0xf8, 0x24, 0x79, 0xcb,
	0x02, 0xcf, 0x99, 0x51, 0x2f, 0x17, 0xcb, 0x29, 0x8d, 0x6c, 0xea, 0x73, 0x7c, 0x5f, 0x9a, 0x9e,
	0x26, 0x96, 0x66, 0x66, 0x58, 0x3b, 0x83, 0xd2, 0xdc, 0x10, 0x8c, 0x00, 0x6e, 0x1b, 0x66, 0xd3,
	0xec, 0xb5, 0xd5, 0x15, 0x54, 0x06, 0x30, 0x4c, 0xdc, 0x6b, 0x9b, 0xa4, 0x33, 0x30, 0x54, 0x25,
	0xb9, 0xd4, 0xbe, 0x7e, 0xdc, 0x6b, 0x37, 0xfb, 0x42, 0x50, 0x40, 0x77, 0x60, 0xb5, 0xdb, 0x31,
	0xd4, 0xd5, 0xe4, 0x76, 0x75, 0xdc, 0x3b, 0xee, 0x0d, 0x12, 0x95, 0x61, 0xaa, 0xc5, 0xda, 0xaf,
	0x60, 0x2d, 0x9b, 0xfe, 0x12, 0x3b, 0xac, 0x0f, 0x07, 0x1d, 0x82, 0xf5, 0x56, 0x6f, 0xa0, 0xae,
	0xa0, 0x2d, 0x28, 0xf5, 0xbb, 0x4d, 0xc3, 0x24, 0xb8, 0xfb, 0x8b, 0x61, 0xd7, 0x48, 0xb2, 0xa1,
	0x04, 0xeb, 0xb8, 0x37, 0x38, 0x26, 0x27, 0x4d, 0xe3, 0x44, 0x2d, 0x24, 0x6e, 0xe0, 0xe6, 0xa0,
	0xa3, 0xbf, 0x50, 0x57, 0xd1, 0x5d, 0xa8, 0x5c, 0x27, 0x27, 0xfd, 0x96, 0x5a, 0xac, 0x7d, 0x0a,
	0x95, 0x85, 0xd7, 0x18, 0xad, 0x41, 0xb1, 0x39, 0x34, 0x75, 0x75, 0x05, 0x6d, 0xc0, 0x9d, 0x97,
	0x9f, 0x10, 0x7d, 0xd0, 0xff, 0x4a, 0x55, 0xc4, 0xe6, 0xb3, 0x74, 0x53, 0xa8, 0x99, 0xa0, 0xdd,
	0xd4, 0xa6, 0xd0, 0x2e, 0xec, 0x0c, 0x8d, 0x2e, 0x69, 0xeb, 0x83, 0xa3, 0xde, 0xf1, 0x10, 0x77,
	0x3b, 0xe4, 0x14, 0xeb, 0xa6, 0xde, 0xd6, 0xfb, 0xea, 0x4a, 0xa6, 0xec, 0xe8, 0x67, 0x03, 0xc3,
	0xc4, 0xdd, 0xe6, 0x8b, 0x37, 0x4a, 0xa5, 0xb5, 0x21, 0x26, 0xe2, 0xb4, 0x71, 0x7d, 0x59, 0x5c,
	0xdb, 0x54, 0x4b, 0x5f, 0x16, 0xd7, 0x2a, 0xaa, 0x5a, 0x3b, 0x03, 0x34, 0x5c, 0x7e, 0xdc, 0x9a,
	0x50, 0x4e, 0xff, 0x41, 0x12, 0xf9, 0x67, 0xf5, 0x2d, 0xf7, 0x97, 0x8d, 0x06, 0xa5, 0xd4, 0x42,
	0x6e, 0x1b, 0xff, 0x55, 0x60, 0x47, 0x1e, 0x64, 0x76, 0x7f, 0x46, 0xda, 0xe8, 0xd0, 0x19, 0x94,
	0x0d, 0xf1, 0x49, 0x09, 0x60, 0x68, 0x61, 0x3e, 0x9e, 0x59, 0xc8, 0x11, 0xb6, 0xba, 0x77, 0xa3,
	0x9e, 0x85, 0x81, 0xcf, 0x68, 0x6d, 0xe5, 0x40, 0xf9, 0x58, 0x41, 0x0c, 0x4a, 0x47, 0x94, 0xdb,
	0x93, 0xef, 0x8f, 0xf7, 0xf1, 0xb7, 0xff, 0xf8, 0xcf, 0xef, 0x0b, 0xbb, 0xb5, 0xed, 0xb9, 0xbf,
	0xce, 0x9f, 0xcb, 0x79, 0x86, 0x7d, 0xae, 0x3c, 0x6d, 0x15, 0xff, 0xf4, 0xef, 0x47, 0xca, 0xe8,
	0xb6, 0xa8, 0x96, 0xe7, 0xff, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xd4, 0x68, 0x72, 0x14, 0x17, 0x10,
	0x00, 0x00,
}
