// Code generated by protoc-gen-go. DO NOT EDIT.
// source: envoy/config/filter/fault/v2/fault.proto

package v2

import (
	fmt "fmt"
	_type "github.com/cilium/cilium/pkg/envoy/envoy/type"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	_ "github.com/lyft/protoc-gen-validate/validate"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FaultDelay_FaultDelayType int32

const (
	// Fixed delay (step function).
	FaultDelay_FIXED FaultDelay_FaultDelayType = 0
)

var FaultDelay_FaultDelayType_name = map[int32]string{
	0: "FIXED",
}

var FaultDelay_FaultDelayType_value = map[string]int32{
	"FIXED": 0,
}

func (x FaultDelay_FaultDelayType) String() string {
	return proto.EnumName(FaultDelay_FaultDelayType_name, int32(x))
}

func (FaultDelay_FaultDelayType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d1b308afbc13f85b, []int{0, 0}
}

// Delay specification is used to inject latency into the
// HTTP/gRPC/Mongo/Redis operation or delay proxying of TCP connections.
type FaultDelay struct {
	// Delay type to use (fixed|exponential|..). Currently, only fixed delay (step function) is
	// supported.
	Type FaultDelay_FaultDelayType `protobuf:"varint,1,opt,name=type,proto3,enum=envoy.config.filter.fault.v2.FaultDelay_FaultDelayType" json:"type,omitempty"`
	// Types that are valid to be assigned to FaultDelaySecifier:
	//	*FaultDelay_FixedDelay
	FaultDelaySecifier isFaultDelay_FaultDelaySecifier `protobuf_oneof:"fault_delay_secifier"`
	// The percentage of operations/connection requests on which the delay will be injected.
	Percentage           *_type.FractionalPercent `protobuf:"bytes,4,opt,name=percentage,proto3" json:"percentage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *FaultDelay) Reset()         { *m = FaultDelay{} }
func (m *FaultDelay) String() string { return proto.CompactTextString(m) }
func (*FaultDelay) ProtoMessage()    {}
func (*FaultDelay) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1b308afbc13f85b, []int{0}
}

func (m *FaultDelay) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FaultDelay.Unmarshal(m, b)
}
func (m *FaultDelay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FaultDelay.Marshal(b, m, deterministic)
}
func (m *FaultDelay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FaultDelay.Merge(m, src)
}
func (m *FaultDelay) XXX_Size() int {
	return xxx_messageInfo_FaultDelay.Size(m)
}
func (m *FaultDelay) XXX_DiscardUnknown() {
	xxx_messageInfo_FaultDelay.DiscardUnknown(m)
}

var xxx_messageInfo_FaultDelay proto.InternalMessageInfo

func (m *FaultDelay) GetType() FaultDelay_FaultDelayType {
	if m != nil {
		return m.Type
	}
	return FaultDelay_FIXED
}

type isFaultDelay_FaultDelaySecifier interface {
	isFaultDelay_FaultDelaySecifier()
}

type FaultDelay_FixedDelay struct {
	FixedDelay *duration.Duration `protobuf:"bytes,3,opt,name=fixed_delay,json=fixedDelay,proto3,oneof"`
}

func (*FaultDelay_FixedDelay) isFaultDelay_FaultDelaySecifier() {}

func (m *FaultDelay) GetFaultDelaySecifier() isFaultDelay_FaultDelaySecifier {
	if m != nil {
		return m.FaultDelaySecifier
	}
	return nil
}

func (m *FaultDelay) GetFixedDelay() *duration.Duration {
	if x, ok := m.GetFaultDelaySecifier().(*FaultDelay_FixedDelay); ok {
		return x.FixedDelay
	}
	return nil
}

func (m *FaultDelay) GetPercentage() *_type.FractionalPercent {
	if m != nil {
		return m.Percentage
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*FaultDelay) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _FaultDelay_OneofMarshaler, _FaultDelay_OneofUnmarshaler, _FaultDelay_OneofSizer, []interface{}{
		(*FaultDelay_FixedDelay)(nil),
	}
}

func _FaultDelay_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*FaultDelay)
	// fault_delay_secifier
	switch x := m.FaultDelaySecifier.(type) {
	case *FaultDelay_FixedDelay:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.FixedDelay); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("FaultDelay.FaultDelaySecifier has unexpected type %T", x)
	}
	return nil
}

func _FaultDelay_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*FaultDelay)
	switch tag {
	case 3: // fault_delay_secifier.fixed_delay
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(duration.Duration)
		err := b.DecodeMessage(msg)
		m.FaultDelaySecifier = &FaultDelay_FixedDelay{msg}
		return true, err
	default:
		return false, nil
	}
}

func _FaultDelay_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*FaultDelay)
	// fault_delay_secifier
	switch x := m.FaultDelaySecifier.(type) {
	case *FaultDelay_FixedDelay:
		s := proto.Size(x.FixedDelay)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterEnum("envoy.config.filter.fault.v2.FaultDelay_FaultDelayType", FaultDelay_FaultDelayType_name, FaultDelay_FaultDelayType_value)
	proto.RegisterType((*FaultDelay)(nil), "envoy.config.filter.fault.v2.FaultDelay")
}

func init() {
	proto.RegisterFile("envoy/config/filter/fault/v2/fault.proto", fileDescriptor_d1b308afbc13f85b)
}

var fileDescriptor_d1b308afbc13f85b = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x50, 0xbf, 0x4a, 0xc3, 0x40,
	0x18, 0xef, 0x25, 0xa9, 0xe8, 0x57, 0x28, 0x25, 0x14, 0x8c, 0xd5, 0x6a, 0xe9, 0x54, 0x1c, 0xee,
	0x20, 0x0e, 0x4e, 0x2e, 0xa1, 0x16, 0x15, 0x07, 0x29, 0x82, 0xe2, 0x52, 0xae, 0xc9, 0x97, 0x70,
	0x10, 0x72, 0x21, 0x26, 0xc1, 0xac, 0x3e, 0x85, 0xcf, 0xe0, 0xec, 0x20, 0x4e, 0x7d, 0x13, 0xe7,
	0xbe, 0x85, 0xe4, 0x2e, 0xc5, 0xba, 0xb8, 0xfd, 0x92, 0xef, 0xf7, 0xf7, 0x60, 0x82, 0x49, 0x29,
	0x2b, 0xe6, 0xcb, 0x24, 0x14, 0x11, 0x0b, 0x45, 0x9c, 0x63, 0xc6, 0x42, 0x5e, 0xc4, 0x39, 0x2b,
	0x5d, 0x0d, 0x68, 0x9a, 0xc9, 0x5c, 0xda, 0x47, 0x8a, 0x49, 0x35, 0x93, 0x6a, 0x26, 0xd5, 0x84,
	0xd2, 0x1d, 0x38, 0xda, 0x27, 0xaf, 0x52, 0x64, 0x29, 0x66, 0x3e, 0x26, 0x8d, 0x6e, 0x70, 0x1c,
	0x49, 0x19, 0xc5, 0xc8, 0xd4, 0xd7, 0xb2, 0x08, 0x59, 0x50, 0x64, 0x3c, 0x17, 0x32, 0x69, 0xee,
	0xfb, 0x25, 0x8f, 0x45, 0xc0, 0x73, 0x64, 0x1b, 0xd0, 0x1c, 0xfa, 0x91, 0x8c, 0xa4, 0x82, 0xac,
	0x46, 0xfa, 0xef, 0xf8, 0xc3, 0x00, 0x98, 0xd5, 0xa9, 0x53, 0x8c, 0x79, 0x65, 0x3f, 0x80, 0x55,
	0x67, 0x3a, 0x64, 0x44, 0x26, 0x5d, 0xf7, 0x9c, 0xfe, 0x57, 0x92, 0xfe, 0xea, 0xb6, 0xe0, 0x7d,
	0x95, 0xa2, 0x07, 0x5f, 0xeb, 0x95, 0xd9, 0x7e, 0x25, 0x46, 0x8f, 0xcc, 0x95, 0xa1, 0x7d, 0x0b,
	0x9d, 0x50, 0xbc, 0x60, 0xb0, 0x08, 0x6a, 0x92, 0x63, 0x8e, 0xc8, 0xa4, 0xe3, 0x1e, 0x50, 0x3d,
	0x86, 0x6e, 0xc6, 0xd0, 0x69, 0x33, 0xc6, 0xeb, 0xbe, 0x7d, 0x9f, 0x10, 0xe5, 0xf2, 0x4e, 0x8c,
	0xd3, 0xd6, 0x55, 0x6b, 0x0e, 0x4a, 0xaf, 0x6b, 0x5e, 0x00, 0x34, 0xaf, 0xc2, 0x23, 0x74, 0x2c,
	0x65, 0x36, 0x6c, 0xca, 0xd6, 0x71, 0x74, 0x96, 0x71, 0xbf, 0xf6, 0xe1, 0xf1, 0x9d, 0xe6, 0xcd,
	0xb7, 0x04, 0xe3, 0x43, 0xe8, 0xfe, 0x2d, 0x6c, 0xef, 0x41, 0x7b, 0x76, 0xfd, 0x78, 0x39, 0xed,
	0xb5, 0xbc, 0x21, 0xf4, 0xd5, 0x42, 0xdd, 0x74, 0xf1, 0x8c, 0xbe, 0x08, 0x05, 0x66, 0x76, 0xfb,
	0x73, 0xbd, 0x32, 0xc9, 0x8d, 0xb5, 0x6b, 0xf4, 0x4c, 0xcf, 0x7a, 0x32, 0x4a, 0x77, 0xb9, 0xa3,
	0x7a, 0x9f, 0xfd, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x0c, 0xfc, 0x20, 0xf6, 0x01, 0x00, 0x00,
}
