{{- if and (or .Values.clustermesh.mcsapi.enabled .Values.clustermesh.enableMCSAPISupport) .Values.clustermesh.mcsapi.corednsAutoConfigure.enabled }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cilium-coredns-mcsapi-autoconfig
  {{- with .Values.commonLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    {{- with .Values.clustermesh.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
- apiGroups: [ "" ]
  resources: [ "namespaces" ]
  verbs: [ "get" ]
{{- end }}
