#!/bin/bash

set -xv

dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source "${dir}/helpers.bash"
# dir might have been overwritten by helpers.bash
dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

function copy_runtime_test_files {
  local VM=$(get_cilium_master_vm_name)
  local RUNTIME_TESTS_DIR="tests/${CILIUM_FILES}"
   
  sudo rm -rf ./cilium-files
  sudo rm -rf *.tar.gz

  copy_files_vm ${VM} ${RUNTIME_TESTS_DIR}

  sudo tar -czvf ${CILIUM_FILES}-runtime.tar.gz ${CILIUM_FILES}-*
}

copy_runtime_test_files
