#!/bin/bash

set -e

# Set path to contain Go binaries explicitly; see issue 566.
export PATH=$PATH:/usr/local/go/bin:/usr/local/clang/bin:/home/vagrant/go/bin:/home/vagrant/bin

for test in *.sh; do
	echo
	echo "Starting test $test"
	echo
	./$test
	echo
	echo "Finished test $test"
	echo
done
