#!/bin/bash

set -e

# This script must be launched with Jenkins only.
cd ${WORKSPACE}

echo "Destroying runtime test VM if it's already running"
vagrant destroy -f || echo "Nothing to destroy"

echo "Starting runtime test VM"
NO_PROVISION=1 ./contrib/vagrant/start.sh
