// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by informer-gen. DO NOT EDIT.

package v2alpha1

import (
	context "context"
	time "time"

	apisciliumiov2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	versioned "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned"
	internalinterfaces "github.com/cilium/cilium/pkg/k8s/client/informers/externalversions/internalinterfaces"
	ciliumiov2alpha1 "github.com/cilium/cilium/pkg/k8s/client/listers/cilium.io/v2alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CiliumResourceIPPoolInformer provides access to a shared informer and lister for
// CiliumResourceIPPools. Prefer using the type-safe variant (see [TypedCiliumResourceIPPoolInformer]).
type CiliumResourceIPPoolInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() ciliumiov2alpha1.CiliumResourceIPPoolLister
}

// TypedCiliumResourceIPPoolInformer provides access to a shared informer and lister for
// CiliumResourceIPPools, including the type-safe TypedInformer variant.
// It is a superset of CiliumResourceIPPoolInformer.
type TypedCiliumResourceIPPoolInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() CiliumResourceIPPoolIndexInformer
	Lister() ciliumiov2alpha1.CiliumResourceIPPoolLister
}

// CiliumResourceIPPoolIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type CiliumResourceIPPoolIndexInformer cache.TypedSharedIndexInformer[*apisciliumiov2alpha1.CiliumResourceIPPool]

// CiliumResourceIPPoolHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for CiliumResourceIPPool.
type CiliumResourceIPPoolHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apisciliumiov2alpha1.CiliumResourceIPPool]

// CiliumResourceIPPoolDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for CiliumResourceIPPool.
type CiliumResourceIPPoolDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apisciliumiov2alpha1.CiliumResourceIPPool]

// CiliumResourceIPPoolFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for CiliumResourceIPPool.
type CiliumResourceIPPoolFilteringHandler = cache.TypedFilteringResourceEventHandler[*apisciliumiov2alpha1.CiliumResourceIPPool]

// CiliumResourceIPPoolIndexers is a specialization of [cache.TypedIndexers] for CiliumResourceIPPool.
type CiliumResourceIPPoolIndexers = cache.TypedIndexers[*apisciliumiov2alpha1.CiliumResourceIPPool]

// DeletedCiliumResourceIPPool is a specialization of [cache.DeletedObject] for CiliumResourceIPPool.
type DeletedCiliumResourceIPPool = cache.DeletedObject[*apisciliumiov2alpha1.CiliumResourceIPPool]

type ciliumResourceIPPoolInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewCiliumResourceIPPoolInformer constructs a new informer for CiliumResourceIPPool type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedCiliumResourceIPPoolInformer]).
func NewCiliumResourceIPPoolInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewCiliumResourceIPPoolInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedCiliumResourceIPPoolInformer constructs a new informer for CiliumResourceIPPool type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedCiliumResourceIPPoolInformer(client versioned.Interface, resyncPeriod time.Duration, indexers CiliumResourceIPPoolIndexers) CiliumResourceIPPoolIndexInformer {
	return NewTypedCiliumResourceIPPoolInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredCiliumResourceIPPoolInformer constructs a new informer for CiliumResourceIPPool type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredCiliumResourceIPPoolInformer]).
func NewFilteredCiliumResourceIPPoolInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedCiliumResourceIPPoolInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredCiliumResourceIPPoolInformer constructs a new informer for CiliumResourceIPPool type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredCiliumResourceIPPoolInformer(client versioned.Interface, resyncPeriod time.Duration, indexers CiliumResourceIPPoolIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) CiliumResourceIPPoolIndexInformer {
	return NewTypedCiliumResourceIPPoolInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewCiliumResourceIPPoolInformerWithOptions constructs a new informer for CiliumResourceIPPool type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedCiliumResourceIPPoolInformerWithOptions]).
func NewCiliumResourceIPPoolInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedCiliumResourceIPPoolInformerWithOptions(client, options)
}

// NewTypedCiliumResourceIPPoolInformerWithOptions constructs a new informer for CiliumResourceIPPool type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedCiliumResourceIPPoolInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) CiliumResourceIPPoolIndexInformer {
	gvr := schema.GroupVersionResource{Group: "cilium.io", Version: "v2alpha1", Resource: "ciliumresourceippools"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apisciliumiov2alpha1.CiliumResourceIPPool](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CiliumV2alpha1().CiliumResourceIPPools().List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CiliumV2alpha1().CiliumResourceIPPools().Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CiliumV2alpha1().CiliumResourceIPPools().List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CiliumV2alpha1().CiliumResourceIPPools().Watch(ctx, opts)
			},
		}, client),
		&apisciliumiov2alpha1.CiliumResourceIPPool{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *ciliumResourceIPPoolInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedCiliumResourceIPPoolInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *ciliumResourceIPPoolInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *ciliumResourceIPPoolInformer) TypedInformer() CiliumResourceIPPoolIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apisciliumiov2alpha1.CiliumResourceIPPool](f.factory.InformerFor(&apisciliumiov2alpha1.CiliumResourceIPPool{}, f.defaultInformer))
}

func (f *ciliumResourceIPPoolInformer) Lister() ciliumiov2alpha1.CiliumResourceIPPoolLister {
	return ciliumiov2alpha1.NewCiliumResourceIPPoolLister(f.Informer().GetIndexer())
}

// ToTypedCiliumResourceIPPoolInformer converts an untyped informer into a TypedCiliumResourceIPPoolInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *CiliumResourceIPPool. If that is not the case, calling type-safe methods of the returned
// TypedCiliumResourceIPPoolInformer leads to runtime panics. A safer alternative is to pass
// around a TypedCiliumResourceIPPoolInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedCiliumResourceIPPoolInformer(informer CiliumResourceIPPoolInformer) TypedCiliumResourceIPPoolInformer {
	if informer, ok := informer.(TypedCiliumResourceIPPoolInformer); ok {
		return informer
	}
	return &ciliumResourceIPPoolTypedInformerAdapter{informer}
}

type ciliumResourceIPPoolTypedInformerAdapter struct {
	CiliumResourceIPPoolInformer
}

func (a *ciliumResourceIPPoolTypedInformerAdapter) TypedInformer() CiliumResourceIPPoolIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apisciliumiov2alpha1.CiliumResourceIPPool](a.Informer())
}

// ToCiliumResourceIPPoolIndexInformer converts an untyped informer into a CiliumResourceIPPoolIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *CiliumResourceIPPool. If that is not the case, calling type-safe methods of the returned
// CiliumResourceIPPoolIndexInformer leads to runtime panics. A safer alternative is to pass
// around a CiliumResourceIPPoolIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToCiliumResourceIPPoolIndexInformer(informer cache.SharedIndexInformer) CiliumResourceIPPoolIndexInformer {
	if informer, ok := informer.(CiliumResourceIPPoolIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apisciliumiov2alpha1.CiliumResourceIPPool](informer)
}
