// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetClusterHandlerFunc turns a function with the right signature into a get cluster handler
type GetClusterHandlerFunc func(GetClusterParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetClusterHandlerFunc) Handle(params GetClusterParams) middleware.Responder {
	return fn(params)
}

// GetClusterHandler interface for that can handle valid get cluster params
type GetClusterHandler interface {
	Handle(GetClusterParams) middleware.Responder
}

// NewGetCluster creates a new http.Handler for the get cluster operation
func NewGetCluster(ctx *middleware.Context, handler GetClusterHandler) *GetCluster {
	return &GetCluster{Context: ctx, Handler: handler}
}

/*
	GetCluster swagger:route GET /cluster cluster getCluster

Retrieve the list of remote clusters and their status
*/
type GetCluster struct {
	Context *middleware.Context
	Handler GetClusterHandler
}

func (o *GetCluster) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetClusterParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
