debug:
  enabled: true

routingMode: native
endpointRoutes:
    enabled: true

ipv6:
  enabled: true

bgpControlPlane:
  enabled: true

ipv4NativeRoutingCIDR: 10.0.0.0/8
ipv6NativeRoutingCIDR: fd00::/16

ipam:
  mode: multi-pool
  operator:
    autoCreateCiliumPodIPPools:
      default:
        ipv4:
          cidrs:
            - 10.10.0.0/16
          maskSize: 24
        ipv6:
          cidrs:
            - fd00:10:1::/48
          maskSize: 64

kubeProxyReplacement: true

bpf:
  masquerade: true

operator:
  enabled: true
  replicas: 1
