# === BPF datapath ===
bpf:
  hostLegacyRouting: true

# === Service / load balancer ===
socketLB:
  enabled: false
  hostNamespaceOnly: true
loadBalancer:
  algorithm: maglev
  dsrDispatch: geneve
  serviceTopology: true
nodePort:
  autoProtectPortRange: true
  bindProtection: true
  enableHealthCheck: true

# === Envoy embedded in cilium-agent (no separate DaemonSet) ===
envoy:
  enabled: false

# === IPAM / identity ===
ipam:
  mode: kubernetes
identityAllocationMode: crd
identityManagementMode: agent
