// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cilium/cilium/api/v1/models"
)

// GetFqdnGccacheOKCode is the HTTP code returned for type GetFqdnGccacheOK
const GetFqdnGccacheOKCode int = 200

/*
GetFqdnGccacheOK Success

swagger:response getFqdnGccacheOK
*/
type GetFqdnGccacheOK struct {

	/*
	  In: Body
	*/
	Payload []*models.FQDNGCCacheEntry `json:"body,omitempty"`
}

// NewGetFqdnGccacheOK creates GetFqdnGccacheOK with default headers values
func NewGetFqdnGccacheOK() *GetFqdnGccacheOK {

	return &GetFqdnGccacheOK{}
}

// WithPayload adds the payload to the get fqdn gccache o k response
func (o *GetFqdnGccacheOK) WithPayload(payload []*models.FQDNGCCacheEntry) *GetFqdnGccacheOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get fqdn gccache o k response
func (o *GetFqdnGccacheOK) SetPayload(payload []*models.FQDNGCCacheEntry) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFqdnGccacheOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.FQDNGCCacheEntry, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
