#!/usr/bin/env bash
eval `go build -work -a 2>&1`
find $WORK -type f -name "*.a" | xargs -I{} du -hxs "{}" | sort -rh | sed s@_pkg_.a@importcfg@g | xargs -I{} echo {} | awk '{print $1; system("bash -c '\''grep importmap "$2" | head -1'\''")}'
