name: Feature Proposal
description: Suggest a feature to Cilium
labels: ["kind/feature", "kind/cfp"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking time to make a feature proposal for Cilium! If you have usage questions, please try the [slack channel](https://slack.cilium.io) and see the [FAQ](https://github.com/cilium/cilium/issues?utf8=%E2%9C%93&q=is:issue+label:kind/question+) first.
  - type: textarea
    id: problem
    attributes:
      label: Is your proposed feature related to a problem?
      description: If so, please describe the problem.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature you'd like
      description: Include any specific requirements you need.
      placeholder: "I would like Cilium to..."
    validations:
      required: true
  - type: textarea
    id: relevant-teams
    attributes:
      label: Notify relevant community channels
      description: |
        Notify the members of any relevant code owners from the [teams](https://github.com/cilium/community/tree/main/ladder/teams) list (e.g. @cilium/example).

        If you don't know which team to include or you haven't gotten feedback, consider raising this topic on [Slack](https://docs.cilium.io/en/stable/community/community/#slack) in the #development channel or during a [community meeting](https://docs.cilium.io/en/stable/community/community/#community-meetings) for awareness.
      placeholder: "@cilium/..."
    validations:
      required: false
  - type: textarea
    id: proposed-solution
    attributes:
      label: "(Optional) Describe your proposed solution"
      description: |
        Please complete this section if you have ideas / suggestions on how to implement the feature. We strongly recommend discussing your approach with Cilium committers before spending lots of time implementing a change.

        For longer proposals, you are welcome to link to an external doc (e.g. a Google doc). We have a [Cilium Feature Proposal template](https://docs.google.com/document/d/1vtE82JExQHw8_-pX2Uhq5acN1BMPxNlS6cMQUezRTWg/edit) to help you structure your proposal - if you would like to use it, please make a copy and ensure it's publicly visible, and then add the link here.

        Once the CFP is close to being finalized, please add it as a PR to the [design-cfps](https://github.com/cilium/design-cfps) repo for final approval.
    validations:
      required: false
