apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app.kubernetes.io/name: cilium-agent
    app.kubernetes.io/part-of: cilium
  name: cilium-agent
  namespace: kube-system
spec:
  podMetricsEndpoints:
  - honorLabels: true
    interval: 5s
    path: /metrics
    port: prometheus
    relabelings:
    - action: replace
      replacement: ${1}
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: node
  namespaceSelector:
    matchNames:
    - kube-system
  podTargetLabels:
  - k8s-app
  selector:
    matchLabels:
      app.kubernetes.io/name: cilium-agent
