// Code generated by protoc-gen-go. DO NOT EDIT.
// source: envoy/config/filter/http/buffer/v2/buffer.proto

package v2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import duration "github.com/golang/protobuf/ptypes/duration"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"
import _ "github.com/lyft/protoc-gen-validate/validate"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Buffer struct {
	// The maximum request size that the filter will buffer before the connection
	// manager will stop buffering and return a 413 response.
	MaxRequestBytes *wrappers.UInt32Value `protobuf:"bytes,1,opt,name=max_request_bytes,json=maxRequestBytes" json:"max_request_bytes,omitempty"`
	// The maximum number of seconds that the filter will wait for a complete
	// request before returning a 408 response.
	MaxRequestTime       *duration.Duration `protobuf:"bytes,2,opt,name=max_request_time,json=maxRequestTime" json:"max_request_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Buffer) Reset()         { *m = Buffer{} }
func (m *Buffer) String() string { return proto.CompactTextString(m) }
func (*Buffer) ProtoMessage()    {}
func (*Buffer) Descriptor() ([]byte, []int) {
	return fileDescriptor_buffer_c5f5ff738db1d284, []int{0}
}
func (m *Buffer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Buffer.Unmarshal(m, b)
}
func (m *Buffer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Buffer.Marshal(b, m, deterministic)
}
func (dst *Buffer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Buffer.Merge(dst, src)
}
func (m *Buffer) XXX_Size() int {
	return xxx_messageInfo_Buffer.Size(m)
}
func (m *Buffer) XXX_DiscardUnknown() {
	xxx_messageInfo_Buffer.DiscardUnknown(m)
}

var xxx_messageInfo_Buffer proto.InternalMessageInfo

func (m *Buffer) GetMaxRequestBytes() *wrappers.UInt32Value {
	if m != nil {
		return m.MaxRequestBytes
	}
	return nil
}

func (m *Buffer) GetMaxRequestTime() *duration.Duration {
	if m != nil {
		return m.MaxRequestTime
	}
	return nil
}

type BufferPerRoute struct {
	// Types that are valid to be assigned to Override:
	//	*BufferPerRoute_Disabled
	//	*BufferPerRoute_Buffer
	Override             isBufferPerRoute_Override `protobuf_oneof:"override"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *BufferPerRoute) Reset()         { *m = BufferPerRoute{} }
func (m *BufferPerRoute) String() string { return proto.CompactTextString(m) }
func (*BufferPerRoute) ProtoMessage()    {}
func (*BufferPerRoute) Descriptor() ([]byte, []int) {
	return fileDescriptor_buffer_c5f5ff738db1d284, []int{1}
}
func (m *BufferPerRoute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BufferPerRoute.Unmarshal(m, b)
}
func (m *BufferPerRoute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BufferPerRoute.Marshal(b, m, deterministic)
}
func (dst *BufferPerRoute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BufferPerRoute.Merge(dst, src)
}
func (m *BufferPerRoute) XXX_Size() int {
	return xxx_messageInfo_BufferPerRoute.Size(m)
}
func (m *BufferPerRoute) XXX_DiscardUnknown() {
	xxx_messageInfo_BufferPerRoute.DiscardUnknown(m)
}

var xxx_messageInfo_BufferPerRoute proto.InternalMessageInfo

type isBufferPerRoute_Override interface {
	isBufferPerRoute_Override()
}

type BufferPerRoute_Disabled struct {
	Disabled bool `protobuf:"varint,1,opt,name=disabled,oneof"`
}
type BufferPerRoute_Buffer struct {
	Buffer *Buffer `protobuf:"bytes,2,opt,name=buffer,oneof"`
}

func (*BufferPerRoute_Disabled) isBufferPerRoute_Override() {}
func (*BufferPerRoute_Buffer) isBufferPerRoute_Override()   {}

func (m *BufferPerRoute) GetOverride() isBufferPerRoute_Override {
	if m != nil {
		return m.Override
	}
	return nil
}

func (m *BufferPerRoute) GetDisabled() bool {
	if x, ok := m.GetOverride().(*BufferPerRoute_Disabled); ok {
		return x.Disabled
	}
	return false
}

func (m *BufferPerRoute) GetBuffer() *Buffer {
	if x, ok := m.GetOverride().(*BufferPerRoute_Buffer); ok {
		return x.Buffer
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*BufferPerRoute) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _BufferPerRoute_OneofMarshaler, _BufferPerRoute_OneofUnmarshaler, _BufferPerRoute_OneofSizer, []interface{}{
		(*BufferPerRoute_Disabled)(nil),
		(*BufferPerRoute_Buffer)(nil),
	}
}

func _BufferPerRoute_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*BufferPerRoute)
	// override
	switch x := m.Override.(type) {
	case *BufferPerRoute_Disabled:
		t := uint64(0)
		if x.Disabled {
			t = 1
		}
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *BufferPerRoute_Buffer:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Buffer); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("BufferPerRoute.Override has unexpected type %T", x)
	}
	return nil
}

func _BufferPerRoute_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*BufferPerRoute)
	switch tag {
	case 1: // override.disabled
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Override = &BufferPerRoute_Disabled{x != 0}
		return true, err
	case 2: // override.buffer
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Buffer)
		err := b.DecodeMessage(msg)
		m.Override = &BufferPerRoute_Buffer{msg}
		return true, err
	default:
		return false, nil
	}
}

func _BufferPerRoute_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*BufferPerRoute)
	// override
	switch x := m.Override.(type) {
	case *BufferPerRoute_Disabled:
		n += 1 // tag and wire
		n += 1
	case *BufferPerRoute_Buffer:
		s := proto.Size(x.Buffer)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Buffer)(nil), "envoy.config.filter.http.buffer.v2.Buffer")
	proto.RegisterType((*BufferPerRoute)(nil), "envoy.config.filter.http.buffer.v2.BufferPerRoute")
}

func init() {
	proto.RegisterFile("envoy/config/filter/http/buffer/v2/buffer.proto", fileDescriptor_buffer_c5f5ff738db1d284)
}

var fileDescriptor_buffer_c5f5ff738db1d284 = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x3f, 0x4e, 0xe3, 0x40,
	0x18, 0xc5, 0x33, 0xce, 0x9f, 0xf5, 0xce, 0x4a, 0xd9, 0xc4, 0x5a, 0x69, 0xb3, 0xab, 0xd5, 0x6e,
	0x94, 0x66, 0x51, 0x8a, 0x19, 0xc9, 0xb9, 0x81, 0x45, 0x01, 0x5d, 0x64, 0x08, 0x05, 0x4d, 0x34,
	0xc6, 0x9f, 0xcd, 0x20, 0xdb, 0x63, 0xc6, 0x63, 0x93, 0x5c, 0x81, 0x13, 0x50, 0x71, 0x00, 0x6a,
	0x0a, 0x44, 0x95, 0x9b, 0x50, 0xe7, 0x16, 0xc8, 0x9e, 0x09, 0x20, 0xa5, 0xa0, 0x7b, 0xf2, 0xf3,
	0xfb, 0xbd, 0xf7, 0xd9, 0x98, 0x42, 0x56, 0x89, 0x35, 0xbd, 0x10, 0x59, 0xc4, 0x63, 0x1a, 0xf1,
	0x44, 0x81, 0xa4, 0x97, 0x4a, 0xe5, 0x34, 0x28, 0xa3, 0x08, 0x24, 0xad, 0x5c, 0xa3, 0x48, 0x2e,
	0x85, 0x12, 0xce, 0xa4, 0x09, 0x10, 0x1d, 0x20, 0x3a, 0x40, 0xea, 0x00, 0x31, 0xaf, 0x55, 0xee,
	0xef, 0xbf, 0xb1, 0x10, 0x71, 0x02, 0xb4, 0x49, 0x04, 0x65, 0x44, 0xc3, 0x52, 0x32, 0xc5, 0x45,
	0xa6, 0x19, 0xfb, 0xfe, 0x8d, 0x64, 0x79, 0x0e, 0xb2, 0x30, 0xfe, 0xcf, 0x8a, 0x25, 0x3c, 0x64,
	0x0a, 0xe8, 0x4e, 0x18, 0xe3, 0x47, 0x2c, 0x62, 0xd1, 0x48, 0x5a, 0x2b, 0xfd, 0x74, 0xf2, 0x88,
	0x70, 0xcf, 0x6b, 0xca, 0x9d, 0x13, 0x3c, 0x4c, 0xd9, 0x6a, 0x29, 0xe1, 0xba, 0x84, 0x42, 0x2d,
	0x83, 0xb5, 0x82, 0x62, 0x84, 0xc6, 0xe8, 0xe0, 0x9b, 0xfb, 0x87, 0xe8, 0x56, 0xb2, 0x6b, 0x25,
	0x8b, 0xe3, 0x4c, 0xcd, 0xdc, 0x33, 0x96, 0x94, 0xe0, 0x7d, 0x7d, 0xde, 0x6e, 0xda, 0x9d, 0xa9,
	0x35, 0x6e, 0xf9, 0xdf, 0x53, 0xb6, 0xf2, 0x35, 0xc0, 0xab, 0xf3, 0xce, 0x02, 0x0f, 0x3e, 0x42,
	0x15, 0x4f, 0x61, 0x64, 0x35, 0xcc, 0x5f, 0x7b, 0xcc, 0x43, 0x73, 0xa9, 0x37, 0xb8, 0x7b, 0xf9,
	0x87, 0x6a, 0xe8, 0x97, 0x07, 0xd4, 0xb1, 0xd1, 0xb4, 0xe5, 0xf7, 0xdf, 0xb9, 0xa7, 0x3c, 0x85,
	0xc9, 0x3d, 0xc2, 0x7d, 0x3d, 0x7b, 0x0e, 0xd2, 0x17, 0xa5, 0x02, 0xe7, 0x3f, 0xb6, 0x43, 0x5e,
	0xb0, 0x20, 0x81, 0xb0, 0x59, 0x6d, 0x9b, 0x5d, 0x57, 0x96, 0x8d, 0x8e, 0x5a, 0xfe, 0x9b, 0xe9,
	0xcc, 0x71, 0x4f, 0x7f, 0x6e, 0x33, 0x64, 0x4a, 0x3e, 0xff, 0x2d, 0x44, 0x97, 0x79, 0xb8, 0x46,
	0x76, 0x6f, 0x91, 0x35, 0xa8, 0x99, 0x86, 0xe3, 0x0d, 0xb1, 0x2d, 0x2a, 0x90, 0x92, 0x87, 0xe0,
	0x74, 0x9f, 0xb6, 0x9b, 0x36, 0xf2, 0x3a, 0xe7, 0x56, 0xe5, 0x06, 0xbd, 0xe6, 0xb6, 0xd9, 0x6b,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x98, 0x9c, 0xdc, 0xe8, 0x2a, 0x02, 0x00, 0x00,
}
