# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 2.0.0"

$bootstrap = <<SCRIPT
sudo sed -i -re 's/([a-z]{2}\.)?archive.ubuntu.com|security.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list
apt-get update
#apt-get -y upgrade
#install new kernel?

apt -y install docker.io

curl -sL http://repos.mesosphere.com/ubuntu/pool/main/m/mesos/mesos_1.5.0-2.0.1.ubuntu1704_amd64.deb > /tmp/mesos_1.5.0-2.0.1.ubuntu1704_amd64.deb
apt -y install /tmp/mesos_1.5.0-2.0.1.ubuntu1704_amd64.deb

# remove openjdk-9 as it conflicts with zookeeper
# removing openjdk-9 will install openjdk-8 automatically
apt -y remove openjdk-9-jre-headless

echo "/var/lib/mesos" > /etc/mesos/work_dir
echo "zk://192.168.44.11:2181/mesos" > /etc/mesos/zk
echo "192.168.44.11" > /etc/mesos-master/ip
echo "192.168.44.11" > /etc/mesos-slave/ip
echo "/var/run/docker.sock" > /etc/mesos-slave/docker_socket
echo "docker,mesos" > /etc/mesos-slave/containerizers
echo "docker" > /etc/mesos-slave/image_providers
echo "filesystem/linux,docker/runtime" > /etc/mesos-slave/isolation
echo "/opt/cni/bin" > /etc/mesos-slave/network_cni_plugins_dir
echo "/etc/cni/net.d" > /etc/mesos-slave/network_cni_config_dir

curl -sL https://downloads.mesosphere.com/marathon/releases/1.6.322/marathon-1.6.322-2bf46b341.tgz | tar -xz
mv marathon-1.6.322-2bf46b341 marathon

# allow default user to use docker
usermod -aG docker vagrant

curl -sL https://github.com/docker/compose/releases/download/1.14.0/docker-compose-`uname -s`-`uname -m` > /usr/bin/docker-compose
chmod a+x /usr/bin/docker-compose

service zookeeper restart
service mesos-master restart
service mesos-slave restart

cd /home/vagrant/allfiles

docker-compose up -d

while [[ -z $cilium_docker ]]; do
        sleep 1
        cilium_docker=$(docker ps -a -q --filter="ancestor=cilium/cilium:stable" --filter="status=running")
done

# copy cilium from container to host
mkdir /home/vagrant/bin
docker cp $cilium_docker:/usr/bin/cilium /home/vagrant/bin/cilium
docker exec $cilium_docker /cni-install.sh
echo 'PATH=$PATH:/home/vagrant/bin' >> /home/vagrant/.bashrc

chown -R vagrant:vagrant /home/vagrant/
echo "Deploying Vagrant VM + Cilium + Mesos...done"

echo 'cd /home/vagrant/allfiles' >> /home/vagrant/.bashrc
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-17.04"
  config.vm.provision "file", source: "./allfiles", destination: "./allfiles"
  config.vm.provision "bootstrap", type: "shell", inline: $bootstrap
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "private_network", ip: "192.168.44.11"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end
end
