// Code generated by protoc-gen-go. DO NOT EDIT.
// source: envoy/config/filter/accesslog/v2/accesslog.proto

/*
Package v2 is a generated protocol buffer package.

It is generated from these files:
	envoy/config/filter/accesslog/v2/accesslog.proto

It has these top-level messages:
	AccessLogCommon
	ResponseFlags
	TLSProperties
	TCPAccessLogEntry
	HTTPRequestProperties
	HTTPResponseProperties
	HTTPAccessLogEntry
	AccessLog
	AccessLogFilter
	ComparisonFilter
	StatusCodeFilter
	DurationFilter
	NotHealthCheckFilter
	TraceableFilter
	RuntimeFilter
	AndFilter
	OrFilter
	FileAccessLog
*/
package v2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import envoy_api_v2_core "github.com/cilium/cilium/pkg/envoy/envoy/api/v2/core"
import envoy_api_v2_core1 "github.com/cilium/cilium/pkg/envoy/envoy/api/v2/core"
import envoy_type "github.com/cilium/cilium/pkg/envoy/envoy/type"
import google_protobuf2 "github.com/golang/protobuf/ptypes/duration"
import google_protobuf4 "github.com/golang/protobuf/ptypes/struct"
import google_protobuf3 "github.com/golang/protobuf/ptypes/timestamp"
import google_protobuf "github.com/golang/protobuf/ptypes/wrappers"
import _ "github.com/lyft/protoc-gen-validate/validate"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reasons why the request was unauthorized
type ResponseFlags_Unauthorized_Reason int32

const (
	ResponseFlags_Unauthorized_REASON_UNSPECIFIED ResponseFlags_Unauthorized_Reason = 0
	// The request was denied by the external authorization service.
	ResponseFlags_Unauthorized_EXTERNAL_SERVICE ResponseFlags_Unauthorized_Reason = 1
)

var ResponseFlags_Unauthorized_Reason_name = map[int32]string{
	0: "REASON_UNSPECIFIED",
	1: "EXTERNAL_SERVICE",
}
var ResponseFlags_Unauthorized_Reason_value = map[string]int32{
	"REASON_UNSPECIFIED": 0,
	"EXTERNAL_SERVICE":   1,
}

func (x ResponseFlags_Unauthorized_Reason) String() string {
	return proto.EnumName(ResponseFlags_Unauthorized_Reason_name, int32(x))
}
func (ResponseFlags_Unauthorized_Reason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0, 0}
}

type TLSProperties_TLSVersion int32

const (
	TLSProperties_VERSION_UNSPECIFIED TLSProperties_TLSVersion = 0
	TLSProperties_TLSv1               TLSProperties_TLSVersion = 1
	TLSProperties_TLSv1_1             TLSProperties_TLSVersion = 2
	TLSProperties_TLSv1_2             TLSProperties_TLSVersion = 3
	TLSProperties_TLSv1_3             TLSProperties_TLSVersion = 4
)

var TLSProperties_TLSVersion_name = map[int32]string{
	0: "VERSION_UNSPECIFIED",
	1: "TLSv1",
	2: "TLSv1_1",
	3: "TLSv1_2",
	4: "TLSv1_3",
}
var TLSProperties_TLSVersion_value = map[string]int32{
	"VERSION_UNSPECIFIED": 0,
	"TLSv1":               1,
	"TLSv1_1":             2,
	"TLSv1_2":             3,
	"TLSv1_3":             4,
}

func (x TLSProperties_TLSVersion) String() string {
	return proto.EnumName(TLSProperties_TLSVersion_name, int32(x))
}
func (TLSProperties_TLSVersion) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

// HTTP version
type HTTPAccessLogEntry_HTTPVersion int32

const (
	HTTPAccessLogEntry_PROTOCOL_UNSPECIFIED HTTPAccessLogEntry_HTTPVersion = 0
	HTTPAccessLogEntry_HTTP10               HTTPAccessLogEntry_HTTPVersion = 1
	HTTPAccessLogEntry_HTTP11               HTTPAccessLogEntry_HTTPVersion = 2
	HTTPAccessLogEntry_HTTP2                HTTPAccessLogEntry_HTTPVersion = 3
)

var HTTPAccessLogEntry_HTTPVersion_name = map[int32]string{
	0: "PROTOCOL_UNSPECIFIED",
	1: "HTTP10",
	2: "HTTP11",
	3: "HTTP2",
}
var HTTPAccessLogEntry_HTTPVersion_value = map[string]int32{
	"PROTOCOL_UNSPECIFIED": 0,
	"HTTP10":               1,
	"HTTP11":               2,
	"HTTP2":                3,
}

func (x HTTPAccessLogEntry_HTTPVersion) String() string {
	return proto.EnumName(HTTPAccessLogEntry_HTTPVersion_name, int32(x))
}
func (HTTPAccessLogEntry_HTTPVersion) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 0}
}

type ComparisonFilter_Op int32

const (
	// =
	ComparisonFilter_EQ ComparisonFilter_Op = 0
	// >=
	ComparisonFilter_GE ComparisonFilter_Op = 1
	// <=
	ComparisonFilter_LE ComparisonFilter_Op = 2
)

var ComparisonFilter_Op_name = map[int32]string{
	0: "EQ",
	1: "GE",
	2: "LE",
}
var ComparisonFilter_Op_value = map[string]int32{
	"EQ": 0,
	"GE": 1,
	"LE": 2,
}

func (x ComparisonFilter_Op) String() string {
	return proto.EnumName(ComparisonFilter_Op_name, int32(x))
}
func (ComparisonFilter_Op) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{9, 0} }

// Defines fields that are shared by all Envoy access logs.
// [#not-implemented-hide:] Not configuration. TBD how to doc proto APIs.
type AccessLogCommon struct {
	// This field indicates the rate at which this log entry was sampled.
	// Valid range is (0.0, 1.0].
	SampleRate float64 `protobuf:"fixed64,1,opt,name=sample_rate,json=sampleRate" json:"sample_rate,omitempty"`
	// This field is the remote/origin address on which the request from the user was received.
	// Note: This may not be the physical peer. E.g, if the remote address is inferred from for
	//       example the x-forwarder-for header, proxy protocol, etc.
	DownstreamRemoteAddress *envoy_api_v2_core.Address `protobuf:"bytes,2,opt,name=downstream_remote_address,json=downstreamRemoteAddress" json:"downstream_remote_address,omitempty"`
	// This field is the local/destination address on which the request from the user was received.
	DownstreamLocalAddress *envoy_api_v2_core.Address `protobuf:"bytes,3,opt,name=downstream_local_address,json=downstreamLocalAddress" json:"downstream_local_address,omitempty"`
	// If the connection is secure, this field will contain TLS properties.
	TlsProperties *TLSProperties `protobuf:"bytes,4,opt,name=tls_properties,json=tlsProperties" json:"tls_properties,omitempty"`
	// The time that Envoy started servicing this request. This is effectively the time that the first
	// downstream byte is received.
	StartTime *google_protobuf3.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	// Interval between the first downstream byte received and the last
	// downstream byte received (i.e. time it takes to receive a request).
	TimeToLastRxByte *google_protobuf2.Duration `protobuf:"bytes,6,opt,name=time_to_last_rx_byte,json=timeToLastRxByte" json:"time_to_last_rx_byte,omitempty"`
	// Interval between the first downstream byte received and the first upstream byte sent. There may
	// by considerable delta between *time_to_last_rx_byte* and this value due to filters.
	// Additionally, the same caveats apply as documented in *time_to_last_downstream_tx_byte* about
	// not accounting for kernel socket buffer time, etc.
	TimeToFirstUpstreamTxByte *google_protobuf2.Duration `protobuf:"bytes,7,opt,name=time_to_first_upstream_tx_byte,json=timeToFirstUpstreamTxByte" json:"time_to_first_upstream_tx_byte,omitempty"`
	// Interval between the first downstream byte received and the last upstream byte sent. There may
	// by considerable delta between *time_to_last_rx_byte* and this value due to filters.
	// Additionally, the same caveats apply as documented in *time_to_last_downstream_tx_byte* about
	// not accounting for kernel socket buffer time, etc.
	TimeToLastUpstreamTxByte *google_protobuf2.Duration `protobuf:"bytes,8,opt,name=time_to_last_upstream_tx_byte,json=timeToLastUpstreamTxByte" json:"time_to_last_upstream_tx_byte,omitempty"`
	// Interval between the first downstream byte received and the first upstream
	// byte received (i.e. time it takes to start receiving a response).
	TimeToFirstUpstreamRxByte *google_protobuf2.Duration `protobuf:"bytes,9,opt,name=time_to_first_upstream_rx_byte,json=timeToFirstUpstreamRxByte" json:"time_to_first_upstream_rx_byte,omitempty"`
	// Interval between the first downstream byte received and the last upstream
	// byte received (i.e. time it takes to receive a complete response).
	TimeToLastUpstreamRxByte *google_protobuf2.Duration `protobuf:"bytes,10,opt,name=time_to_last_upstream_rx_byte,json=timeToLastUpstreamRxByte" json:"time_to_last_upstream_rx_byte,omitempty"`
	// Interval between the first downstream byte received and the first downstream byte sent.
	// There may be a considerable delta between the *time_to_first_upstream_rx_byte* and this field
	// due to filters. Additionally, the same caveats apply as documented in
	// *time_to_last_downstream_tx_byte* about not accounting for kernel socket buffer time, etc.
	TimeToFirstDownstreamTxByte *google_protobuf2.Duration `protobuf:"bytes,11,opt,name=time_to_first_downstream_tx_byte,json=timeToFirstDownstreamTxByte" json:"time_to_first_downstream_tx_byte,omitempty"`
	// Interval between the first downstream byte received and the last downstream byte sent.
	// Depending on protocol, buffering, windowing, filters, etc. there may be a considerable delta
	// between *time_to_last_upstream_rx_byte* and this field. Note also that this is an approximate
	// time. In the current implementation it does not include kernel socket buffer time. In the
	// current implementation it also does not include send window buffering inside the HTTP/2 codec.
	// In the future it is likely that work will be done to make this duration more accurate.
	TimeToLastDownstreamTxByte *google_protobuf2.Duration `protobuf:"bytes,12,opt,name=time_to_last_downstream_tx_byte,json=timeToLastDownstreamTxByte" json:"time_to_last_downstream_tx_byte,omitempty"`
	// The upstream remote/destination address that handles this exchange. This does not include
	// retries.
	UpstreamRemoteAddress *envoy_api_v2_core.Address `protobuf:"bytes,13,opt,name=upstream_remote_address,json=upstreamRemoteAddress" json:"upstream_remote_address,omitempty"`
	// The upstream local/origin address that handles this exchange. This does not include retries.
	UpstreamLocalAddress *envoy_api_v2_core.Address `protobuf:"bytes,14,opt,name=upstream_local_address,json=upstreamLocalAddress" json:"upstream_local_address,omitempty"`
	// The upstream cluster that *upstream_remote_address* belongs to.
	UpstreamCluster string `protobuf:"bytes,15,opt,name=upstream_cluster,json=upstreamCluster" json:"upstream_cluster,omitempty"`
	// Flags indicating occurrences during request/response processing.
	ResponseFlags *ResponseFlags `protobuf:"bytes,16,opt,name=response_flags,json=responseFlags" json:"response_flags,omitempty"`
	// All metadata encountered during request processing, including endpoint
	// selection.
	//
	// This can be used to associate IDs attached to the various configurations
	// used to process this request with the access log entry. For example, a
	// route created from a higher level forwarding rule with some ID can place
	// that ID in this field and cross reference later. It can also be used to
	// determine if a canary endpoint was used or not.
	Metadata *envoy_api_v2_core1.Metadata `protobuf:"bytes,17,opt,name=metadata" json:"metadata,omitempty"`
}

func (m *AccessLogCommon) Reset()                    { *m = AccessLogCommon{} }
func (m *AccessLogCommon) String() string            { return proto.CompactTextString(m) }
func (*AccessLogCommon) ProtoMessage()               {}
func (*AccessLogCommon) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AccessLogCommon) GetSampleRate() float64 {
	if m != nil {
		return m.SampleRate
	}
	return 0
}

func (m *AccessLogCommon) GetDownstreamRemoteAddress() *envoy_api_v2_core.Address {
	if m != nil {
		return m.DownstreamRemoteAddress
	}
	return nil
}

func (m *AccessLogCommon) GetDownstreamLocalAddress() *envoy_api_v2_core.Address {
	if m != nil {
		return m.DownstreamLocalAddress
	}
	return nil
}

func (m *AccessLogCommon) GetTlsProperties() *TLSProperties {
	if m != nil {
		return m.TlsProperties
	}
	return nil
}

func (m *AccessLogCommon) GetStartTime() *google_protobuf3.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *AccessLogCommon) GetTimeToLastRxByte() *google_protobuf2.Duration {
	if m != nil {
		return m.TimeToLastRxByte
	}
	return nil
}

func (m *AccessLogCommon) GetTimeToFirstUpstreamTxByte() *google_protobuf2.Duration {
	if m != nil {
		return m.TimeToFirstUpstreamTxByte
	}
	return nil
}

func (m *AccessLogCommon) GetTimeToLastUpstreamTxByte() *google_protobuf2.Duration {
	if m != nil {
		return m.TimeToLastUpstreamTxByte
	}
	return nil
}

func (m *AccessLogCommon) GetTimeToFirstUpstreamRxByte() *google_protobuf2.Duration {
	if m != nil {
		return m.TimeToFirstUpstreamRxByte
	}
	return nil
}

func (m *AccessLogCommon) GetTimeToLastUpstreamRxByte() *google_protobuf2.Duration {
	if m != nil {
		return m.TimeToLastUpstreamRxByte
	}
	return nil
}

func (m *AccessLogCommon) GetTimeToFirstDownstreamTxByte() *google_protobuf2.Duration {
	if m != nil {
		return m.TimeToFirstDownstreamTxByte
	}
	return nil
}

func (m *AccessLogCommon) GetTimeToLastDownstreamTxByte() *google_protobuf2.Duration {
	if m != nil {
		return m.TimeToLastDownstreamTxByte
	}
	return nil
}

func (m *AccessLogCommon) GetUpstreamRemoteAddress() *envoy_api_v2_core.Address {
	if m != nil {
		return m.UpstreamRemoteAddress
	}
	return nil
}

func (m *AccessLogCommon) GetUpstreamLocalAddress() *envoy_api_v2_core.Address {
	if m != nil {
		return m.UpstreamLocalAddress
	}
	return nil
}

func (m *AccessLogCommon) GetUpstreamCluster() string {
	if m != nil {
		return m.UpstreamCluster
	}
	return ""
}

func (m *AccessLogCommon) GetResponseFlags() *ResponseFlags {
	if m != nil {
		return m.ResponseFlags
	}
	return nil
}

func (m *AccessLogCommon) GetMetadata() *envoy_api_v2_core1.Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// [#not-implemented-hide:] Not configuration. TBD how to doc proto APIs.
// Flags indicating occurrences during request/response processing.
type ResponseFlags struct {
	// Indicates local server healthcheck failed.
	FailedLocalHealthcheck bool `protobuf:"varint,1,opt,name=failed_local_healthcheck,json=failedLocalHealthcheck" json:"failed_local_healthcheck,omitempty"`
	// Indicates there was no healthy upstream.
	NoHealthyUpstream bool `protobuf:"varint,2,opt,name=no_healthy_upstream,json=noHealthyUpstream" json:"no_healthy_upstream,omitempty"`
	// Indicates an there was an upstream request timeout.
	UpstreamRequestTimeout bool `protobuf:"varint,3,opt,name=upstream_request_timeout,json=upstreamRequestTimeout" json:"upstream_request_timeout,omitempty"`
	// Indicates local codec level reset was sent on the stream.
	LocalReset bool `protobuf:"varint,4,opt,name=local_reset,json=localReset" json:"local_reset,omitempty"`
	// Indicates remote codec level reset was received on the stream.
	UpstreamRemoteReset bool `protobuf:"varint,5,opt,name=upstream_remote_reset,json=upstreamRemoteReset" json:"upstream_remote_reset,omitempty"`
	// Indicates there was a local reset by a connection pool due to an initial connection failure.
	UpstreamConnectionFailure bool `protobuf:"varint,6,opt,name=upstream_connection_failure,json=upstreamConnectionFailure" json:"upstream_connection_failure,omitempty"`
	// Indicates the stream was reset locally due to connection termination.
	UpstreamConnectionTermination bool `protobuf:"varint,7,opt,name=upstream_connection_termination,json=upstreamConnectionTermination" json:"upstream_connection_termination,omitempty"`
	// Indicates the stream was reset because of a resource overflow.
	UpstreamOverflow bool `protobuf:"varint,8,opt,name=upstream_overflow,json=upstreamOverflow" json:"upstream_overflow,omitempty"`
	// Indicates no route was found for the request.
	NoRouteFound bool `protobuf:"varint,9,opt,name=no_route_found,json=noRouteFound" json:"no_route_found,omitempty"`
	// Indicates that the request was delayed before proxying.
	DelayInjected bool `protobuf:"varint,10,opt,name=delay_injected,json=delayInjected" json:"delay_injected,omitempty"`
	// Indicates that the request was aborted with an injected error code.
	FaultInjected bool `protobuf:"varint,11,opt,name=fault_injected,json=faultInjected" json:"fault_injected,omitempty"`
	// Indicates that the request was rate-limited locally.
	RateLimited bool `protobuf:"varint,12,opt,name=rate_limited,json=rateLimited" json:"rate_limited,omitempty"`
	// Indicates if the request was deemed unauthorized and the reason for it.
	UnauthorizedDetails *ResponseFlags_Unauthorized `protobuf:"bytes,13,opt,name=unauthorized_details,json=unauthorizedDetails" json:"unauthorized_details,omitempty"`
}

func (m *ResponseFlags) Reset()                    { *m = ResponseFlags{} }
func (m *ResponseFlags) String() string            { return proto.CompactTextString(m) }
func (*ResponseFlags) ProtoMessage()               {}
func (*ResponseFlags) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ResponseFlags) GetFailedLocalHealthcheck() bool {
	if m != nil {
		return m.FailedLocalHealthcheck
	}
	return false
}

func (m *ResponseFlags) GetNoHealthyUpstream() bool {
	if m != nil {
		return m.NoHealthyUpstream
	}
	return false
}

func (m *ResponseFlags) GetUpstreamRequestTimeout() bool {
	if m != nil {
		return m.UpstreamRequestTimeout
	}
	return false
}

func (m *ResponseFlags) GetLocalReset() bool {
	if m != nil {
		return m.LocalReset
	}
	return false
}

func (m *ResponseFlags) GetUpstreamRemoteReset() bool {
	if m != nil {
		return m.UpstreamRemoteReset
	}
	return false
}

func (m *ResponseFlags) GetUpstreamConnectionFailure() bool {
	if m != nil {
		return m.UpstreamConnectionFailure
	}
	return false
}

func (m *ResponseFlags) GetUpstreamConnectionTermination() bool {
	if m != nil {
		return m.UpstreamConnectionTermination
	}
	return false
}

func (m *ResponseFlags) GetUpstreamOverflow() bool {
	if m != nil {
		return m.UpstreamOverflow
	}
	return false
}

func (m *ResponseFlags) GetNoRouteFound() bool {
	if m != nil {
		return m.NoRouteFound
	}
	return false
}

func (m *ResponseFlags) GetDelayInjected() bool {
	if m != nil {
		return m.DelayInjected
	}
	return false
}

func (m *ResponseFlags) GetFaultInjected() bool {
	if m != nil {
		return m.FaultInjected
	}
	return false
}

func (m *ResponseFlags) GetRateLimited() bool {
	if m != nil {
		return m.RateLimited
	}
	return false
}

func (m *ResponseFlags) GetUnauthorizedDetails() *ResponseFlags_Unauthorized {
	if m != nil {
		return m.UnauthorizedDetails
	}
	return nil
}

type ResponseFlags_Unauthorized struct {
	Reason ResponseFlags_Unauthorized_Reason `protobuf:"varint,1,opt,name=reason,enum=envoy.config.filter.accesslog.v2.ResponseFlags_Unauthorized_Reason" json:"reason,omitempty"`
}

func (m *ResponseFlags_Unauthorized) Reset()                    { *m = ResponseFlags_Unauthorized{} }
func (m *ResponseFlags_Unauthorized) String() string            { return proto.CompactTextString(m) }
func (*ResponseFlags_Unauthorized) ProtoMessage()               {}
func (*ResponseFlags_Unauthorized) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *ResponseFlags_Unauthorized) GetReason() ResponseFlags_Unauthorized_Reason {
	if m != nil {
		return m.Reason
	}
	return ResponseFlags_Unauthorized_REASON_UNSPECIFIED
}

// [#not-implemented-hide:] Not configuration. TBD how to doc proto APIs.
// Properties of a negotiated TLS connection.
type TLSProperties struct {
	// Version of TLS that was negotiated.
	TlsVersion TLSProperties_TLSVersion `protobuf:"varint,1,opt,name=tls_version,json=tlsVersion,enum=envoy.config.filter.accesslog.v2.TLSProperties_TLSVersion" json:"tls_version,omitempty"`
	// TLS cipher suite negotiated during handshake. The value is a
	// four-digit hex code defined by the IANA TLS Cipher Suite Registry
	// (e.g. ``009C`` for ``TLS_RSA_WITH_AES_128_GCM_SHA256``).
	//
	// Here it is expressed as an integer.
	TlsCipherSuite *google_protobuf.UInt32Value `protobuf:"bytes,2,opt,name=tls_cipher_suite,json=tlsCipherSuite" json:"tls_cipher_suite,omitempty"`
	// SNI hostname from handshake.
	TlsSniHostname string `protobuf:"bytes,3,opt,name=tls_sni_hostname,json=tlsSniHostname" json:"tls_sni_hostname,omitempty"`
}

func (m *TLSProperties) Reset()                    { *m = TLSProperties{} }
func (m *TLSProperties) String() string            { return proto.CompactTextString(m) }
func (*TLSProperties) ProtoMessage()               {}
func (*TLSProperties) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TLSProperties) GetTlsVersion() TLSProperties_TLSVersion {
	if m != nil {
		return m.TlsVersion
	}
	return TLSProperties_VERSION_UNSPECIFIED
}

func (m *TLSProperties) GetTlsCipherSuite() *google_protobuf.UInt32Value {
	if m != nil {
		return m.TlsCipherSuite
	}
	return nil
}

func (m *TLSProperties) GetTlsSniHostname() string {
	if m != nil {
		return m.TlsSniHostname
	}
	return ""
}

// [#not-implemented-hide:] Not configuration. TBD how to doc proto APIs.
type TCPAccessLogEntry struct {
	// Common properties shared by all Envoy access logs.
	CommonProperties *AccessLogCommon `protobuf:"bytes,1,opt,name=common_properties,json=commonProperties" json:"common_properties,omitempty"`
}

func (m *TCPAccessLogEntry) Reset()                    { *m = TCPAccessLogEntry{} }
func (m *TCPAccessLogEntry) String() string            { return proto.CompactTextString(m) }
func (*TCPAccessLogEntry) ProtoMessage()               {}
func (*TCPAccessLogEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TCPAccessLogEntry) GetCommonProperties() *AccessLogCommon {
	if m != nil {
		return m.CommonProperties
	}
	return nil
}

// [#not-implemented-hide:] Not configuration. TBD how to doc proto APIs.
type HTTPRequestProperties struct {
	// The request method (RFC 7231/2616).
	// [#comment:TODO(htuch): add (validate.rules).enum.defined_only = true once
	// https://github.com/lyft/protoc-gen-validate/issues/42 is resolved.]
	RequestMethod envoy_api_v2_core1.RequestMethod `protobuf:"varint,1,opt,name=request_method,json=requestMethod,enum=envoy.api.v2.core.RequestMethod" json:"request_method,omitempty"`
	// The scheme portion of the incoming request URI.
	Scheme string `protobuf:"bytes,2,opt,name=scheme" json:"scheme,omitempty"`
	// HTTP/2 ``:authority`` or HTTP/1.1 ``Host`` header value.
	Authority string `protobuf:"bytes,3,opt,name=authority" json:"authority,omitempty"`
	// The port of the incoming request URI
	// (unused currently, as port is composed onto authority).
	Port *google_protobuf.UInt32Value `protobuf:"bytes,4,opt,name=port" json:"port,omitempty"`
	// The path portion from the incoming request URI.
	Path string `protobuf:"bytes,5,opt,name=path" json:"path,omitempty"`
	// Value of the ``User-Agent`` request header.
	UserAgent string `protobuf:"bytes,6,opt,name=user_agent,json=userAgent" json:"user_agent,omitempty"`
	// Value of the ``Referer`` request header.
	Referer string `protobuf:"bytes,7,opt,name=referer" json:"referer,omitempty"`
	// Value of the ``X-Forwarded-For`` request header.
	ForwardedFor string `protobuf:"bytes,8,opt,name=forwarded_for,json=forwardedFor" json:"forwarded_for,omitempty"`
	// Value of the ``X-Request-Id`` request header
	//
	// This header is used by Envoy to uniquely identify a request.
	// It will be generated for all external requests and internal requests that
	// do not already have a request ID.
	RequestId string `protobuf:"bytes,9,opt,name=request_id,json=requestId" json:"request_id,omitempty"`
	// Value of the ``X-Envoy-Original-Path`` request header.
	OriginalPath string `protobuf:"bytes,10,opt,name=original_path,json=originalPath" json:"original_path,omitempty"`
	// Size of the HTTP request headers in bytes.
	//
	// This value is captured from the OSI layer 7 perspective, i.e. it does not
	// include overhead from framing or encoding at other networking layers.
	RequestHeadersBytes uint64 `protobuf:"varint,11,opt,name=request_headers_bytes,json=requestHeadersBytes" json:"request_headers_bytes,omitempty"`
	// Size of the HTTP request body in bytes.
	//
	// This value is captured from the OSI layer 7 perspective, i.e. it does not
	// include overhead from framing or encoding at other networking layers.
	RequestBodyBytes uint64 `protobuf:"varint,12,opt,name=request_body_bytes,json=requestBodyBytes" json:"request_body_bytes,omitempty"`
	// Map of additional headers that have been configured to be logged.
	RequestHeaders map[string]string `protobuf:"bytes,13,rep,name=request_headers,json=requestHeaders" json:"request_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *HTTPRequestProperties) Reset()                    { *m = HTTPRequestProperties{} }
func (m *HTTPRequestProperties) String() string            { return proto.CompactTextString(m) }
func (*HTTPRequestProperties) ProtoMessage()               {}
func (*HTTPRequestProperties) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *HTTPRequestProperties) GetRequestMethod() envoy_api_v2_core1.RequestMethod {
	if m != nil {
		return m.RequestMethod
	}
	return envoy_api_v2_core1.RequestMethod_METHOD_UNSPECIFIED
}

func (m *HTTPRequestProperties) GetScheme() string {
	if m != nil {
		return m.Scheme
	}
	return ""
}

func (m *HTTPRequestProperties) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *HTTPRequestProperties) GetPort() *google_protobuf.UInt32Value {
	if m != nil {
		return m.Port
	}
	return nil
}

func (m *HTTPRequestProperties) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *HTTPRequestProperties) GetUserAgent() string {
	if m != nil {
		return m.UserAgent
	}
	return ""
}

func (m *HTTPRequestProperties) GetReferer() string {
	if m != nil {
		return m.Referer
	}
	return ""
}

func (m *HTTPRequestProperties) GetForwardedFor() string {
	if m != nil {
		return m.ForwardedFor
	}
	return ""
}

func (m *HTTPRequestProperties) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *HTTPRequestProperties) GetOriginalPath() string {
	if m != nil {
		return m.OriginalPath
	}
	return ""
}

func (m *HTTPRequestProperties) GetRequestHeadersBytes() uint64 {
	if m != nil {
		return m.RequestHeadersBytes
	}
	return 0
}

func (m *HTTPRequestProperties) GetRequestBodyBytes() uint64 {
	if m != nil {
		return m.RequestBodyBytes
	}
	return 0
}

func (m *HTTPRequestProperties) GetRequestHeaders() map[string]string {
	if m != nil {
		return m.RequestHeaders
	}
	return nil
}

// [#not-implemented-hide:] Not configuration. TBD how to doc proto APIs.
type HTTPResponseProperties struct {
	// The HTTP response code returned by Envoy.
	ResponseCode *google_protobuf.UInt32Value `protobuf:"bytes,1,opt,name=response_code,json=responseCode" json:"response_code,omitempty"`
	// Size of the HTTP response headers in bytes.
	//
	// This value is captured from the OSI layer 7 perspective, i.e. it does not
	// include overhead from framing or encoding at other networking layers.
	ResponseHeadersBytes uint64 `protobuf:"varint,2,opt,name=response_headers_bytes,json=responseHeadersBytes" json:"response_headers_bytes,omitempty"`
	// Size of the HTTP response body in bytes.
	//
	// This value is captured from the OSI layer 7 perspective, i.e. it does not
	// include overhead from framing or encoding at other networking layers.
	ResponseBodyBytes uint64 `protobuf:"varint,3,opt,name=response_body_bytes,json=responseBodyBytes" json:"response_body_bytes,omitempty"`
	// Map of additional headers configured to be logged.
	ResponseHeaders map[string]string `protobuf:"bytes,4,rep,name=response_headers,json=responseHeaders" json:"response_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *HTTPResponseProperties) Reset()                    { *m = HTTPResponseProperties{} }
func (m *HTTPResponseProperties) String() string            { return proto.CompactTextString(m) }
func (*HTTPResponseProperties) ProtoMessage()               {}
func (*HTTPResponseProperties) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *HTTPResponseProperties) GetResponseCode() *google_protobuf.UInt32Value {
	if m != nil {
		return m.ResponseCode
	}
	return nil
}

func (m *HTTPResponseProperties) GetResponseHeadersBytes() uint64 {
	if m != nil {
		return m.ResponseHeadersBytes
	}
	return 0
}

func (m *HTTPResponseProperties) GetResponseBodyBytes() uint64 {
	if m != nil {
		return m.ResponseBodyBytes
	}
	return 0
}

func (m *HTTPResponseProperties) GetResponseHeaders() map[string]string {
	if m != nil {
		return m.ResponseHeaders
	}
	return nil
}

// [#not-implemented-hide:] Not configuration. TBD how to doc proto APIs.
type HTTPAccessLogEntry struct {
	// Common properties shared by all Envoy access logs.
	CommonProperties *AccessLogCommon               `protobuf:"bytes,1,opt,name=common_properties,json=commonProperties" json:"common_properties,omitempty"`
	ProtocolVersion  HTTPAccessLogEntry_HTTPVersion `protobuf:"varint,2,opt,name=protocol_version,json=protocolVersion,enum=envoy.config.filter.accesslog.v2.HTTPAccessLogEntry_HTTPVersion" json:"protocol_version,omitempty"`
	// Description of the incoming HTTP request.
	Request *HTTPRequestProperties `protobuf:"bytes,3,opt,name=request" json:"request,omitempty"`
	// Description of the outgoing HTTP response.
	Response *HTTPResponseProperties `protobuf:"bytes,4,opt,name=response" json:"response,omitempty"`
}

func (m *HTTPAccessLogEntry) Reset()                    { *m = HTTPAccessLogEntry{} }
func (m *HTTPAccessLogEntry) String() string            { return proto.CompactTextString(m) }
func (*HTTPAccessLogEntry) ProtoMessage()               {}
func (*HTTPAccessLogEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *HTTPAccessLogEntry) GetCommonProperties() *AccessLogCommon {
	if m != nil {
		return m.CommonProperties
	}
	return nil
}

func (m *HTTPAccessLogEntry) GetProtocolVersion() HTTPAccessLogEntry_HTTPVersion {
	if m != nil {
		return m.ProtocolVersion
	}
	return HTTPAccessLogEntry_PROTOCOL_UNSPECIFIED
}

func (m *HTTPAccessLogEntry) GetRequest() *HTTPRequestProperties {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *HTTPAccessLogEntry) GetResponse() *HTTPResponseProperties {
	if m != nil {
		return m.Response
	}
	return nil
}

type AccessLog struct {
	// The name of the access log implementation to instantiate. The name must
	// match a statically registered access log. Current built-in loggers include:
	// 1) "envoy.file_access_log"
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Filter which is used to determine if the access log needs to be written.
	Filter *AccessLogFilter `protobuf:"bytes,2,opt,name=filter" json:"filter,omitempty"`
	// Custom configuration that depends on the access log being instantiated. built-in configurations
	// include:
	// 1) "envoy.file_access_log": :ref:`FileAccessLog
	// <envoy_api_msg_config.filter.accesslog.v2.FileAccessLog>`
	Config *google_protobuf4.Struct `protobuf:"bytes,3,opt,name=config" json:"config,omitempty"`
}

func (m *AccessLog) Reset()                    { *m = AccessLog{} }
func (m *AccessLog) String() string            { return proto.CompactTextString(m) }
func (*AccessLog) ProtoMessage()               {}
func (*AccessLog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *AccessLog) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AccessLog) GetFilter() *AccessLogFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *AccessLog) GetConfig() *google_protobuf4.Struct {
	if m != nil {
		return m.Config
	}
	return nil
}

type AccessLogFilter struct {
	// Types that are valid to be assigned to FilterSpecifier:
	//	*AccessLogFilter_StatusCodeFilter
	//	*AccessLogFilter_DurationFilter
	//	*AccessLogFilter_NotHealthCheckFilter
	//	*AccessLogFilter_TraceableFilter
	//	*AccessLogFilter_RuntimeFilter
	//	*AccessLogFilter_AndFilter
	//	*AccessLogFilter_OrFilter
	FilterSpecifier isAccessLogFilter_FilterSpecifier `protobuf_oneof:"filter_specifier"`
}

func (m *AccessLogFilter) Reset()                    { *m = AccessLogFilter{} }
func (m *AccessLogFilter) String() string            { return proto.CompactTextString(m) }
func (*AccessLogFilter) ProtoMessage()               {}
func (*AccessLogFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type isAccessLogFilter_FilterSpecifier interface {
	isAccessLogFilter_FilterSpecifier()
}

type AccessLogFilter_StatusCodeFilter struct {
	StatusCodeFilter *StatusCodeFilter `protobuf:"bytes,1,opt,name=status_code_filter,json=statusCodeFilter,oneof"`
}
type AccessLogFilter_DurationFilter struct {
	DurationFilter *DurationFilter `protobuf:"bytes,2,opt,name=duration_filter,json=durationFilter,oneof"`
}
type AccessLogFilter_NotHealthCheckFilter struct {
	NotHealthCheckFilter *NotHealthCheckFilter `protobuf:"bytes,3,opt,name=not_health_check_filter,json=notHealthCheckFilter,oneof"`
}
type AccessLogFilter_TraceableFilter struct {
	TraceableFilter *TraceableFilter `protobuf:"bytes,4,opt,name=traceable_filter,json=traceableFilter,oneof"`
}
type AccessLogFilter_RuntimeFilter struct {
	RuntimeFilter *RuntimeFilter `protobuf:"bytes,5,opt,name=runtime_filter,json=runtimeFilter,oneof"`
}
type AccessLogFilter_AndFilter struct {
	AndFilter *AndFilter `protobuf:"bytes,6,opt,name=and_filter,json=andFilter,oneof"`
}
type AccessLogFilter_OrFilter struct {
	OrFilter *OrFilter `protobuf:"bytes,7,opt,name=or_filter,json=orFilter,oneof"`
}

func (*AccessLogFilter_StatusCodeFilter) isAccessLogFilter_FilterSpecifier()     {}
func (*AccessLogFilter_DurationFilter) isAccessLogFilter_FilterSpecifier()       {}
func (*AccessLogFilter_NotHealthCheckFilter) isAccessLogFilter_FilterSpecifier() {}
func (*AccessLogFilter_TraceableFilter) isAccessLogFilter_FilterSpecifier()      {}
func (*AccessLogFilter_RuntimeFilter) isAccessLogFilter_FilterSpecifier()        {}
func (*AccessLogFilter_AndFilter) isAccessLogFilter_FilterSpecifier()            {}
func (*AccessLogFilter_OrFilter) isAccessLogFilter_FilterSpecifier()             {}

func (m *AccessLogFilter) GetFilterSpecifier() isAccessLogFilter_FilterSpecifier {
	if m != nil {
		return m.FilterSpecifier
	}
	return nil
}

func (m *AccessLogFilter) GetStatusCodeFilter() *StatusCodeFilter {
	if x, ok := m.GetFilterSpecifier().(*AccessLogFilter_StatusCodeFilter); ok {
		return x.StatusCodeFilter
	}
	return nil
}

func (m *AccessLogFilter) GetDurationFilter() *DurationFilter {
	if x, ok := m.GetFilterSpecifier().(*AccessLogFilter_DurationFilter); ok {
		return x.DurationFilter
	}
	return nil
}

func (m *AccessLogFilter) GetNotHealthCheckFilter() *NotHealthCheckFilter {
	if x, ok := m.GetFilterSpecifier().(*AccessLogFilter_NotHealthCheckFilter); ok {
		return x.NotHealthCheckFilter
	}
	return nil
}

func (m *AccessLogFilter) GetTraceableFilter() *TraceableFilter {
	if x, ok := m.GetFilterSpecifier().(*AccessLogFilter_TraceableFilter); ok {
		return x.TraceableFilter
	}
	return nil
}

func (m *AccessLogFilter) GetRuntimeFilter() *RuntimeFilter {
	if x, ok := m.GetFilterSpecifier().(*AccessLogFilter_RuntimeFilter); ok {
		return x.RuntimeFilter
	}
	return nil
}

func (m *AccessLogFilter) GetAndFilter() *AndFilter {
	if x, ok := m.GetFilterSpecifier().(*AccessLogFilter_AndFilter); ok {
		return x.AndFilter
	}
	return nil
}

func (m *AccessLogFilter) GetOrFilter() *OrFilter {
	if x, ok := m.GetFilterSpecifier().(*AccessLogFilter_OrFilter); ok {
		return x.OrFilter
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*AccessLogFilter) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _AccessLogFilter_OneofMarshaler, _AccessLogFilter_OneofUnmarshaler, _AccessLogFilter_OneofSizer, []interface{}{
		(*AccessLogFilter_StatusCodeFilter)(nil),
		(*AccessLogFilter_DurationFilter)(nil),
		(*AccessLogFilter_NotHealthCheckFilter)(nil),
		(*AccessLogFilter_TraceableFilter)(nil),
		(*AccessLogFilter_RuntimeFilter)(nil),
		(*AccessLogFilter_AndFilter)(nil),
		(*AccessLogFilter_OrFilter)(nil),
	}
}

func _AccessLogFilter_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*AccessLogFilter)
	// filter_specifier
	switch x := m.FilterSpecifier.(type) {
	case *AccessLogFilter_StatusCodeFilter:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.StatusCodeFilter); err != nil {
			return err
		}
	case *AccessLogFilter_DurationFilter:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DurationFilter); err != nil {
			return err
		}
	case *AccessLogFilter_NotHealthCheckFilter:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.NotHealthCheckFilter); err != nil {
			return err
		}
	case *AccessLogFilter_TraceableFilter:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TraceableFilter); err != nil {
			return err
		}
	case *AccessLogFilter_RuntimeFilter:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RuntimeFilter); err != nil {
			return err
		}
	case *AccessLogFilter_AndFilter:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AndFilter); err != nil {
			return err
		}
	case *AccessLogFilter_OrFilter:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OrFilter); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("AccessLogFilter.FilterSpecifier has unexpected type %T", x)
	}
	return nil
}

func _AccessLogFilter_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*AccessLogFilter)
	switch tag {
	case 1: // filter_specifier.status_code_filter
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(StatusCodeFilter)
		err := b.DecodeMessage(msg)
		m.FilterSpecifier = &AccessLogFilter_StatusCodeFilter{msg}
		return true, err
	case 2: // filter_specifier.duration_filter
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DurationFilter)
		err := b.DecodeMessage(msg)
		m.FilterSpecifier = &AccessLogFilter_DurationFilter{msg}
		return true, err
	case 3: // filter_specifier.not_health_check_filter
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(NotHealthCheckFilter)
		err := b.DecodeMessage(msg)
		m.FilterSpecifier = &AccessLogFilter_NotHealthCheckFilter{msg}
		return true, err
	case 4: // filter_specifier.traceable_filter
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TraceableFilter)
		err := b.DecodeMessage(msg)
		m.FilterSpecifier = &AccessLogFilter_TraceableFilter{msg}
		return true, err
	case 5: // filter_specifier.runtime_filter
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RuntimeFilter)
		err := b.DecodeMessage(msg)
		m.FilterSpecifier = &AccessLogFilter_RuntimeFilter{msg}
		return true, err
	case 6: // filter_specifier.and_filter
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AndFilter)
		err := b.DecodeMessage(msg)
		m.FilterSpecifier = &AccessLogFilter_AndFilter{msg}
		return true, err
	case 7: // filter_specifier.or_filter
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(OrFilter)
		err := b.DecodeMessage(msg)
		m.FilterSpecifier = &AccessLogFilter_OrFilter{msg}
		return true, err
	default:
		return false, nil
	}
}

func _AccessLogFilter_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*AccessLogFilter)
	// filter_specifier
	switch x := m.FilterSpecifier.(type) {
	case *AccessLogFilter_StatusCodeFilter:
		s := proto.Size(x.StatusCodeFilter)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AccessLogFilter_DurationFilter:
		s := proto.Size(x.DurationFilter)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AccessLogFilter_NotHealthCheckFilter:
		s := proto.Size(x.NotHealthCheckFilter)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AccessLogFilter_TraceableFilter:
		s := proto.Size(x.TraceableFilter)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AccessLogFilter_RuntimeFilter:
		s := proto.Size(x.RuntimeFilter)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AccessLogFilter_AndFilter:
		s := proto.Size(x.AndFilter)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AccessLogFilter_OrFilter:
		s := proto.Size(x.OrFilter)
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Filter on an integer comparison.
type ComparisonFilter struct {
	// Comparison operator.
	Op ComparisonFilter_Op `protobuf:"varint,1,opt,name=op,enum=envoy.config.filter.accesslog.v2.ComparisonFilter_Op" json:"op,omitempty"`
	// Value to compare against.
	Value *envoy_api_v2_core1.RuntimeUInt32 `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *ComparisonFilter) Reset()                    { *m = ComparisonFilter{} }
func (m *ComparisonFilter) String() string            { return proto.CompactTextString(m) }
func (*ComparisonFilter) ProtoMessage()               {}
func (*ComparisonFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ComparisonFilter) GetOp() ComparisonFilter_Op {
	if m != nil {
		return m.Op
	}
	return ComparisonFilter_EQ
}

func (m *ComparisonFilter) GetValue() *envoy_api_v2_core1.RuntimeUInt32 {
	if m != nil {
		return m.Value
	}
	return nil
}

// Filters on HTTP response/status code.
type StatusCodeFilter struct {
	// Comparison.
	Comparison *ComparisonFilter `protobuf:"bytes,1,opt,name=comparison" json:"comparison,omitempty"`
}

func (m *StatusCodeFilter) Reset()                    { *m = StatusCodeFilter{} }
func (m *StatusCodeFilter) String() string            { return proto.CompactTextString(m) }
func (*StatusCodeFilter) ProtoMessage()               {}
func (*StatusCodeFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *StatusCodeFilter) GetComparison() *ComparisonFilter {
	if m != nil {
		return m.Comparison
	}
	return nil
}

// Filters on total request duration in milliseconds.
type DurationFilter struct {
	// Comparison.
	Comparison *ComparisonFilter `protobuf:"bytes,1,opt,name=comparison" json:"comparison,omitempty"`
}

func (m *DurationFilter) Reset()                    { *m = DurationFilter{} }
func (m *DurationFilter) String() string            { return proto.CompactTextString(m) }
func (*DurationFilter) ProtoMessage()               {}
func (*DurationFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *DurationFilter) GetComparison() *ComparisonFilter {
	if m != nil {
		return m.Comparison
	}
	return nil
}

// Filters for requests that are not health check requests. A health check
// request is marked by the health check filter.
type NotHealthCheckFilter struct {
}

func (m *NotHealthCheckFilter) Reset()                    { *m = NotHealthCheckFilter{} }
func (m *NotHealthCheckFilter) String() string            { return proto.CompactTextString(m) }
func (*NotHealthCheckFilter) ProtoMessage()               {}
func (*NotHealthCheckFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

// Filters for requests that are traceable. See the tracing overview for more
// information on how a request becomes traceable.
type TraceableFilter struct {
}

func (m *TraceableFilter) Reset()                    { *m = TraceableFilter{} }
func (m *TraceableFilter) String() string            { return proto.CompactTextString(m) }
func (*TraceableFilter) ProtoMessage()               {}
func (*TraceableFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

// Filters for random sampling of requests.
type RuntimeFilter struct {
	// Runtime key to get an optional overridden numerator for use in the *percent_sampled* field.
	// If found in runtime, this value will replace the default numerator.
	RuntimeKey string `protobuf:"bytes,1,opt,name=runtime_key,json=runtimeKey" json:"runtime_key,omitempty"`
	// The default sampling percentage. If not specified, defaults to 0% with denominator of 100.
	PercentSampled *envoy_type.FractionalPercent `protobuf:"bytes,2,opt,name=percent_sampled,json=percentSampled" json:"percent_sampled,omitempty"`
	// By default, sampling pivots on the header
	// :ref:`x-request-id<config_http_conn_man_headers_x-request-id>` being present. If
	// :ref:`x-request-id<config_http_conn_man_headers_x-request-id>` is present, the filter will
	// consistently sample across multiple hosts based on the runtime key value and the value
	// extracted from :ref:`x-request-id<config_http_conn_man_headers_x-request-id>`. If it is
	// missing, or *use_independent_randomness* is set to true, the filter will randomly sample based
	// on the runtime key value alone. *use_independent_randomness* can be used for logging kill
	// switches within complex nested :ref:`AndFilter
	// <envoy_api_msg_config.filter.accesslog.v2.AndFilter>` and :ref:`OrFilter
	// <envoy_api_msg_config.filter.accesslog.v2.OrFilter>` blocks that are easier to reason about
	// from a probability perspective (i.e., setting to true will cause the filter to behave like
	// an independent random variable when composed within logical operator filters).
	UseIndependentRandomness bool `protobuf:"varint,3,opt,name=use_independent_randomness,json=useIndependentRandomness" json:"use_independent_randomness,omitempty"`
}

func (m *RuntimeFilter) Reset()                    { *m = RuntimeFilter{} }
func (m *RuntimeFilter) String() string            { return proto.CompactTextString(m) }
func (*RuntimeFilter) ProtoMessage()               {}
func (*RuntimeFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *RuntimeFilter) GetRuntimeKey() string {
	if m != nil {
		return m.RuntimeKey
	}
	return ""
}

func (m *RuntimeFilter) GetPercentSampled() *envoy_type.FractionalPercent {
	if m != nil {
		return m.PercentSampled
	}
	return nil
}

func (m *RuntimeFilter) GetUseIndependentRandomness() bool {
	if m != nil {
		return m.UseIndependentRandomness
	}
	return false
}

// Performs a logical “and” operation on the result of each filter in filters.
// Filters are evaluated sequentially and if one of them returns false, the
// filter returns false immediately.
type AndFilter struct {
	Filters []*AccessLogFilter `protobuf:"bytes,1,rep,name=filters" json:"filters,omitempty"`
}

func (m *AndFilter) Reset()                    { *m = AndFilter{} }
func (m *AndFilter) String() string            { return proto.CompactTextString(m) }
func (*AndFilter) ProtoMessage()               {}
func (*AndFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *AndFilter) GetFilters() []*AccessLogFilter {
	if m != nil {
		return m.Filters
	}
	return nil
}

// Performs a logical “or” operation on the result of each individual filter.
// Filters are evaluated sequentially and if one of them returns true, the
// filter returns true immediately.
type OrFilter struct {
	Filters []*AccessLogFilter `protobuf:"bytes,2,rep,name=filters" json:"filters,omitempty"`
}

func (m *OrFilter) Reset()                    { *m = OrFilter{} }
func (m *OrFilter) String() string            { return proto.CompactTextString(m) }
func (*OrFilter) ProtoMessage()               {}
func (*OrFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *OrFilter) GetFilters() []*AccessLogFilter {
	if m != nil {
		return m.Filters
	}
	return nil
}

// Custom configuration for an AccessLog that writes log entries directly to a file.
// Configures the built-in *envoy.file_access_log* AccessLog.
type FileAccessLog struct {
	// A path to a local file to which to write the access log entries.
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	// Access log format. Envoy supports :ref:`custom access log formats
	// <config_access_log_format>` as well as a :ref:`default format
	// <config_access_log_default_format>`.
	Format string `protobuf:"bytes,2,opt,name=format" json:"format,omitempty"`
}

func (m *FileAccessLog) Reset()                    { *m = FileAccessLog{} }
func (m *FileAccessLog) String() string            { return proto.CompactTextString(m) }
func (*FileAccessLog) ProtoMessage()               {}
func (*FileAccessLog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *FileAccessLog) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *FileAccessLog) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func init() {
	proto.RegisterType((*AccessLogCommon)(nil), "envoy.config.filter.accesslog.v2.AccessLogCommon")
	proto.RegisterType((*ResponseFlags)(nil), "envoy.config.filter.accesslog.v2.ResponseFlags")
	proto.RegisterType((*ResponseFlags_Unauthorized)(nil), "envoy.config.filter.accesslog.v2.ResponseFlags.Unauthorized")
	proto.RegisterType((*TLSProperties)(nil), "envoy.config.filter.accesslog.v2.TLSProperties")
	proto.RegisterType((*TCPAccessLogEntry)(nil), "envoy.config.filter.accesslog.v2.TCPAccessLogEntry")
	proto.RegisterType((*HTTPRequestProperties)(nil), "envoy.config.filter.accesslog.v2.HTTPRequestProperties")
	proto.RegisterType((*HTTPResponseProperties)(nil), "envoy.config.filter.accesslog.v2.HTTPResponseProperties")
	proto.RegisterType((*HTTPAccessLogEntry)(nil), "envoy.config.filter.accesslog.v2.HTTPAccessLogEntry")
	proto.RegisterType((*AccessLog)(nil), "envoy.config.filter.accesslog.v2.AccessLog")
	proto.RegisterType((*AccessLogFilter)(nil), "envoy.config.filter.accesslog.v2.AccessLogFilter")
	proto.RegisterType((*ComparisonFilter)(nil), "envoy.config.filter.accesslog.v2.ComparisonFilter")
	proto.RegisterType((*StatusCodeFilter)(nil), "envoy.config.filter.accesslog.v2.StatusCodeFilter")
	proto.RegisterType((*DurationFilter)(nil), "envoy.config.filter.accesslog.v2.DurationFilter")
	proto.RegisterType((*NotHealthCheckFilter)(nil), "envoy.config.filter.accesslog.v2.NotHealthCheckFilter")
	proto.RegisterType((*TraceableFilter)(nil), "envoy.config.filter.accesslog.v2.TraceableFilter")
	proto.RegisterType((*RuntimeFilter)(nil), "envoy.config.filter.accesslog.v2.RuntimeFilter")
	proto.RegisterType((*AndFilter)(nil), "envoy.config.filter.accesslog.v2.AndFilter")
	proto.RegisterType((*OrFilter)(nil), "envoy.config.filter.accesslog.v2.OrFilter")
	proto.RegisterType((*FileAccessLog)(nil), "envoy.config.filter.accesslog.v2.FileAccessLog")
	proto.RegisterEnum("envoy.config.filter.accesslog.v2.ResponseFlags_Unauthorized_Reason", ResponseFlags_Unauthorized_Reason_name, ResponseFlags_Unauthorized_Reason_value)
	proto.RegisterEnum("envoy.config.filter.accesslog.v2.TLSProperties_TLSVersion", TLSProperties_TLSVersion_name, TLSProperties_TLSVersion_value)
	proto.RegisterEnum("envoy.config.filter.accesslog.v2.HTTPAccessLogEntry_HTTPVersion", HTTPAccessLogEntry_HTTPVersion_name, HTTPAccessLogEntry_HTTPVersion_value)
	proto.RegisterEnum("envoy.config.filter.accesslog.v2.ComparisonFilter_Op", ComparisonFilter_Op_name, ComparisonFilter_Op_value)
}

func init() { proto.RegisterFile("envoy/config/filter/accesslog/v2/accesslog.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0xcf, 0x73, 0x1b, 0x49,
	0xf5, 0x8f, 0x64, 0x59, 0xd1, 0x3c, 0x59, 0xf6, 0xb8, 0xad, 0xd8, 0xb2, 0x93, 0xac, 0xbd, 0xfa,
	0x7e, 0xa9, 0x0a, 0xbb, 0x94, 0x94, 0x28, 0x90, 0x4d, 0x6d, 0x6d, 0xb1, 0xd8, 0x8a, 0xb4, 0x31,
	0xeb, 0xc4, 0x4e, 0x4b, 0xf1, 0x6e, 0x91, 0xaa, 0x0c, 0x6d, 0x4d, 0xcb, 0x1e, 0x32, 0x9a, 0x1e,
	0x7a, 0x5a, 0x4e, 0xc4, 0x91, 0x23, 0x27, 0x8a, 0x13, 0x14, 0x47, 0x2e, 0x5c, 0x39, 0x41, 0x2d,
	0x97, 0xf0, 0x4f, 0x70, 0xe5, 0x9c, 0xe2, 0xc2, 0x7f, 0x00, 0xd5, 0x3f, 0x66, 0x46, 0x92, 0xbd,
	0x2b, 0x25, 0xfc, 0xd0, 0x45, 0xdd, 0xef, 0xc7, 0xe7, 0xbd, 0x7e, 0xef, 0xf5, 0xeb, 0xee, 0x81,
	0xdb, 0x34, 0x38, 0x67, 0xa3, 0x7a, 0x8f, 0x05, 0x7d, 0xef, 0xb4, 0xde, 0xf7, 0x7c, 0x41, 0x79,
	0x9d, 0xf4, 0x7a, 0x34, 0x8a, 0x7c, 0x76, 0x5a, 0x3f, 0x6f, 0xa4, 0x93, 0x5a, 0xc8, 0x99, 0x60,
	0x68, 0x47, 0x69, 0xd4, 0xb4, 0x46, 0x4d, 0x6b, 0xd4, 0x52, 0xa1, 0xf3, 0xc6, 0xd6, 0xb6, 0xc6,
	0x24, 0xa1, 0x27, 0xf5, 0x7b, 0x8c, 0xd3, 0x3a, 0x71, 0x5d, 0x4e, 0xa3, 0x48, 0x43, 0x6c, 0xdd,
	0xb8, 0x28, 0x70, 0x42, 0x22, 0x6a, 0xb8, 0x15, 0xcd, 0x15, 0xa3, 0x90, 0xd6, 0x43, 0xca, 0x7b,
	0x34, 0x10, 0x86, 0xf3, 0xde, 0x29, 0x63, 0xa7, 0x3e, 0xad, 0xab, 0xd9, 0xc9, 0xb0, 0x5f, 0x77,
	0x87, 0x9c, 0x08, 0x8f, 0x05, 0x31, 0xee, 0x34, 0x3f, 0x12, 0x7c, 0xd8, 0x8b, 0xb5, 0xb7, 0xa7,
	0xb9, 0xc2, 0x1b, 0xd0, 0x48, 0x90, 0x41, 0xf8, 0x75, 0xf0, 0x2f, 0x39, 0x09, 0x43, 0xca, 0x63,
	0xb7, 0x37, 0xce, 0x89, 0xef, 0xb9, 0x44, 0xd0, 0x7a, 0x3c, 0x30, 0x8c, 0xf2, 0x29, 0x3b, 0x65,
	0x6a, 0x58, 0x97, 0x23, 0x4d, 0xad, 0xfe, 0xbe, 0x08, 0x2b, 0xbb, 0x2a, 0x2e, 0x07, 0xec, 0xb4,
	0xc9, 0x06, 0x03, 0x16, 0xa0, 0x5d, 0x28, 0x46, 0x64, 0x10, 0xfa, 0xd4, 0xe1, 0x44, 0xd0, 0x4a,
	0x66, 0x27, 0x73, 0x2b, 0xb3, 0xb7, 0xf3, 0xd5, 0x9b, 0xd7, 0x0b, 0x45, 0x64, 0xbd, 0x7f, 0xc5,
	0xfc, 0xcc, 0x7c, 0x53, 0xcf, 0xfe, 0xf1, 0x29, 0x06, 0xad, 0x84, 0x89, 0xa0, 0xe8, 0x18, 0x36,
	0x5d, 0xf6, 0x32, 0x88, 0x04, 0xa7, 0x64, 0xe0, 0x70, 0x3a, 0x60, 0x82, 0x3a, 0x26, 0xbe, 0x95,
	0xec, 0x4e, 0xe6, 0x56, 0xb1, 0xb1, 0x55, 0xd3, 0x39, 0x22, 0xa1, 0x57, 0x3b, 0x6f, 0xd4, 0x64,
	0x80, 0x6b, 0xbb, 0x5a, 0x02, 0x6f, 0xa4, 0xca, 0x58, 0xe9, 0x1a, 0x06, 0xea, 0x42, 0x65, 0x0c,
	0xd7, 0x67, 0x3d, 0xe2, 0x27, 0xb0, 0x0b, 0x33, 0x61, 0xd7, 0x53, 0xdd, 0x03, 0xa9, 0x1a, 0xa3,
	0x1e, 0xc3, 0xb2, 0xf0, 0x23, 0x27, 0xe4, 0x2c, 0xa4, 0x5c, 0x78, 0x34, 0xaa, 0xe4, 0x14, 0x56,
	0xbd, 0x36, 0xab, 0x8c, 0x6a, 0xdd, 0x83, 0xce, 0x51, 0xa2, 0x86, 0x4b, 0xc2, 0x8f, 0xd2, 0x29,
	0xfa, 0x14, 0x20, 0x12, 0x84, 0x0b, 0x47, 0x26, 0xb1, 0xb2, 0x68, 0xfc, 0xd3, 0x09, 0xac, 0xc5,
	0x09, 0xac, 0x75, 0xe3, 0x0c, 0xef, 0xe5, 0x7e, 0xf9, 0xb7, 0xed, 0x0c, 0xb6, 0x94, 0x8e, 0xa4,
	0xa2, 0x43, 0x28, 0x4b, 0x55, 0x47, 0x30, 0xc7, 0x27, 0x91, 0x70, 0xf8, 0x2b, 0xe7, 0x64, 0x24,
	0x68, 0x25, 0xaf, 0xa0, 0x36, 0x2f, 0x40, 0x3d, 0x30, 0xa5, 0xb6, 0x97, 0xfb, 0xb5, 0x44, 0xb2,
	0xa5, 0x72, 0x97, 0x1d, 0x90, 0x48, 0xe0, 0x57, 0x7b, 0x23, 0x41, 0xd1, 0x09, 0xbc, 0x17, 0x03,
	0xf6, 0x3d, 0x1e, 0x09, 0x67, 0x18, 0x9a, 0x58, 0x0a, 0x03, 0x7d, 0x75, 0x3e, 0xe8, 0x4d, 0x0d,
	0xdd, 0x96, 0x20, 0x4f, 0x0d, 0x46, 0x57, 0xdb, 0xf8, 0x31, 0xdc, 0x9c, 0x70, 0xfa, 0x82, 0x89,
	0xc2, 0x7c, 0x26, 0x2a, 0xa9, 0xf7, 0x53, 0x16, 0xbe, 0x7e, 0x15, 0x71, 0x80, 0xac, 0x77, 0x5f,
	0x05, 0x9e, 0xb1, 0x8a, 0xd8, 0x04, 0xbc, 0xf3, 0x2a, 0x8c, 0x85, 0x3e, 0xec, 0x4c, 0xae, 0x62,
	0xac, 0xb2, 0xe3, 0x50, 0x15, 0xe7, 0x33, 0x72, 0x7d, 0x6c, 0x1d, 0x0f, 0x12, 0x14, 0x13, 0x2d,
	0x17, 0xb6, 0x27, 0x56, 0x72, 0x89, 0x99, 0xa5, 0xf9, 0xcc, 0x6c, 0xa5, 0x6b, 0xb9, 0x60, 0x05,
	0xc3, 0x46, 0x1a, 0xa2, 0xc9, 0xfd, 0x5e, 0x9a, 0xb9, 0x31, 0xaf, 0xc5, 0xaa, 0x93, 0xbb, 0xfd,
	0x08, 0xd6, 0x13, 0xcc, 0xc9, 0xbd, 0xbe, 0x3c, 0x13, 0xb2, 0x1c, 0x6b, 0x4e, 0xec, 0xf4, 0x6f,
	0x83, 0x9d, 0x20, 0xf6, 0xfc, 0x61, 0x24, 0x28, 0xaf, 0xac, 0xec, 0x64, 0x6e, 0x59, 0x78, 0x25,
	0xa6, 0x37, 0x35, 0x59, 0x36, 0x05, 0x4e, 0xa3, 0x90, 0x05, 0x11, 0x75, 0xfa, 0x3e, 0x39, 0x8d,
	0x2a, 0xf6, 0xbc, 0x4d, 0x01, 0x1b, 0xbd, 0xb6, 0x54, 0xc3, 0x25, 0x3e, 0x3e, 0x45, 0x1f, 0x41,
	0x61, 0x40, 0x05, 0x71, 0x89, 0x20, 0x95, 0x55, 0x85, 0x78, 0xfd, 0x92, 0x65, 0x3c, 0x32, 0x22,
	0x38, 0x11, 0xae, 0xfe, 0x3d, 0x0f, 0xa5, 0x09, 0x64, 0x74, 0x1f, 0x2a, 0x7d, 0xe2, 0xf9, 0xd4,
	0x35, 0xd1, 0x39, 0xa3, 0xc4, 0x17, 0x67, 0xbd, 0x33, 0xda, 0x7b, 0xa1, 0xba, 0x76, 0x01, 0xaf,
	0x6b, 0xbe, 0x8a, 0xc1, 0xc3, 0x94, 0x8b, 0x6a, 0xb0, 0x16, 0x30, 0x23, 0x3f, 0x4a, 0x6a, 0x5b,
	0x75, 0xe6, 0x02, 0x5e, 0x0d, 0x98, 0x96, 0x1d, 0xc5, 0x15, 0x2b, 0x2d, 0x8d, 0x65, 0xf7, 0xa7,
	0x43, 0x1a, 0xe9, 0xa6, 0xc6, 0x86, 0x42, 0xf5, 0xdd, 0x02, 0x5e, 0x4f, 0x53, 0xa8, 0xd8, 0x5d,
	0xcd, 0x45, 0xdb, 0x50, 0xd4, 0xce, 0x71, 0x1a, 0x51, 0xa1, 0x1a, 0x6b, 0x01, 0x83, 0x22, 0x61,
	0x49, 0x41, 0x0d, 0xb8, 0x36, 0x5d, 0x38, 0x5a, 0x74, 0x51, 0x89, 0xae, 0x4d, 0x96, 0x86, 0xd6,
	0xf9, 0x3e, 0x5c, 0x4f, 0xd3, 0xc8, 0x82, 0x80, 0xf6, 0x64, 0x95, 0x3a, 0x72, 0xb1, 0x43, 0xae,
	0xdb, 0x63, 0x01, 0x6f, 0x26, 0x19, 0x4d, 0x24, 0xda, 0x5a, 0x00, 0xb5, 0x61, 0xfb, 0x32, 0x7d,
	0x41, 0xf9, 0xc0, 0x0b, 0x54, 0xc5, 0xab, 0x3e, 0x58, 0xc0, 0x37, 0x2f, 0x62, 0x74, 0x53, 0x21,
	0xf4, 0x21, 0xac, 0x26, 0x38, 0xec, 0x9c, 0xf2, 0xbe, 0xcf, 0x5e, 0xaa, 0xf6, 0x56, 0xc0, 0x49,
	0x9d, 0x1d, 0x1a, 0x3a, 0xfa, 0x7f, 0x58, 0x0e, 0x98, 0xc3, 0xd9, 0x50, 0x50, 0xa7, 0xcf, 0x86,
	0x81, 0xab, 0xba, 0x54, 0x01, 0x2f, 0x05, 0x0c, 0x4b, 0x62, 0x5b, 0xd2, 0xd0, 0xb7, 0x60, 0xd9,
	0xa5, 0x3e, 0x19, 0x39, 0x5e, 0xf0, 0x13, 0xda, 0x13, 0xd4, 0x55, 0x8d, 0xa6, 0x80, 0x4b, 0x8a,
	0xba, 0x6f, 0x88, 0x52, 0xac, 0x4f, 0x86, 0xbe, 0x48, 0xc5, 0x8a, 0x5a, 0x4c, 0x51, 0x13, 0xb1,
	0xf7, 0x61, 0x49, 0x9e, 0xe1, 0x8e, 0xef, 0x0d, 0x3c, 0x29, 0xb4, 0xa4, 0x84, 0x8a, 0x92, 0x76,
	0xa0, 0x49, 0x88, 0x41, 0x79, 0x18, 0x90, 0xa1, 0x38, 0x63, 0xdc, 0xfb, 0x19, 0x75, 0x1d, 0x97,
	0x0a, 0xe2, 0xf9, 0xf1, 0xae, 0xfd, 0xe4, 0x2d, 0xab, 0xbd, 0xf6, 0x74, 0x0c, 0x0b, 0xaf, 0x8d,
	0x23, 0x3f, 0xd0, 0xc0, 0x5b, 0xbf, 0xcb, 0xc0, 0xd2, 0xb8, 0x14, 0x7a, 0x06, 0x79, 0x4e, 0x49,
	0xc4, 0x02, 0x55, 0xb4, 0xcb, 0x8d, 0xe6, 0xbf, 0x63, 0xb3, 0x86, 0x15, 0x14, 0x36, 0x90, 0xd5,
	0x7b, 0x90, 0xd7, 0x14, 0xb4, 0x0e, 0x08, 0xb7, 0x76, 0x3b, 0x87, 0x8f, 0x9d, 0xa7, 0x8f, 0x3b,
	0x47, 0xad, 0xe6, 0x7e, 0x7b, 0xbf, 0xf5, 0xc0, 0xbe, 0x82, 0xca, 0x60, 0xb7, 0xbe, 0xec, 0xb6,
	0xf0, 0xe3, 0xdd, 0x03, 0xa7, 0xd3, 0xc2, 0xc7, 0xfb, 0xcd, 0x96, 0x9d, 0xa9, 0xfe, 0x31, 0x0b,
	0xa5, 0x89, 0xc3, 0x1d, 0x3d, 0x83, 0xa2, 0xbc, 0x25, 0x9c, 0x53, 0x1e, 0x79, 0x89, 0xaf, 0x1f,
	0xbf, 0xe5, 0x15, 0x41, 0xce, 0x8e, 0x35, 0x02, 0x06, 0xe1, 0x47, 0x66, 0x8c, 0xda, 0x60, 0x4b,
	0xf0, 0x9e, 0x17, 0x9e, 0x51, 0xee, 0x44, 0x43, 0x4f, 0x50, 0x73, 0x4f, 0xba, 0x71, 0xa1, 0x2b,
	0x3f, 0xdd, 0x0f, 0xc4, 0xdd, 0xc6, 0x31, 0xf1, 0x87, 0x14, 0xcb, 0x8b, 0x4b, 0x53, 0x29, 0x75,
	0xa4, 0x0e, 0xba, 0xa5, 0x71, 0xa2, 0xc0, 0x73, 0xce, 0x58, 0x24, 0x02, 0x32, 0xa0, 0x6a, 0x83,
	0x5a, 0x4a, 0xb2, 0x13, 0x78, 0x0f, 0x0d, 0xb5, 0xfa, 0x05, 0x40, 0xea, 0x0b, 0xda, 0x80, 0xb5,
	0xe3, 0x16, 0xee, 0xec, 0x5f, 0x88, 0x8e, 0x05, 0x8b, 0xdd, 0x83, 0xce, 0xf9, 0x1d, 0x3b, 0x83,
	0x8a, 0x70, 0x55, 0x0d, 0x9d, 0x3b, 0x76, 0x36, 0x9d, 0x34, 0xec, 0x85, 0x74, 0x72, 0xd7, 0xce,
	0x55, 0x23, 0x58, 0xed, 0x36, 0x8f, 0x92, 0x4b, 0x65, 0x2b, 0x10, 0x7c, 0x84, 0x9e, 0xc3, 0x6a,
	0x4f, 0xdd, 0x2e, 0xc7, 0x6f, 0x59, 0x19, 0xb5, 0xc0, 0x3b, 0xb3, 0x43, 0x38, 0x75, 0x43, 0xc5,
	0xb6, 0xc6, 0x4a, 0xc3, 0x5a, 0xfd, 0xcd, 0x22, 0x5c, 0x7b, 0xd8, 0xed, 0x1e, 0x99, 0xee, 0x33,
	0x96, 0xb6, 0xcf, 0x64, 0x1f, 0xd7, 0x1d, 0x6b, 0x40, 0xc5, 0x19, 0x73, 0x4d, 0xe6, 0x76, 0x2e,
	0xe9, 0xba, 0x46, 0xfb, 0x91, 0x92, 0x93, 0x8d, 0x7b, 0x6c, 0x8a, 0xd6, 0x21, 0x1f, 0xf5, 0xce,
	0xe8, 0x40, 0x27, 0xc6, 0xc2, 0x66, 0x86, 0x6e, 0x80, 0x65, 0xca, 0x4f, 0x8c, 0x4c, 0xac, 0x53,
	0x02, 0xba, 0x0d, 0xb9, 0x90, 0x71, 0x61, 0x6e, 0x94, 0xdf, 0x9c, 0x4c, 0x25, 0x89, 0x10, 0xe4,
	0x42, 0x22, 0xce, 0x54, 0xff, 0xb3, 0xb0, 0x1a, 0xa3, 0x9b, 0x00, 0xc3, 0x88, 0x72, 0x87, 0x9c,
	0xd2, 0x40, 0xa8, 0xfe, 0x66, 0x61, 0x4b, 0x52, 0x76, 0x25, 0x01, 0x55, 0xe0, 0x2a, 0xa7, 0x7d,
	0xca, 0x29, 0x57, 0x7d, 0xcb, 0xc2, 0xf1, 0x14, 0xfd, 0x1f, 0x94, 0xfa, 0x8c, 0xbf, 0x24, 0xdc,
	0xa5, 0xae, 0xd3, 0x67, 0x5c, 0x75, 0x27, 0x0b, 0x2f, 0x25, 0xc4, 0x36, 0xe3, 0x12, 0x3d, 0x0e,
	0x91, 0xa7, 0xbb, 0x92, 0x85, 0x2d, 0x43, 0xd9, 0x77, 0x25, 0x06, 0xe3, 0xde, 0xa9, 0x17, 0x10,
	0xdf, 0x51, 0x9e, 0x81, 0xc6, 0x88, 0x89, 0x47, 0xd2, 0xc3, 0x06, 0x5c, 0x8b, 0x31, 0xce, 0x28,
	0x71, 0x29, 0x8f, 0xd4, 0xd5, 0x22, 0x52, 0x7d, 0x29, 0x87, 0xd7, 0x0c, 0xf3, 0xa1, 0xe6, 0xc9,
	0x2b, 0x43, 0x84, 0xbe, 0x03, 0x28, 0xd6, 0x39, 0x61, 0xee, 0xc8, 0x28, 0x2c, 0x29, 0x05, 0xdb,
	0x70, 0xf6, 0x98, 0x3b, 0xd2, 0xd2, 0x02, 0x56, 0xa6, 0x2c, 0x54, 0x4a, 0x3b, 0x0b, 0xb7, 0x8a,
	0x8d, 0xcf, 0x67, 0x17, 0xd0, 0xa5, 0xa5, 0x11, 0xa7, 0xdb, 0xf8, 0xa4, 0x0a, 0x15, 0x2f, 0x4f,
	0x3a, 0xba, 0xb5, 0x0b, 0x6b, 0x97, 0x88, 0x21, 0x1b, 0x16, 0x5e, 0xd0, 0x91, 0x2a, 0x25, 0x0b,
	0xcb, 0x21, 0x2a, 0xc3, 0xe2, 0xb9, 0xcc, 0xa2, 0xa9, 0x0e, 0x3d, 0xf9, 0x38, 0x7b, 0x3f, 0x53,
	0xfd, 0x67, 0x16, 0xd6, 0xb5, 0x03, 0xba, 0x69, 0x8d, 0x15, 0xe7, 0x2e, 0x24, 0xb7, 0x03, 0xa7,
	0xc7, 0x5c, 0x6a, 0xb6, 0xc4, 0x37, 0x97, 0xc9, 0x52, 0xac, 0xd2, 0x64, 0x2e, 0x45, 0xdf, 0x85,
	0xf5, 0x04, 0x62, 0x32, 0xf2, 0x59, 0x15, 0xc8, 0x72, 0xcc, 0x9d, 0x08, 0x7d, 0x0d, 0xd6, 0x12,
	0xad, 0xb1, 0xd8, 0x2f, 0x28, 0x95, 0xd5, 0x98, 0x95, 0x06, 0xff, 0x15, 0xd8, 0xd3, 0x56, 0x2a,
	0x39, 0x15, 0xfd, 0x47, 0xf3, 0x46, 0x7f, 0x7a, 0xf1, 0x49, 0x13, 0x9f, 0x88, 0xff, 0xca, 0x94,
	0xbb, 0x5b, 0x7b, 0x50, 0xbe, 0x4c, 0xf0, 0xad, 0x32, 0xf0, 0xd7, 0x05, 0x40, 0xd2, 0x89, 0xff,
	0x6d, 0x53, 0x42, 0x2f, 0xc0, 0x56, 0x09, 0xec, 0x31, 0x3f, 0x39, 0x36, 0xb2, 0xaa, 0xf9, 0xfc,
	0x60, 0xbe, 0xa0, 0x4d, 0xfa, 0xab, 0x48, 0xf1, 0xe1, 0xb1, 0x12, 0x23, 0xc7, 0x1d, 0xfc, 0x89,
	0xec, 0x01, 0xaa, 0x50, 0xcd, 0x4b, 0xf8, 0xa3, 0x77, 0xdc, 0x16, 0x38, 0xc6, 0x41, 0x5d, 0x28,
	0xc4, 0xd9, 0x30, 0xfd, 0xeb, 0xfe, 0xbb, 0x26, 0x1b, 0x27, 0x48, 0xd5, 0x1f, 0x42, 0x71, 0x6c,
	0x21, 0xa8, 0x02, 0xe5, 0x23, 0x7c, 0xd8, 0x3d, 0x6c, 0x1e, 0x1e, 0x4c, 0x1d, 0x3d, 0x00, 0x79,
	0x29, 0x78, 0xe7, 0xb6, 0x9d, 0x49, 0xc6, 0xf2, 0xe8, 0xb1, 0x60, 0x51, 0x8e, 0x1b, 0xf6, 0x42,
	0xf5, 0xb7, 0x19, 0xb0, 0x92, 0x20, 0xc9, 0xce, 0xa9, 0x0e, 0x3c, 0x5d, 0x13, 0x6a, 0x8c, 0xf6,
	0x21, 0xaf, 0xbd, 0x34, 0xc7, 0xe9, 0xdb, 0x24, 0xb6, 0xad, 0x98, 0xd8, 0x00, 0xa0, 0x3a, 0xe4,
	0xb5, 0x96, 0x09, 0xf0, 0xc6, 0x85, 0x5d, 0xda, 0x51, 0x9f, 0x72, 0xb0, 0x11, 0xab, 0xfe, 0x61,
	0x71, 0xec, 0xe3, 0x8a, 0x06, 0x43, 0x27, 0x80, 0x22, 0x41, 0xc4, 0x30, 0x52, 0xfb, 0xdd, 0x31,
	0xbe, 0xe9, 0xa2, 0x6b, 0xcc, 0xf6, 0xad, 0xa3, 0x74, 0xe5, 0xc6, 0xd7, 0x78, 0x0f, 0xaf, 0x60,
	0x3b, 0x9a, 0xa2, 0xa1, 0x67, 0xb0, 0x12, 0x7f, 0x74, 0x72, 0x26, 0x16, 0x7f, 0x7b, 0xb6, 0x81,
	0xf8, 0xc9, 0x97, 0xc0, 0x2f, 0xbb, 0x13, 0x14, 0xc4, 0x60, 0x23, 0x60, 0xc2, 0xbc, 0x1d, 0x1c,
	0xf5, 0x9c, 0x88, 0x8d, 0xe8, 0xb0, 0xdc, 0x9b, 0x6d, 0xe4, 0x31, 0x13, 0xfa, 0x85, 0xd1, 0x94,
	0xea, 0x89, 0xa9, 0x72, 0x70, 0x09, 0x1d, 0x3d, 0x07, 0x5b, 0x70, 0xd2, 0xa3, 0xe4, 0xc4, 0x4f,
	0xe2, 0x95, 0x9b, 0x37, 0x97, 0xdd, 0x58, 0x33, 0x31, 0xb2, 0x22, 0x26, 0x49, 0xe8, 0x4b, 0x58,
	0xe6, 0xc3, 0x40, 0x3d, 0x91, 0x0d, 0xfa, 0xe2, 0xdc, 0x0f, 0x3d, 0xad, 0x97, 0x60, 0x97, 0xf8,
	0x38, 0x01, 0x1d, 0x00, 0x90, 0xc0, 0x8d, 0x51, 0xf5, 0x47, 0x9b, 0x0f, 0xe7, 0xa8, 0xbf, 0xc0,
	0x4d, 0x10, 0x2d, 0x12, 0x4f, 0xd0, 0x3e, 0x58, 0x8c, 0xc7, 0x60, 0xfa, 0x33, 0xcd, 0x07, 0xb3,
	0xc1, 0x0e, 0x79, 0x82, 0x55, 0x60, 0x66, 0xbc, 0xb7, 0x09, 0xb6, 0x96, 0x75, 0xa2, 0x90, 0xf6,
	0xbc, 0xbe, 0x47, 0x39, 0x5a, 0xfc, 0xd3, 0x9b, 0xd7, 0x0b, 0x99, 0xea, 0x9f, 0x33, 0x60, 0x37,
	0xd9, 0x20, 0x24, 0xdc, 0x8b, 0x92, 0x9c, 0x3f, 0x81, 0x2c, 0x0b, 0xcd, 0xbd, 0xe9, 0x7b, 0xb3,
	0x6d, 0x4e, 0xeb, 0xd7, 0x0e, 0xc3, 0x3d, 0xf8, 0xea, 0xcd, 0xeb, 0x85, 0xc5, 0x9f, 0x67, 0xb2,
	0x76, 0x06, 0x67, 0x59, 0x88, 0xee, 0x8d, 0x37, 0xeb, 0xe2, 0xe5, 0xb7, 0x31, 0x1d, 0x4c, 0x7d,
	0xf4, 0x99, 0x76, 0x5e, 0xbd, 0x01, 0xd9, 0xc3, 0x10, 0xe5, 0x21, 0xdb, 0x7a, 0x62, 0x5f, 0x91,
	0xff, 0x9f, 0xb5, 0xec, 0x8c, 0xfc, 0x3f, 0x68, 0xd9, 0xd9, 0x2a, 0x07, 0x7b, 0x7a, 0x87, 0xa0,
	0xe7, 0x00, 0xbd, 0xc4, 0xa1, 0xf9, 0x77, 0xda, 0xf4, 0x22, 0xcc, 0x0a, 0x7e, 0xa1, 0x56, 0x30,
	0x86, 0x58, 0x0d, 0x61, 0x79, 0x72, 0xd3, 0xfc, 0xd7, 0x2d, 0xae, 0x43, 0xf9, 0xb2, 0x1d, 0x54,
	0x5d, 0x85, 0x95, 0xa9, 0x7a, 0xaf, 0xfe, 0x25, 0x03, 0xa5, 0x89, 0x2a, 0x45, 0x1f, 0x40, 0x31,
	0x2e, 0xf7, 0xe4, 0xfc, 0xdc, 0xb3, 0xa4, 0xa5, 0x1c, 0xcf, 0xee, 0x64, 0x30, 0x18, 0xee, 0xe7,
	0x74, 0x84, 0xda, 0xb0, 0x62, 0x3e, 0x6e, 0x3b, 0xfa, 0xe3, 0xae, 0x6b, 0xd2, 0x75, 0xd3, 0xac,
	0x46, 0x8c, 0x42, 0x5a, 0x6b, 0x73, 0xa2, 0x5e, 0xc6, 0xc4, 0x3f, 0xd2, 0xc2, 0x78, 0xd9, 0x68,
	0x75, 0xb4, 0x12, 0xfa, 0x04, 0xb6, 0x86, 0x11, 0x75, 0xbc, 0xc0, 0xa5, 0x21, 0x0d, 0x5c, 0x89,
	0xc7, 0x49, 0xe0, 0xb2, 0x41, 0x10, 0x7f, 0xb8, 0x2d, 0xe0, 0xca, 0x30, 0xa2, 0xfb, 0xa9, 0x00,
	0x4e, 0xf8, 0x55, 0x17, 0xac, 0x64, 0x4b, 0xa0, 0x2f, 0xe0, 0xaa, 0x8e, 0x9d, 0x3c, 0xa9, 0x17,
	0xde, 0xa9, 0xa1, 0x9b, 0xb8, 0xfe, 0x2a, 0x93, 0x2d, 0x64, 0x71, 0x8c, 0x56, 0xed, 0x41, 0x21,
	0xde, 0x2b, 0xe3, 0x46, 0xb2, 0xff, 0x51, 0x23, 0x6d, 0x28, 0xb5, 0x3d, 0x9f, 0xa6, 0x47, 0xd6,
	0x4d, 0x73, 0xd9, 0xbf, 0x90, 0x06, 0x7d, 0xef, 0x5f, 0x87, 0x7c, 0x9f, 0xf1, 0x01, 0x11, 0xf1,
	0x9b, 0x43, 0xcf, 0xf6, 0x72, 0x3f, 0xca, 0x9e, 0x37, 0x4e, 0xf2, 0xea, 0xe0, 0xb9, 0xfb, 0xaf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x22, 0x22, 0x8a, 0x42, 0x20, 0x19, 0x00, 0x00,
}
