{{- if and .Values.agent .Values.prometheus.enabled .Values.prometheus.tls.enabled .Values.prometheus.tls.auto.enabled (eq .Values.prometheus.tls.auto.method "helm") }}
{{- $_ := include "cilium.ca.setup" . -}}
{{- $cn := list (.Values.cluster.name | replace "." "-") "agent-metrics.cilium.io" | join "." }}
{{- $ip := .Values.prometheus.tls.server.extraIpAddresses }}
{{- $dns := prepend .Values.prometheus.tls.server.extraDnsNames $cn }}
{{- $cert := genSignedCert $cn $ip $dns (.Values.prometheus.tls.auto.certValidityDuration | int) .commonCA -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.prometheus.tls.server.existingSecret | default "agent-metrics-server-certs" }}
  namespace: {{ include "cilium.namespace" . }}
  labels:
  {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
    cilium.io/helm-template-non-idempotent: "true"

  annotations:
  {{- with .Values.nonIdempotentAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
data:
  ca.crt:  {{ .commonCA.Cert | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key  | b64enc }}
{{- end }}
