// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cilium/cilium_network_filter.proto

package cilium

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NetworkFilter struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkFilter) Reset()         { *m = NetworkFilter{} }
func (m *NetworkFilter) String() string { return proto.CompactTextString(m) }
func (*NetworkFilter) ProtoMessage()    {}
func (*NetworkFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d495a4248b4ff1, []int{0}
}

func (m *NetworkFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkFilter.Unmarshal(m, b)
}
func (m *NetworkFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkFilter.Marshal(b, m, deterministic)
}
func (m *NetworkFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkFilter.Merge(m, src)
}
func (m *NetworkFilter) XXX_Size() int {
	return xxx_messageInfo_NetworkFilter.Size(m)
}
func (m *NetworkFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkFilter.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkFilter proto.InternalMessageInfo

func init() {
	proto.RegisterType((*NetworkFilter)(nil), "cilium.NetworkFilter")
}

func init() { proto.RegisterFile("cilium/cilium_network_filter.proto", fileDescriptor_97d495a4248b4ff1) }

var fileDescriptor_97d495a4248b4ff1 = []byte{
	// 74 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4a, 0xce, 0xcc, 0xc9,
	0x2c, 0xcd, 0xd5, 0x87, 0x50, 0xf1, 0x79, 0xa9, 0x25, 0xe5, 0xf9, 0x45, 0xd9, 0xf1, 0x69, 0x99,
	0x39, 0x25, 0xa9, 0x45, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x6c, 0x10, 0x49, 0x25, 0x7e,
	0x2e, 0x5e, 0x3f, 0x88, 0xbc, 0x1b, 0x58, 0x3a, 0x89, 0x0d, 0x2c, 0x6f, 0x0c, 0x08, 0x00, 0x00,
	0xff, 0xff, 0x2d, 0x3f, 0x00, 0x1e, 0x45, 0x00, 0x00, 0x00,
}
