// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v2alpha1

// CiliumEgressNATPolicyListerExpansion allows custom methods to be added to
// CiliumEgressNATPolicyLister.
type CiliumEgressNATPolicyListerExpansion interface{}

// CiliumEndpointSliceListerExpansion allows custom methods to be added to
// CiliumEndpointSliceLister.
type CiliumEndpointSliceListerExpansion interface{}

// CiliumEnvoyConfigListerExpansion allows custom methods to be added to
// CiliumEnvoyConfigLister.
type CiliumEnvoyConfigListerExpansion interface{}
