//go:build kubernetes_protomessage_one_more_release
// +build kubernetes_protomessage_one_more_release

// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by go-to-protobuf. DO NOT EDIT.

package v1

func (*IPBlock) ProtoMessage() {}

func (*NetworkPolicy) ProtoMessage() {}

func (*NetworkPolicyEgressRule) ProtoMessage() {}

func (*NetworkPolicyIngressRule) ProtoMessage() {}

func (*NetworkPolicyList) ProtoMessage() {}

func (*NetworkPolicyPeer) ProtoMessage() {}

func (*NetworkPolicyPort) ProtoMessage() {}

func (*NetworkPolicySpec) ProtoMessage() {}
