{{- if and (eq (include "ztunnelSpireInstallEnabled" .) "true") .Values.encryption.ztunnel.spire.install.server.serviceAccount.create -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.encryption.ztunnel.spire.install.server.serviceAccount.name }}
  namespace: {{ .Values.encryption.ztunnel.spire.install.namespace }}
  {{- with .Values.commonLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.encryption.ztunnel.spire.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
# Role (namespace scoped) to be able to push certificate bundles to a configmap
- apiGroups: [ "" ]
  resources: [ "configmaps" ]
  verbs: [ "patch", "get", "list" ]
{{- end }}
