{{- if and (eq (include "ztunnelSpireInstallEnabled" .) "true") .Values.encryption.ztunnel.spire.install.server.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.encryption.ztunnel.spire.install.server.serviceAccount.name }}
  {{- with .Values.commonLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Values.encryption.ztunnel.spire.install.namespace }}
  {{- with .Values.encryption.ztunnel.spire.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
