{{- if eq (include "ztunnelSpireInstallEnabled" .) "true" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-agent
  namespace: {{ .Values.encryption.ztunnel.spire.install.namespace }}
  {{- with .Values.commonLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.encryption.ztunnel.spire.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  agent.conf: |
    agent {
      data_dir = "/run/spire"
      log_level = "ERROR"
      server_address = "spire-server"
      server_port = "8081"
      socket_path = {{ .Values.encryption.ztunnel.spire.agentSocketPath | quote }}
      admin_socket_path = {{ .Values.encryption.ztunnel.spire.adminSocketPath | quote }}
      trust_bundle_path = "/run/spire/bundle/bundle.crt"
      trust_domain = {{ .Values.encryption.ztunnel.spire.trustDomain | quote }}
      authorized_delegates = [
        "spiffe://{{ .Values.encryption.ztunnel.spire.trustDomain }}/cilium-agent",
      ]
    }

    plugins {
      NodeAttestor "k8s_psat" {
        plugin_data {
          cluster = {{ .Values.cluster.name | quote }}
        }
      }

      KeyManager "memory" {
        plugin_data {
        }
      }

      WorkloadAttestor "k8s" {
        plugin_data {
          skip_kubelet_verification = {{ .Values.encryption.ztunnel.spire.install.agent.skipKubeletVerification }}
        }
      }
    }

    health_checks {
      listener_enabled = true
      bind_address = "0.0.0.0"
      bind_port = "4251"
      live_path = "/live"
      ready_path = "/ready"
    }
{{- end }}
