{
 "title": "Cilium Policy Verdicts",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ingress Policy Verdict Rate per Minute by Match Type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (match) (rate(hubble_policy_verdicts_total{direction=\"ingress\",destination=~\"$namespace/.*\"}[$__rate_interval])) * 60",
     "legendFormat": "{{match}}"
    }
   ]
  },
  {
   "title": "Egress Policy Verdict Rate per Minute by Match Type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (match) (rate(hubble_policy_verdicts_total{direction=\"egress\",source=~\"$namespace/.*\"}[$__rate_interval])) * 60",
     "legendFormat": "{{match}}"
    }
   ]
  },
  {
   "title": "Ingress Policy Verdict Rate per Minute by Action",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (action) (rate(hubble_policy_verdicts_total{direction=\"ingress\",destination=~\"$namespace/.*\"}[$__rate_interval])) * 60",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Egress Policy Verdict Rate per Minute by Action",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (action) (rate(hubble_policy_verdicts_total{direction=\"egress\",source=~\"$namespace/.*\"}[$__rate_interval])) * 60",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Current Ingress Policy Verdict Rate Per Minute",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (source, destination, match, action) (rate(hubble_policy_verdicts_total{direction=\"ingress\",destination=~\"$namespace/.*\"}[$__rate_interval])) * 60",
     "legendFormat": "source: {{source}} destination: {{destination}} match: {{match}} action: {{action}}"
    }
   ]
  },
  {
   "title": "Current Egress Policy Verdict Rate Per Minute",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by (destination, source, match, action) (rate(hubble_policy_verdicts_total{direction=\"egress\",source=~\"$namespace/.*\"}[$__rate_interval])) * 60",
     "legendFormat": "destination: {{destination}} source: {{source}} match: {{match}} action: {{action}}"
    }
   ]
  }
 ]
}