// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cilium/cilium/api/v1/models"
)

// GetPolicySubjectSelectorsReader is a Reader for the GetPolicySubjectSelectors structure.
type GetPolicySubjectSelectorsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPolicySubjectSelectorsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetPolicySubjectSelectorsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /policy/subject-selectors] GetPolicySubjectSelectors", response, response.Code())
	}
}

// NewGetPolicySubjectSelectorsOK creates a GetPolicySubjectSelectorsOK with default headers values
func NewGetPolicySubjectSelectorsOK() *GetPolicySubjectSelectorsOK {
	return &GetPolicySubjectSelectorsOK{}
}

/*
GetPolicySubjectSelectorsOK describes a response with status code 200, with default header values.

Success
*/
type GetPolicySubjectSelectorsOK struct {
	Payload models.SelectorCache
}

// IsSuccess returns true when this get policy subject selectors o k response has a 2xx status code
func (o *GetPolicySubjectSelectorsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get policy subject selectors o k response has a 3xx status code
func (o *GetPolicySubjectSelectorsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get policy subject selectors o k response has a 4xx status code
func (o *GetPolicySubjectSelectorsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get policy subject selectors o k response has a 5xx status code
func (o *GetPolicySubjectSelectorsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get policy subject selectors o k response a status code equal to that given
func (o *GetPolicySubjectSelectorsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get policy subject selectors o k response
func (o *GetPolicySubjectSelectorsOK) Code() int {
	return 200
}

func (o *GetPolicySubjectSelectorsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /policy/subject-selectors][%d] getPolicySubjectSelectorsOK %s", 200, payload)
}

func (o *GetPolicySubjectSelectorsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /policy/subject-selectors][%d] getPolicySubjectSelectorsOK %s", 200, payload)
}

func (o *GetPolicySubjectSelectorsOK) GetPayload() models.SelectorCache {
	return o.Payload
}

func (o *GetPolicySubjectSelectorsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
