// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	sockProgAfter            = "after"
	sockProgBefore           = "before"
	sockVarAttachmentContext = "attachment_context"
)

// loadSock returns the embedded CollectionSpec for sock.
func loadSock() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SockBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load sock: %w", err)
	}

	return spec, err
}

// loadSockObjects loads sock and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*sockObjects
//	*sockPrograms
//	*sockMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSockObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadSock()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// sockSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sockSpecs struct {
	sockProgramSpecs
	sockMapSpecs
	sockVariableSpecs
}

// sockProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sockProgramSpecs struct {
	After  *ebpf.ProgramSpec `ebpf:"after"`
	Before *ebpf.ProgramSpec `ebpf:"before"`
}

// sockMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sockMapSpecs struct {
}

// sockVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sockVariableSpecs struct {
	AttachmentContext *ebpf.VariableSpec `ebpf:"attachment_context"`
}

// sockObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSockObjects or ebpf.CollectionSpec.LoadAndAssign.
type sockObjects struct {
	sockPrograms
	sockMaps
	sockVariables
}

func (o *sockObjects) Close() error {
	return _SockClose(
		&o.sockPrograms,
		&o.sockMaps,
	)
}

// sockMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSockObjects or ebpf.CollectionSpec.LoadAndAssign.
type sockMaps struct {
}

func (m *sockMaps) Close() error {
	return _SockClose()
}

// sockVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSockObjects or ebpf.CollectionSpec.LoadAndAssign.
type sockVariables struct {
	AttachmentContext *ebpf.Variable `ebpf:"attachment_context"`
}

// sockPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSockObjects or ebpf.CollectionSpec.LoadAndAssign.
type sockPrograms struct {
	After  *ebpf.Program `ebpf:"after"`
	Before *ebpf.Program `ebpf:"before"`
}

func (p *sockPrograms) Close() error {
	return _SockClose(
		p.After,
		p.Before,
	)
}

func _SockClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed sock_bpfel.o
var _SockBytes []byte
