# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.8.3"

$build = <<SCRIPT
docker run -d -p 5000:5000 registry
cd /home/vagrant/go/src/github.com/cilium/cilium/
make docker-image
export ID=$(docker images | grep "${DOCKER_IMAGE_TAG}" | awk '{print $3}')
docker tag $ID localhost:5000/cilium:${DOCKER_IMAGE_TAG}
docker push localhost:5000/cilium:${DOCKER_IMAGE_TAG}
SCRIPT

$k8s = <<SCRIPT
sudo apt-get update && sudo apt-get install -y apt-transport-https
sudo touch /etc/apt/sources.list.d/kubernetes.list
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg  | sudo apt-key add -
sudo bash -c "cat <<EOF > /etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial main
EOF
"
sudo apt-get update
sudo apt-get install -y docker-engine
sudo apt-get install -y kubelet kubeadm kubectl kubernetes-cni
sudo kubeadm reset
sudo kubeadm init
sudo cp /etc/kubernetes/admin.conf /home/vagrant/admin.conf
sudo chown 1000:1000 /home/vagrant/admin.conf
echo "export KUBECONFIG=/home/vagrant/admin.conf" >> /home/vagrant/.bashrc
echo "export KUBECONFIG=/home/vagrant/admin.conf" >> /home/vagrant/.profile
export KUBECONFIG=/home/vagrant/admin.conf
kubectl taint nodes --all node-role.kubernetes.io/master-
SCRIPT

$testsuite = <<SCRIPT
make -C ~/go/src/github.com/cilium/cilium/ k8s-tests || exit 1
SCRIPT

# Create unique ID for use in vboxnet name so Jenkins pipeline can have concurrent builds.
$job_name = ENV['JOB_NAME'] || "local"
$docker_image_tag=ENV['DOCKER_IMAGE_TAG'] || "local_build"
$build_number = ENV['BUILD_NUMBER'] || "0"
$build_id = "#{$job_name}-#{$build_number}"
$node_ip = "192.168.35.15"
Vagrant.configure(2) do |config|
    config.vm.box = "bento/ubuntu-16.10"

    # http://foo-o-rama.com/vagrant--stdin-is-not-a-tty--fix.html
    config.vm.provision "fix-no-tty", type: "shell" do |s|
        s.privileged = false
        s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
    end

    config.vm.network "private_network", ip: "#{$node_ip}",
        virtualbox__intnet: "cilium-k8s-test-#{$build_id}"

    # install docker runtime
    #config.vm.provision :docker
    config.vm.provision "k8s", type: "shell", inline: $k8s
    config.vm.provision "build", type: "shell", inline: $build, env: {"DOCKER_IMAGE_TAG" => $docker_image_tag}
    config.vm.provider "virtualbox" do |vb|
        # Ignore contrib/packaging/docker/stage to prevent concurrent
        # problems when using rsync on multiple VMs
        config.vm.synced_folder '../../', '/home/vagrant/go/src/github.com/cilium/cilium', type: "rsync",
        rsync__exclude: "contrib/packaging/docker/stage"
    end
    if ENV['RUN_TEST_SUITE'] then
        config.vm.provision "testsuite", run: "always", type: "shell", privileged: false, inline: $testsuite, env: {"DOCKER_IMAGE_TAG" => $docker_image_tag}
    end
end
