graph LR
  table(resizable<br />hashtable) --> bin1(...)
  table(resizable<br />hashtable) --> bin(xfrm_pol_inexact_bin)
  table(resizable<br />hashtable) --> bin2(...)
  bin --> rbtree_dst(root_d)
  bin --> rbtree_src(root_s)
  bin --> list_anyany((any;any))
  rbtree_src --> node_src1(( ))
  rbtree_src --> node_src2(( ))
  node_src1 --> node_src3(( ))
  node_src1 --> node_src4(( ))
  node_src2 --> node_src5(( ))
  node_src2 --> node_src6(( ))
  node_src6 --> list_srcany((src;any))
  rbtree_dst --> node_dst1(( ))
  rbtree_dst --> node_dst2(( ))
  node_dst1 --> node_dst3(( ))
  node_dst1 --> node_dst4(( ))
  node_dst2 --> node_dst5(( ))
  node_dst2 --> node_dst6(( ))
  node_dst5 --> rbtree_dstsrc(root)
  node_dst5 --> list_dstany((any;dst))
  rbtree_dstsrc --> node_dstsrc1(( ))
  rbtree_dstsrc --> node_dstsrc2(( ))
  node_dstsrc1 --> node_dstsrc3(( ))
  node_dstsrc1 --> node_dstsrc4(( ))
  node_dstsrc2 --> node_dstsrc5(( ))
  node_dstsrc2 --> node_dstsrc6(( ))
  node_dstsrc6 --> list_dstsrc((src;dst))