// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v2alpha1

// CiliumBGPFamilyApplyConfiguration represents a declarative configuration of the CiliumBGPFamily type for use
// with apply.
type CiliumBGPFamilyApplyConfiguration struct {
	Afi  *string `json:"afi,omitempty"`
	Safi *string `json:"safi,omitempty"`
}

// CiliumBGPFamilyApplyConfiguration constructs a declarative configuration of the CiliumBGPFamily type for use with
// apply.
func CiliumBGPFamily() *CiliumBGPFamilyApplyConfiguration {
	return &CiliumBGPFamilyApplyConfiguration{}
}

// WithAfi sets the Afi field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Afi field is set to the value of the last call.
func (b *CiliumBGPFamilyApplyConfiguration) WithAfi(value string) *CiliumBGPFamilyApplyConfiguration {
	b.Afi = &value
	return b
}

// WithSafi sets the Safi field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Safi field is set to the value of the last call.
func (b *CiliumBGPFamilyApplyConfiguration) WithSafi(value string) *CiliumBGPFamilyApplyConfiguration {
	b.Safi = &value
	return b
}
