#!/usr/bin/env bash
# SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause)
# Copyright Authors of Cilium

echo -e "\ttest___builtin_$1_single(1);"
for (( j = 2; j <= "$2"; j += 2 )); do
	echo -e "\ttest___builtin_$1_single($j);"
done
