// Code generated by dpgen. DO NOT EDIT.

// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

package latest

import "fmt"

func NewBPFLXC(node *Node) *BPFLXC {
	r := &BPFLXC{}
	r.AllowIcmpFragNeeded = false
	r.DeviceMtu = 0x5dc
	r.EnableArpResponder = false
	r.EnableExtendedIpProtocols = false
	r.EnableIcmpRule = false
	r.EnableIpv4Fragments = false
	r.EnableIpv6Fragments = false
	r.EnableLrp = false
	r.EnableNetkit = false
	r.EnableNoServiceEndpointsRoutable = false
	r.EnablePolicyAccounting = false
	r.EnableRemoteNodeMasquerade = false
	r.EndpointId = 0x0
	r.EndpointIpv4 = []byte{0x0, 0x0, 0x0, 0x0}
	r.EndpointIpv6 = []byte{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}
	r.EndpointNetnsCookie = 0x0
	r.EphemeralMin = 0x0
	r.FibTableId = 0x0
	r.HostEpId = 0x0
	r.HybridRoutingEnabled = false
	r.InterfaceIfindex = 0x0
	r.InterfaceMac = []byte{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}
	r.NatIpv4Masquerade = []byte{0x0, 0x0, 0x0, 0x0}
	r.NatIpv6Masquerade = []byte{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}
	r.PolicyVerdictLogFilter = 0x0
	r.ProxyRedirectViaCiliumNet = false
	r.SecurityLabel = 0x0
	r.TunnelPort = 0x0
	r.TunnelProtocol = 0x0
	r.VtepMask = 0x0
	r.Node = node
	return r
}
var fieldSizesBPFLXC = map[string]int{
	"allow_icmp_frag_needed": 1,
	"device_mtu": 2,
	"enable_arp_responder": 1,
	"enable_extended_ip_protocols": 1,
	"enable_icmp_rule": 1,
	"enable_ipv4_fragments": 1,
	"enable_ipv6_fragments": 1,
	"enable_lrp": 1,
	"enable_netkit": 1,
	"enable_no_service_endpoints_routable": 1,
	"enable_policy_accounting": 1,
	"enable_remote_node_masquerade": 1,
	"endpoint_id": 2,
	"endpoint_ipv4": 4,
	"endpoint_ipv6": 16,
	"endpoint_netns_cookie": 8,
	"ephemeral_min": 2,
	"fib_table_id": 4,
	"host_ep_id": 2,
	"hybrid_routing_enabled": 1,
	"interface_ifindex": 4,
	"interface_mac": 8,
	"nat_ipv4_masquerade": 4,
	"nat_ipv6_masquerade": 16,
	"policy_verdict_log_filter": 4,
	"proxy_redirect_via_cilium_net": 1,
	"security_label": 4,
	"tunnel_port": 2,
	"tunnel_protocol": 1,
	"vtep_mask": 4,
}

func (c *BPFLXC) SizeOf(fieldName string) int {
	if c.Node.SizeOf(fieldName) != 0 {
		return c.Node.SizeOf(fieldName)
	}
	return fieldSizesBPFLXC[fieldName]
}

func (c *BPFLXC) Map() (map[string]any, error) {
	result := make(map[string]any)
	mapNode, err := c.Node.Map()
	if err != nil {
		return nil, fmt.Errorf("Node: %w", err)
	}
	for name, val := range mapNode {
		if _, ok := result[name]; ok {
			return nil, fmt.Errorf("Node: %s exists in two embedded types", name)
		}
		result[name] = val
	}
	result["allow_icmp_frag_needed"] = c.AllowIcmpFragNeeded
	DeviceMtu := uint16(c.DeviceMtu)
	if (uint32(DeviceMtu) != c.DeviceMtu) {
		return nil, fmt.Errorf("DeviceMtu must fit into a uint16 (value = %d)", c.DeviceMtu)
	}
	result["device_mtu"] = DeviceMtu
	result["enable_arp_responder"] = c.EnableArpResponder
	result["enable_extended_ip_protocols"] = c.EnableExtendedIpProtocols
	result["enable_icmp_rule"] = c.EnableIcmpRule
	result["enable_ipv4_fragments"] = c.EnableIpv4Fragments
	result["enable_ipv6_fragments"] = c.EnableIpv6Fragments
	result["enable_lrp"] = c.EnableLrp
	result["enable_netkit"] = c.EnableNetkit
	result["enable_no_service_endpoints_routable"] = c.EnableNoServiceEndpointsRoutable
	result["enable_policy_accounting"] = c.EnablePolicyAccounting
	result["enable_remote_node_masquerade"] = c.EnableRemoteNodeMasquerade
	EndpointId := uint16(c.EndpointId)
	if (uint32(EndpointId) != c.EndpointId) {
		return nil, fmt.Errorf("EndpointId must fit into a uint16 (value = %d)", c.EndpointId)
	}
	result["endpoint_id"] = EndpointId
	if (len(c.EndpointIpv4) != 4) {
		return nil, fmt.Errorf("EndpointIpv4 must be 4 bytes (got %d)", len(c.EndpointIpv4))
	}
	result["endpoint_ipv4"] = c.EndpointIpv4
	if (len(c.EndpointIpv6) != 16) {
		return nil, fmt.Errorf("EndpointIpv6 must be 16 bytes (got %d)", len(c.EndpointIpv6))
	}
	result["endpoint_ipv6"] = c.EndpointIpv6
	result["endpoint_netns_cookie"] = c.EndpointNetnsCookie
	EphemeralMin := uint16(c.EphemeralMin)
	if (uint32(EphemeralMin) != c.EphemeralMin) {
		return nil, fmt.Errorf("EphemeralMin must fit into a uint16 (value = %d)", c.EphemeralMin)
	}
	result["ephemeral_min"] = EphemeralMin
	result["fib_table_id"] = c.FibTableId
	HostEpId := uint16(c.HostEpId)
	if (uint32(HostEpId) != c.HostEpId) {
		return nil, fmt.Errorf("HostEpId must fit into a uint16 (value = %d)", c.HostEpId)
	}
	result["host_ep_id"] = HostEpId
	result["hybrid_routing_enabled"] = c.HybridRoutingEnabled
	result["interface_ifindex"] = c.InterfaceIfindex
	if (len(c.InterfaceMac) != 8) {
		return nil, fmt.Errorf("InterfaceMac must be 8 bytes (got %d)", len(c.InterfaceMac))
	}
	result["interface_mac"] = c.InterfaceMac
	if (len(c.NatIpv4Masquerade) != 4) {
		return nil, fmt.Errorf("NatIpv4Masquerade must be 4 bytes (got %d)", len(c.NatIpv4Masquerade))
	}
	result["nat_ipv4_masquerade"] = c.NatIpv4Masquerade
	if (len(c.NatIpv6Masquerade) != 16) {
		return nil, fmt.Errorf("NatIpv6Masquerade must be 16 bytes (got %d)", len(c.NatIpv6Masquerade))
	}
	result["nat_ipv6_masquerade"] = c.NatIpv6Masquerade
	result["policy_verdict_log_filter"] = c.PolicyVerdictLogFilter
	result["proxy_redirect_via_cilium_net"] = c.ProxyRedirectViaCiliumNet
	result["security_label"] = c.SecurityLabel
	TunnelPort := uint16(c.TunnelPort)
	if (uint32(TunnelPort) != c.TunnelPort) {
		return nil, fmt.Errorf("TunnelPort must fit into a uint16 (value = %d)", c.TunnelPort)
	}
	result["tunnel_port"] = TunnelPort
	TunnelProtocol := uint8(c.TunnelProtocol)
	if (uint32(TunnelProtocol) != c.TunnelProtocol) {
		return nil, fmt.Errorf("TunnelProtocol must fit into a uint8 (value = %d)", c.TunnelProtocol)
	}
	result["tunnel_protocol"] = TunnelProtocol
	result["vtep_mask"] = c.VtepMask
	return result, nil
}
