name: Set runtime image
description: Set runtime image version for building images
inputs:
  repository:
    description: 'Repository value used to check the image provenance'
    required: true
  path:
    description: 'Path to the file containing the runtime image reference'
    default: '${{ github.action_path }}/runtime-image.txt'
runs:
  using: composite
  steps:
    - shell: bash
      name: Read runtime variable from file safely
      run: |
        CILIUM_RUNTIME_IMAGE=$(cat "${{ inputs.path }}" | tr '\n' ' ' | sed 's/"/\\"/g')
        # Verify provenance of the image with repository passed in parameter
        if [[ $CILIUM_RUNTIME_IMAGE != ${{ inputs.repository }}* ]]; then
          echo "Unknown provenance, runtime image should come from ${{ inputs.repository }}"
          exit 1
        fi
        # Set the runtime image into github env once everything is verified
        echo "CILIUM_RUNTIME_IMAGE=$CILIUM_RUNTIME_IMAGE" >> "$GITHUB_ENV"