// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

package externalgroups

import (
	"encoding/json"
	"strings"
	"time"

	"github.com/cilium/statedb"
	"github.com/cilium/statedb/index"
	"github.com/cilium/statedb/part"

	apiv2 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2"
	"github.com/cilium/cilium/pkg/policy/api"
)

// ExternalGroup is information about a policy External Group
// (i.e. toGroups / fromGroups). It is a set of IPs provided
// by an external integration. Those IPs should be synchronized
// to a CiliumCIDRGroup.
type ExternalGroup struct {
	// ID is a unique identifier for this group.
	// This is currently the SHA256 hash of the group's JSON definition.
	// (We have to syntheize this as groups have no primary key)
	ID string

	// ExtGroup is the group definition
	// immutable!
	ExtGroup *api.Groups

	// CCGName is the name of the created CiliumCIDRGroup.
	// (It is generated by the APIServer so its useful to separate this for indexing purposes)
	CCGName string

	// CCG is the resulting CiliumCIDRGroup for this ExternalGroup
	CCG *apiv2.CiliumCIDRGroup

	// NextRefresh is the soft deadline for refreshing this group.
	NextRefresh time.Time

	// Owners is the set of upstream resources that reference this external group
	Owners part.Set[Owner]
}

func (g *ExternalGroup) ShallowCopy() *ExternalGroup {
	out := *g
	return &out
}

// Owner is an upstream resource that references an external group.
type Owner struct {
	Group     string // k8s api group
	Kind      string
	Namespace string
	Name      string
}

func (r Owner) String() string {
	var b strings.Builder
	b.WriteString(r.Group)
	b.WriteRune(':')
	b.WriteString(r.Kind)
	b.WriteRune('/')
	b.WriteString(r.Namespace)
	b.WriteRune('/')
	b.WriteString(r.Name)
	return b.String()
}

func (*ExternalGroup) TableHeader() []string {
	return []string{
		"ID",
		"ExternalGroup",
		"CCG Name",
		"NextRefresh",
		"Owners",
	}
}

func (eg *ExternalGroup) TableRow() []string {
	groupDef, err := json.Marshal(eg.ExtGroup)
	if err != nil {
		// unreachable, came from JSON!
		return nil
	}

	ccgName := "<nil>"
	if eg.CCG != nil {
		ccgName = eg.CCG.Name
	}

	owners := make([]string, 0, eg.Owners.Len())
	for owner := range eg.Owners.All() {
		owners = append(owners, owner.String())
	}

	return []string{
		eg.ID,
		string(groupDef),
		ccgName,
		eg.NextRefresh.Format(time.RFC3339),
		strings.Join(owners, ", "),
	}
}

const (
	ExternalGroupTableName = "policy-external-group-to-ccg"
)

var (
	egIDIndex = statedb.Index[*ExternalGroup, string]{
		Name: "id",
		FromObject: func(o *ExternalGroup) index.KeySet {
			return index.NewKeySet(index.String(o.ID))
		},
		FromKey:    index.String,
		FromString: index.FromString,
		Unique:     true,
	}

	ExternalGroupByID = egIDIndex.Query

	ccgIndex = statedb.Index[*ExternalGroup, string]{
		Name: "ccg",
		FromObject: func(o *ExternalGroup) index.KeySet {
			return index.NewKeySet(index.String(o.CCGName))
		},
		FromKey:    index.String,
		FromString: index.FromString,
		Unique:     false,
	}

	ExternalGroupByCCG = ccgIndex.Query

	ownerIndex = statedb.Index[*ExternalGroup, Owner]{
		Name: "owner",
		FromObject: func(o *ExternalGroup) index.KeySet {
			return index.Set(o.Owners)
		},
		FromKey: index.Stringer[Owner],
		Unique:  false,
	}

	ExternalGroupByOwner = ownerIndex.Query
)

func NewExternalGroupTable(db *statedb.DB) (statedb.RWTable[*ExternalGroup], error) {
	return statedb.NewTable(
		db,
		ExternalGroupTableName,
		egIDIndex,
		ownerIndex, ccgIndex,
	)
}

func init() {
	// teach part.Set how to turn an Owner in to bytes
	part.RegisterKeyType(
		func(r Owner) []byte { return []byte(r.String()) },
	)
}
