# CiliumEnvoyConfig to proxy any incoming TCP connection on the listener to the
# configured destination, but only if destination port is 80. Connenctions with
# other destination ports are accepted (downstream connection established), but
# not connected anywhere in upstream, so the downstream connection is closed.
# If the connection was a TLS connection, it will get a TLS error as the handshake
# cannot be finished.
apiVersion: cilium.io/v2
kind: CiliumClusterwideEnvoyConfig
metadata:
  name: client-egress-to-fqdns-proxy-{{trimSuffix .ExternalTarget "."}}
spec:
  resources:
  - "@type": type.googleapis.com/envoy.config.listener.v3.Listener
    name: proxy-{{trimSuffix .ExternalTarget "."}}-listener
    filter_chains:
    - filter_chain_match:
        destination_port: 80
      filters:
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: test-listener
          cluster: proxy-{{trimSuffix .ExternalTarget "."}}-cluster
  - '@type': type.googleapis.com/envoy.config.cluster.v3.Cluster
    connectTimeout: 55s
    name: proxy-{{trimSuffix .ExternalTarget "."}}-cluster
    type: ORIGINAL_DST
    lb_policy: CLUSTER_PROVIDED

---

apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: client-egress-to-fqdns-proxy-{{trimSuffix .ExternalTarget "."}}
spec:
  endpointSelector:
    matchLabels:
      kind: client
  egress:
  - toFQDNs:
    - matchName: {{trimSuffix .ExternalTarget "."}}
    toPorts:
    - listener:
        envoyConfig:
          kind: CiliumClusterwideEnvoyConfig
          name: client-egress-to-fqdns-proxy-{{trimSuffix .ExternalTarget "."}}
        name: proxy-{{trimSuffix .ExternalTarget "."}}-listener
        priority: 1
      ports:
      - port: "0"
        protocol: TCP
