{{$actionName := .actionName}}
{{$tuningSet := .tuningSet}}

{{$image := .image}}
{{$ciliumNamespace := .ciliumNamespace}}
{{$ciliumConfigMapName := .ciliumConfigMapName}}

{{if eq $actionName "create"}}

steps:
- module:
    path: ./modules/rbac.yaml
    params:
      replicas: 1
      actionName: create
      tuningSet: {{$tuningSet}}
      serviceAccountName: kwok
      serviceAccountNamespace: {{$ciliumNamespace}}

- name: {{$actionName}} kwok-controller
  phases:
  - namespaceList: [{{$ciliumNamespace}}]
    replicasPerNamespace: 1
    tuningSet: {{$tuningSet}}
    objectBundle:
    - basename: kwok
      objectTemplatePath: ./manifests/kwok-pod.yaml
      templateFillMap:
        image: {{$image}}
        ciliumNamespace: {{$ciliumNamespace}}
        ciliumConfigMapName: {{$ciliumConfigMapName}}
        svcAccountRefName: kwok

- name: Waiting for kwok-controller to be running
  measurements:
  - identifier: WaitForKwokControllerRunning
    method: WaitForRunningPods
    params:
      desiredPodCount: 1
      namespace: {{$ciliumNamespace}}
      labelSelector: app.kubernetes.io/name=kwok-controller
      timeout: 2m

{{else}}

# During deletion kwok controller needs to be stopped before cleaning
# up the RBAC.

steps:
- name: Delete kwok-controller
  phases:
  - namespaceList: [{{$ciliumNamespace}}]
    replicasPerNamespace: 0
    tuningSet: {{$tuningSet}}
    objectBundle:
    - basename: kwok
      objectTemplatePath: ./manifests/kwok-pod.yaml
      templateFillMap:
        image: {{$image}}
        ciliumNamespace: {{$ciliumNamespace}}
        ciliumConfigMapName: {{$ciliumConfigMapName}}
        svcAccountRefName: kwok

- module:
    path: ./modules/rbac.yaml
    params:
      replicas: 0
      actionName: delete
      tuningSet: {{$tuningSet}}
      serviceAccountName: kwok
      serviceAccountNamespace: {{$ciliumNamespace}}

{{end}}

