//go:build kubernetes_protomessage_one_more_release
// +build kubernetes_protomessage_one_more_release

// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by go-to-protobuf. DO NOT EDIT.

package v1

func (*CustomResourceDefinition) ProtoMessage() {}

func (*CustomResourceDefinitionList) ProtoMessage() {}

func (*CustomResourceSubresourceScale) ProtoMessage() {}

func (*CustomResourceSubresourceStatus) ProtoMessage() {}

func (*CustomResourceSubresources) ProtoMessage() {}

func (*CustomResourceValidation) ProtoMessage() {}

func (*ExternalDocumentation) ProtoMessage() {}

func (*JSON) ProtoMessage() {}

func (*JSONSchemaProps) ProtoMessage() {}

func (*JSONSchemaPropsOrArray) ProtoMessage() {}

func (*JSONSchemaPropsOrBool) ProtoMessage() {}

func (*JSONSchemaPropsOrStringArray) ProtoMessage() {}

func (*ValidationRule) ProtoMessage() {}
