name: Ariane scheduled workflows

on:
  # Run every 1 hours
  # Tests are only run when current GITHUB_RUN_NUMBER % 6 corresponds to the branch runModulo value in the matrix,
  # meaning we run every branch roughly every six hours.
  # We run this at :30, to avoid running at the same time as the default branch scheduled workflows (that mostly run
  # at the top of the hour).
  schedule:
    - cron: '30 */1 * * *'


permissions:
  # To be able to access the repository with actions/checkout
  contents: read
  # To trigger workflows via workflow_dispatch
  actions: write

jobs:
  ariane-scheduled:
    name: Run Scheduled Workflows
    strategy:
      fail-fast: false
      matrix:
        include:
          # runModulo (range [0, 5]) should be different for every branch
          - branch: 'v1.18'
            runModulo: 1
          - branch: 'v1.19'
            runModulo: 2
          - branch: 'v1.20'
            runModulo: 3
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ matrix.branch }}
          persist-credentials: false

      - name: Manually run Ariane workflows from the branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Current date time: $(date --utc --rfc-3339=seconds)"
          echo "Current run number: $GITHUB_RUN_NUMBER"

          if (( GITHUB_RUN_NUMBER % 6 == ${{ matrix.runModulo }} )); then
            echo "Running scheduled workflows for branch ${{ matrix.branch }}"
          else
            echo "Skipping scheduled workflows for branch ${{ matrix.branch }}"
            exit 0
          fi

          REF="${{ matrix.branch }}"
          SHA=$(git rev-parse ${REF})
          # /test for 1.18 branch and lower
          # /test\s* for 1.19 branch and higher
          readarray workflows < <((
            yq '.triggers["/test"].workflows[]' .github/ariane-config.yaml
            yq '.triggers["/test\s*"].workflows[]' .github/ariane-config.yaml
            yq '.schedule.nightly.workflows[]' .github/ariane-config.yaml
          ) | sort -u)

          for workflow in "${workflows[@]}"; do
            echo triggering ${workflow}
            gh workflow run ${workflow} \
              --ref ${REF} \
              -f PR-number=${REF/./-} \
              -f context-ref=${REF} \
              -f SHA=${SHA}
          done
