name: Common Post Jobs

on:
  workflow_call:
    inputs:
      context-ref:
        required: true
        type: string
      results:
        required: true
        type: string
      sha:
        required: true
        type: string

permissions:
  contents: read
  actions: read
  statuses: write

jobs:
  merge-upload:
    if: ${{ always() }}
    name: Merge and Upload Artifacts
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      actions: read
    steps:
      - name: Checkout context ref (trusted)
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.context-ref }}
          persist-credentials: false

      - name: Merge JUnits
        uses: ./.github/actions/merge-artifacts
        with:
          name: cilium-junits
          pattern: cilium-junits-*
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Features tested
        uses: ./.github/actions/merge-artifacts
        with:
          name: features-tested
          pattern: features-tested-*
          token: ${{ secrets.GITHUB_TOKEN }}
          separate-directories: true

  update-status:
    if: ${{ always() }}
    name: Update commit and workflow results
    runs-on: ubuntu-24.04
    permissions:
      statuses: write
    steps:
      - name: Aggregate results
        id: aggregate-results
        run: |
          set -eu
          set -o pipefail

          # Convert a job result into a commit status.
          #
          # https://docs.github.com/en/actions/reference/workflows-and-actions/contexts?apiVersion=2026-03-10#jobs-context
          # https://docs.github.com/en/rest/commits/statuses?apiVersion=2026-03-10#create-a-commit-status--parameters
          declare -A result_to_status=(
            [cancelled]="failure"
            [failure]="failure"
            [skipped]="success"
            [success]="success"
          )

          # Check for unrecognized input.
          for result in ${{ inputs.results }}; do
            status="${result_to_status[$result]}"
            if [ "$status" != 'success' ] && [ "$status" != 'failure' ]; then
              # Should not occur
              echo "status=error" >> "$GITHUB_OUTPUT"
              echo "::error::Workflow failed because job results could not be processed"
              echo "::error::$results"
              exit 1
            fi
          done

          # Check for any failures in the results and emit failure.
          for result in ${{ inputs.results }}; do
            status="${result_to_status[$result]}"
            if [ "$status" = 'failure' ]; then
              echo "status=$status" >> "$GITHUB_OUTPUT"
              exit 0
            fi
          done

          echo "status=success" >> "$GITHUB_OUTPUT"

      - name: Set final commit status
        if: ${{ always() }}
        uses: cilium/cilium/.github/actions/set-commit-status@main # main
        with:
          sha: ${{ inputs.sha }}
          status: ${{ steps.aggregate-results.outputs.status }}

      - name: Fail job if result is failure
        # Besides reporting in the commit SHA if the test was or not successful,
        # we should also report it in the workflow itself. This will allow to
        # store the failure rate of the workflow on OpenSearch, instead of
        # marking it as successful.
        if: ${{ steps.aggregate-results.outputs.status != 'success' }}
        run: |
          echo "::error::Workflow failed because one or more jobs failed"
          exit 1
