name: Conformance Kind Envoy Embedded

# Any change in triggers needs to be reflected in the concurrency group.
on:
  workflow_dispatch:
    inputs:
      PR-number:
        description: "Pull request number."
        required: true
      UID:
        description: "A second number, to differentiate multiple runs of the same workflow by the same PR"
        required: false
        default: 1
      context-ref:
        description: "Context in which the workflow runs. If PR is from a fork, will be the PR target branch (general case). If PR is NOT from a fork, will be the PR branch itself (this allows committers to test changes to workflows directly from PRs)."
        required: true
      SHA:
        description: "SHA under test (head of the PR branch)."
        required: true
      base-SHA:
        description: "SHA of the base branch (target branch of the PR)."
        required: false
      extra-args:
        description: "[JSON object] Arbitrary arguments passed from the trigger comment via regex capture group. Parse with 'fromJson(inputs.extra-args).argName' in workflow."
        required: false
        default: '{}'

  push:
    branches:
      - main
      - ft/main/**
    paths-ignore:
      - 'Documentation/**'
      - 'test/**'

# By specifying the access of one of the scopes, all of those that are not
# specified are set to 'none'.
permissions:
  # To read actions state with cilium/workflow-telemetry-action
  actions: read
  # To be able to access the repository with actions/checkout
  contents: read
  # To allow retrieving information from the PR API
  pull-requests: read
  # To be able to set commit status
  statuses: write
  # To be able to request the JWT from GitHub's OIDC provider
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ inputs.PR-number || github.event.after }}
  cancel-in-progress: true

env:
  kind_config: .github/kind-config-dual.yaml

jobs:
  echo-inputs:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    name: Echo Workflow Dispatch Inputs
    runs-on: ubuntu-24.04
    steps:
      - name: Echo Workflow Dispatch Inputs
        run: |
          echo '${{ tojson(inputs) }}'

  commit-status-start:
    name: Commit Status Start
    runs-on: ubuntu-24.04
    steps:
      - name: Set initial commit status
        uses: cilium/cilium/.github/actions/set-commit-status@main # main
        with:
          sha: ${{ inputs.SHA || github.sha }}

  installation-and-connectivity:
    name: "Installation and Connectivity Test (${{ matrix.name }})"
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: default (ads)
          extra-helm-set: ""
        - name: split
          extra-helm-set: "--helm-set=envoy.xdsMode=split"
    env:
      job_name: "Installation and Connectivity Test (${{ matrix.name }})"
    steps:
      - name: Collect Workflow Telemetry
        uses: cilium/workflow-telemetry-action@b1a318f80a08acede58027afe1455d037379966f # v2.2.0
        with:
          comment_on_pr: false

      - name: Checkout code (TRUSTED)
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          ref: ${{ inputs.context-ref || github.sha}}

      - name: Set Environment Variables
        uses: ./.github/actions/set-env-variables

      - name: Get Cilium's default values
        id: default_vars
        uses: ./.github/actions/helm-default
        with:
          image-tag: ${{ inputs.SHA || github.sha }}
          registry_host: ${{ vars.DOCKER_READ_HOST }}
          registry_organization: ${{ vars.DOCKER_READ_ORG }}
          image-pull-secret: "cilium-registry"
          chart-dir: 'untrusted/install/kubernetes/cilium'

      - name: Add external docker network
        uses: ./.github/actions/kind-external-network
        id: external_network

      - name: Create kind cluster
        uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1.14.0
        with:
          version: ${{ env.KIND_VERSION }}
          node_image: ${{ env.KIND_K8S_IMAGE }}
          kubectl_version: ${{ env.KIND_K8S_VERSION }}
          config: ${{ env.kind_config }}
          wait: 0 # The control-plane never becomes ready, since no CNI is present

      - name: Add external targets to kind cluster
        uses: ./.github/actions/kind-external-targets
        id: external_targets
        with:
          kind_network: ${{ steps.external_network.outputs.kind_network }}
          ipv4_external_target: ${{ steps.external_network.outputs.ipv4_external_target }}
          ipv4_other_external_target: ${{ steps.external_network.outputs.ipv4_other_external_target }}
          ipv6_external_target: ${{ steps.external_network.outputs.ipv6_external_target }}
          ipv6_other_external_target: ${{ steps.external_network.outputs.ipv6_other_external_target }}

      - name: Get connectivity test flags
        id: e2e_config
        uses: ./.github/actions/cli-test-config
        with:
          hubble: false
          include-unsafe-tests: true
          test-concurrency: 5
          external-cidr: ${{ steps.external_network.outputs.ipv4_external_cidr }}
          external-cidrv6: ${{ steps.external_network.outputs.ipv6_external_cidr }}
          external-ip: ${{ steps.external_network.outputs.ipv4_external_target }}
          external-ipv6: ${{ steps.external_network.outputs.ipv6_external_target }}
          external-other-ip: ${{ steps.external_network.outputs.ipv4_other_external_target }}
          external-other-ipv6: ${{ steps.external_network.outputs.ipv6_other_external_target }}
          external-other-target: ${{ steps.external_targets.outputs.other_external_target_name }}
          external-target: ${{ steps.external_targets.outputs.external_target_name }}

      - name: Set up job variables
        id: vars
        run: |
          # Note: On Kind, we install Cilium with HostPort (portmap CNI chaining) enabled,
          # to ensure coverage of that feature in cilium connectivity test
          CILIUM_INSTALL_DEFAULTS="${{ steps.default_vars.outputs.cilium_install_defaults }} \
            --helm-set=hubble.relay.enabled=true
            --helm-set=cni.chainingMode=portmap \
            --helm-set-string=kubeProxyReplacement=true \
            --helm-set=loadBalancer.l7.backend=envoy \
            --helm-set=tls.readSecretsOnlyFromSecretsNamespace=true \
            --helm-set=tls.secretSync.enabled=true \
            --helm-set=envoy.enabled=false \
            --helm-set=ipv6.enabled=true \
            ${{ matrix.extra-helm-set }} \
            --wait=false"
          CONNECTIVITY_TEST_DEFAULTS="${{ steps.e2e_config.outputs.test_flags }} \
            --external-target-ca-namespace=external-target-secrets --external-target-ca-name=custom-ca \
            --external-target-ipv6-capable"
          echo cilium_install_defaults=${CILIUM_INSTALL_DEFAULTS} >> $GITHUB_OUTPUT
          echo "test default: ${CONNECTIVITY_TEST_DEFAULTS}"
          echo connectivity_test_defaults=${CONNECTIVITY_TEST_DEFAULTS} >> $GITHUB_OUTPUT
          echo sha=${{ steps.default_vars.outputs.sha }} >> $GITHUB_OUTPUT

      - name: Install Cilium CLI
        uses: cilium/cilium-cli@e391e739db83a8b888ecf18786af6853c51a0c58 # v0.19.5
        with:
          skip-build: ${{ env.CILIUM_CLI_SKIP_BUILD }}
          image-repo: ${{ env.CILIUM_CLI_IMAGE_REPO }}
          image-tag: ${{ steps.vars.outputs.sha }}
          repository: ${{ env.CILIUM_CLI_RELEASE_REPO }}
          release-version: ${{ env.CILIUM_CLI_VERSION }}

      - name: Create imagePullSecret
        run: |
          kubectl create secret docker-registry cilium-registry \
            --namespace kube-system \
            --docker-server=${{ vars.DOCKER_READ_HOST }} \
            --docker-username="${{ vars.DOCKER_READ_USERNAME }}" \
            --docker-password="${{ secrets.DOCKER_READ_PASSWORD }}"

      - name: Login to docker registry for image wait
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ${{ vars.DOCKER_READ_HOST}}
          username: ${{ vars.DOCKER_READ_USERNAME}}
          password: ${{ secrets.DOCKER_READ_PASSWORD }}

      - name: Wait for images to be available
        timeout-minutes: 30
        shell: bash
        run: |
          for image in cilium-ci operator-generic-ci hubble-relay-ci ; do
            until docker manifest inspect ${{ vars.DOCKER_READ_HOST }}/${{ vars.DOCKER_READ_ORG }}/$image:${{ steps.vars.outputs.sha }} &> /dev/null; do sleep 45s; done
          done

      # Warning: since this is a privileged workflow, subsequent workflow job
      # steps must take care not to execute untrusted code.
      - name: Checkout pull request branch (NOT TRUSTED)
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ steps.vars.outputs.sha }}
          persist-credentials: false
          path: untrusted
          sparse-checkout: |
            install/kubernetes/cilium

      - name: Install Cilium
        id: install-cilium
        run: |
          cilium install ${{ steps.vars.outputs.cilium_install_defaults }}

      - name: Wait for Cilium status to be ready
        run: |
          cilium status --wait --interactive=false
          kubectl -n kube-system get pods

      - name: Make JUnit report directory
        run: |
          mkdir -p cilium-junits

      - name: Run connectivity test
        id: run-tests
        run: |
          cilium connectivity test ${{ steps.vars.outputs.connectivity_test_defaults }} \
            --curl-parallel 3 \
            --junit-file "cilium-junits/${{ env.job_name }}.xml" --junit-property github_job_step="Run connectivity test"

      - name: Features tested
        uses: ./.github/actions/feature-status
        with:
          title: "Summary of all features tested"
          json-filename: "${{ env.job_name }}"

      - name: Install Cilium with secret sync disabled
        id: install-cilium-secret-sync-disabled
        run: |
          helm upgrade cilium untrusted/install/kubernetes/cilium \
            --namespace kube-system \
            --reuse-values \
            --set=tls.readSecretsOnlyFromSecretsNamespace=false \
            --set=tls.secretSync.enabled=false

          kubectl -n kube-system rollout restart ds/cilium deployment/cilium-operator
          cilium status --wait --interactive=false --wait-duration=10m
          kubectl -n kube-system get pods

      - name: Run L7 related connectivity test
        run: |
          cilium connectivity test ${{ steps.vars.outputs.connectivity_test_defaults }} \
            --curl-parallel 3 \
            --junit-file "cilium-junits/${{ env.job_name }}-without-secret-sync.xml" \
            --junit-property github_job_step="Run connectivity test with secret sync disabled" \
            --test="l7|sni|check-log-errors"

      - name: Features tested
        uses: ./.github/actions/feature-status
        with:
          title: "Summary of all features tested"
          json-filename: "${{ env.job_name }}-without-secret-sync"

      - name: Run common post steps
        if: ${{ always() && steps.install-cilium.outcome != 'skipped' }}
        uses: ./.github/actions/post-logic
        with:
          artifacts_suffix: "${{ env.job_name }}"
          job_status: "${{ job.status }}"
          capture_features_tested: false

  merge-upload-and-status:
    name: Merge Upload and Status
    if: ${{ always() }}
    needs: installation-and-connectivity
    uses: ./.github/workflows/common-post-jobs.yaml
    secrets: inherit
    with:
      context-ref: ${{ inputs.context-ref || github.sha }}
      sha: ${{ inputs.SHA || github.sha }}
      success: ${{ needs.installation-and-connectivity.result == 'success' }}
