name: Delete EKS Clusters

on:
  workflow_dispatch:
    inputs:
      cluster_name:
        description: "EKS cluster name to delete"
        required: true
        type: string
      region:
        description: "AWS region where the cluster is located"
        required: true
        type: string

permissions:
  id-token: write
  contents: read

env:
  # renovate: datasource=github-releases depName=eksctl-io/eksctl
  eksctl_version: v0.225.0

jobs:
  delete-cluster:
    name: Delete EKS Cluster
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    continue-on-error: true
    steps:
      - name: Checkout context ref (trusted)
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install eksctl CLI
        run: |
          curl -LO "https://github.com/eksctl-io/eksctl/releases/download/${{ env.eksctl_version }}/eksctl_$(uname -s)_amd64.tar.gz"
          sudo tar -xzvf "eksctl_$(uname -s)_amd64.tar.gz" -C /usr/bin
          rm "eksctl_$(uname -s)_amd64.tar.gz"

      - name: Set up AWS CLI credentials
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          role-to-assume: ${{ secrets.AWS_PR_ASSUME_ROLE }}
          aws-region: ${{ inputs.region }}

      - name: Get runner public IP
        id: get-runner-ip
        uses: ./.github/actions/get-runner-ip
        with:
          source: https://checkip.amazonaws.com
          parsing: text

      - name: Delete EKS cluster
        run: |
          eksctl utils update-cluster-vpc-config --cluster "${{ inputs.cluster_name }}" \
            --public-access-cidrs="${{ steps.get-runner-ip.outputs.cidr }}" \
            --public-access=true --private-access=true --approve || \
          eksctl delete cluster --name "${{ inputs.cluster_name }}" --region ${{ inputs.region }}
        shell: bash {0} # Disable default fail-fast behaviour

