name: Hubble CLI tests

on:
  pull_request:
    paths-ignore:
      - 'cilium-cli/**'
      - 'Documentation/**'
      - 'test/**'
  # The push event is only used to recreate the golang cache for hubble-cli
  push:
    branches:
      - v1.17
      - ft/v1.17/**
    paths-ignore:
      - 'cilium-cli/**'
      - 'Documentation/**'
      - 'test/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

jobs:
  build-hubble-cli-release-binaries:
    name: Build Hubble CLI release binaries
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          cache: false
          # renovate: datasource=golang-version depName=go
          go-version: 1.25.9

      # Load Golang cache build from GitHub
      - name: Load hubble-cli Golang cache build from GitHub
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        id: cache
        with:
          path: /tmp/.cache/hubble-cli
          key: ${{ runner.os }}-go-hubble-cli-cache-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-hubble-cli-cache-
            ${{ runner.os }}-go-

      - name: Create cache directories if they don't exist
        if: ${{ steps.go-cache.outputs.cache-hit != 'true' }}
        shell: bash
        run: |
          mkdir -p /tmp/.cache/hubble-cli/.cache/go-build
          mkdir -p /tmp/.cache/hubble-cli/pkg

      - name: Build hubble CLI release binaries
        if: ${{ github.event_name != 'push' || ( github.event_name == 'push' && steps.go-cache.outputs.cache-hit != 'true' ) }}
        env:
          GOCACHE: "/tmp/.cache/hubble-cli/.cache/go-build"
          GOMODCACHE: "/tmp/.cache/hubble-cli/pkg"
        run: |
          make -C hubble local-release
