name: Validate Renovate configuration

on:
  pull_request:
    paths:
      # Run on any renovate.json5, not just .github/renovate.json5
      - '**renovate.json5'

jobs:
  validate:
    name: Validate Renovate configuration
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout configuration
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      # this step uses latest renovate slim release
      - name: Validate configuration
        run: |
          # renovate: datasource=docker
          export RENOVATE_IMAGE=ghcr.io/renovatebot/renovate:43.260.0@sha256:b4c05f43e95841808410b1b2c106bbf4560218c6dbe847abcde22a9fa9ece7e1
          docker run --rm --entrypoint "renovate-config-validator" \
            -v "${{ github.workspace }}/.github/renovate.json5":"/renovate.json5" \
            ${RENOVATE_IMAGE} "/renovate.json5"
